In [7]:
import pandas as pd

# create a dummy data for INDIA cities
india_weather = {
    "city": ["mumbai"] * 5 + ["lucknow"] * 5 + ["delhi"] * 5,
    "humidity": [
        # Mumbai (humid, coastal)
        82, 85, 80, 88, 90,
        # Lucknow (moderate humidity)
        60, 65, 70, 55, 62,
        # Delhi (dry, lower humidity)
        45, 50, 40, 42, 47
    ],
    "precipitation": [
        # Mumbai (frequent rain in monsoon season)
        15.2, 12.5, 20.1, 10.0, 18.3,
        # Lucknow (occasional rain)
        5.0, 2.2, 0.0, 3.1, 1.5,
        # Delhi (less rainfall generally)
        0.0, 0.5, 0.0, 1.2, 0.0
    ],
    "Temperature": [
        # Mumbai (warm and stable)
        29, 30, 31, 28, 29,
        # Lucknow (hotter variation)
        34, 36, 33, 35, 37,
        # Delhi (very hot summers)
        38, 40, 39, 41, 42
    ]
}

# create a dataFrame from this dummy data
df_india = pd.DataFrame(india_weather)
df_india

       city  humidity  precipitation  Temperature
0    mumbai        82           15.2           29
1    mumbai        85           12.5           30
2    mumbai        80           20.1           31
3    mumbai        88           10.0           28
4    mumbai        90           18.3           29
5   lucknow        60            5.0           34
6   lucknow        65            2.2           36
7   lucknow        70            0.0           33
8   lucknow        55            3.1           35
9   lucknow        62            1.5           37
10    delhi        45            0.0           38
11    delhi        50            0.5           40
12    delhi        40            0.0           39
13    delhi        42            1.2           41
14    delhi        47            0.0           42

In [8]:
# create a dummy data for USA cities
usa_weather = {
    "city": ["new_york"] * 5 + ["los_angeles"] * 5 + ["chicago"] * 5,
    "humidity": [
        # New York (moderate humidity, seasonal)
        70, 65, 68, 72, 75,
        # Los Angeles (dry and warm)
        55, 50, 52, 48, 53,
        # Chicago (humid summers, cold winters)
        60, 62, 58, 65, 63
    ],
    "precipitation": [
        # New York (occasional rain)
        3.2, 5.1, 4.0, 2.8, 6.5,
        # Los Angeles (very low rainfall)
        0.0, 0.2, 0.0, 0.1, 0.0,
        # Chicago (rain and snow depending on season)
        4.0, 3.5, 6.0, 2.0, 5.2
    ],
    "Temperature": [
        # New York (mild summers, cold winters)
        25, 28, 22, 27, 30,
        # Los Angeles (warmer, stable weather)
        32, 34, 33, 31, 35,
        # Chicago (more variation, colder in winter)
        20, 18, 22, 19, 21
    ]
}

df_usa = pd.DataFrame(usa_weather)
df_usa

           city  humidity  precipitation  Temperature
0      new_york        70            3.2           25
1      new_york        65            5.1           28
2      new_york        68            4.0           22
3      new_york        72            2.8           27
4      new_york        75            6.5           30
5   los_angeles        55            0.0           32
6   los_angeles        50            0.2           34
7   los_angeles        52            0.0           33
8   los_angeles        48            0.1           31
9   los_angeles        53            0.0           35
10      chicago        60            4.0           20
11      chicago        62            3.5           18
12      chicago        58            6.0           22
13      chicago        65            2.0           19
14      chicago        63            5.2           21

## Concatinate df_india and df_usa into one dataFrame

In [10]:
concatinated_df = pd.concat([df_india,df_usa])
concatinated_df

           city  humidity  precipitation  Temperature
0        mumbai        82           15.2           29
1        mumbai        85           12.5           30
2        mumbai        80           20.1           31
3        mumbai        88           10.0           28
4        mumbai        90           18.3           29
5       lucknow        60            5.0           34
6       lucknow        65            2.2           36
7       lucknow        70            0.0           33
8       lucknow        55            3.1           35
9       lucknow        62            1.5           37
10        delhi        45            0.0           38
11        delhi        50            0.5           40
12        delhi        40            0.0           39
13        delhi        42            1.2           41
14        delhi        47            0.0           42
0      new_york        70            3.2           25
1      new_york        65            5.1           28
2      new_york        68            4.0           22
3      new_york        72            2.8           27
4      new_york        75            6.5           30
5   los_angeles        55            0.0           32
6   los_angeles        50            0.2           34
7   los_angeles        52            0.0           33
8   los_angeles        48            0.1           31
9   los_angeles        53            0.0           35
10      chicago        60            4.0           20
11      chicago        62            3.5           18
12      chicago        58            6.0           22
13      chicago        65            2.0           19
14      chicago        63            5.2           21

### Explaiantion:
```pd.concat([df_india,df_usa])``` takes in multiple dataFrames in a list, concatinates it and then returns a new dataFrame as a result. This ```.concat()``` function can concatinate multiple dataFrames either row wise or column wise based on wheather you pass ```axis=0``` (default, row wise concatination) or ```axis=1``` (column wise concatination). Since I passed nothing in the ```axis``` parameter it concatinated the ```df_india``` dataFrame and ```df_usa``` dataFrame row-wise. 

### Internal working:
1. Takes in the list of DataFrames :
   - It expects them to have the same of atleast overloapping columns.
   - If columns don't match, it fills missing values with ```NaN```.
2. Determines axis (default is ```axis=0```) :
   - ```axis=0``` row wise (vertical stacking)
   - ```axis=1``` column wise (horizontal stacking)
3. Aligns by column or index :
   - If ```axis=0``` -> aligns by column names.
   - If ```axis=1``` -> alings by index values.
4. Creates a new DataFrame
   - The result is a brand-new dataFrame . No changes are made to the original dataFrames.

### Limitations of ```pd.concat```
1. Columns mismatch:
   - If ```df_india``` has ```["city", "temperature"]``` and ```df_usa``` has ```["city","humidity"]```,  the missing columns will be filled with ```NaN```. The resulting DataFrame will contain both the columns with NaNs where data is missing.
2. Index issues:
   - By default it preserves the original indexes.
   - This can lead to duplicate indexes.
   - Example both DataFrames starts with ```0,1,2,3``` the concatinated result will have dataFrame indexes like this ```0,1,2,3,0,1,2,3```.
   - Solution : ```pd.concate([df1,df2],ignore_index=True)```
   - This is what is happening in the above example ```concatinated_df```
3. Not relational joining:
   - Concat just stacks data. It doesn't merge based on keys like SQL ```JOIN```.
   - For relational joining use ```pd.merge()```
4. Memory usage:
   - Concatenation creates a new DataFrame (copies data) which can be very expensive when it comes to hardware resource usage for very large DataFrames.

### When to use ```pd.concat()```:
- You want to stack multiple datasets with the same schema (like monthly sales, wheather data of multiple countires , sensor logs etc.)
- You want column-wise combination of related data aligned by index (axis=1).
- You need to quickly glue multiple DataFrames into one.

### When not to use ```pd.concat()```:
- You need to join datasets by keys/IDs (like customer_id, order_id) --> Use ```pd.merge()``` instead.
- Your DataFrames have mismatched schemas (too many missing values after concat).
- You want to append only few rows repeatedly instead of pd.concat in a loop better to collect rows in a list and dataFrame once (Improves the performance drastically)

In [12]:
concatinated_df2 = pd.concat([df_india,df_usa],ignore_index=True)
concatinated_df2

           city  humidity  precipitation  Temperature
0        mumbai        82           15.2           29
1        mumbai        85           12.5           30
2        mumbai        80           20.1           31
3        mumbai        88           10.0           28
4        mumbai        90           18.3           29
5       lucknow        60            5.0           34
6       lucknow        65            2.2           36
7       lucknow        70            0.0           33
8       lucknow        55            3.1           35
9       lucknow        62            1.5           37
10        delhi        45            0.0           38
11        delhi        50            0.5           40
12        delhi        40            0.0           39
13        delhi        42            1.2           41
14        delhi        47            0.0           42
15     new_york        70            3.2           25
16     new_york        65            5.1           28
17     new_york        68            4.0           22
18     new_york        72            2.8           27
19     new_york        75            6.5           30
20  los_angeles        55            0.0           32
21  los_angeles        50            0.2           34
22  los_angeles        52            0.0           33
23  los_angeles        48            0.1           31
24  los_angeles        53            0.0           35
25      chicago        60            4.0           20
26      chicago        62            3.5           18
27      chicago        58            6.0           22
28      chicago        65            2.0           19
29      chicago        63            5.2           21