# Concatinate function in Pandas

In [57]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

# create a dummy data for INDIA cities
india_weather = {
    "city": ["mumbai"] * 5 + ["lucknow"] * 5 + ["delhi"] * 5,
    "humidity": [
        # Mumbai (humid, coastal)
        82, 85, 80, 88, 90,
        # Lucknow (moderate humidity)
        60, 65, 70, 55, 62,
        # Delhi (dry, lower humidity)
        45, 50, 40, 42, 47
    ],
    "precipitation": [
        # Mumbai (frequent rain in monsoon season)
        15.2, 12.5, 20.1, 10.0, 18.3,
        # Lucknow (occasional rain)
        5.0, 2.2, 0.0, 3.1, 1.5,
        # Delhi (less rainfall generally)
        0.0, 0.5, 0.0, 1.2, 0.0
    ],
    "Temperature": [
        # Mumbai (warm and stable)
        29, 30, 31, 28, 29,
        # Lucknow (hotter variation)
        34, 36, 33, 35, 37,
        # Delhi (very hot summers)
        38, 40, 39, 41, 42
    ]
}

# create a dataFrame from this dummy data
df_india = pd.DataFrame(india_weather)
df_india

       city  humidity  precipitation  Temperature
0    mumbai        82           15.2           29
1    mumbai        85           12.5           30
2    mumbai        80           20.1           31
3    mumbai        88           10.0           28
4    mumbai        90           18.3           29
5   lucknow        60            5.0           34
6   lucknow        65            2.2           36
7   lucknow        70            0.0           33
8   lucknow        55            3.1           35
9   lucknow        62            1.5           37
10    delhi        45            0.0           38
11    delhi        50            0.5           40
12    delhi        40            0.0           39
13    delhi        42            1.2           41
14    delhi        47            0.0           42

In [58]:
# create a dummy data for USA cities
usa_weather = {
    "city": ["new_york"] * 5 + ["los_angeles"] * 5 + ["chicago"] * 5,
    "humidity": [
        # New York (moderate humidity, seasonal)
        70, 65, 68, 72, 75,
        # Los Angeles (dry and warm)
        55, 50, 52, 48, 53,
        # Chicago (humid summers, cold winters)
        60, 62, 58, 65, 63
    ],
    "precipitation": [
        # New York (occasional rain)
        3.2, 5.1, 4.0, 2.8, 6.5,
        # Los Angeles (very low rainfall)
        0.0, 0.2, 0.0, 0.1, 0.0,
        # Chicago (rain and snow depending on season)
        4.0, 3.5, 6.0, 2.0, 5.2
    ],
    "Temperature": [
        # New York (mild summers, cold winters)
        25, 28, 22, 27, 30,
        # Los Angeles (warmer, stable weather)
        32, 34, 33, 31, 35,
        # Chicago (more variation, colder in winter)
        20, 18, 22, 19, 21
    ]
}

df_usa = pd.DataFrame(usa_weather)
df_usa

           city  humidity  precipitation  Temperature
0      new_york        70            3.2           25
1      new_york        65            5.1           28
2      new_york        68            4.0           22
3      new_york        72            2.8           27
4      new_york        75            6.5           30
5   los_angeles        55            0.0           32
6   los_angeles        50            0.2           34
7   los_angeles        52            0.0           33
8   los_angeles        48            0.1           31
9   los_angeles        53            0.0           35
10      chicago        60            4.0           20
11      chicago        62            3.5           18
12      chicago        58            6.0           22
13      chicago        65            2.0           19
14      chicago        63            5.2           21

## Concatinate df_india and df_usa into one dataFrame (Row-wise concatination)

In [59]:
concatinated_df = pd.concat([df_india,df_usa])
concatinated_df

           city  humidity  precipitation  Temperature
0        mumbai        82           15.2           29
1        mumbai        85           12.5           30
2        mumbai        80           20.1           31
3        mumbai        88           10.0           28
4        mumbai        90           18.3           29
5       lucknow        60            5.0           34
6       lucknow        65            2.2           36
7       lucknow        70            0.0           33
8       lucknow        55            3.1           35
9       lucknow        62            1.5           37
10        delhi        45            0.0           38
11        delhi        50            0.5           40
12        delhi        40            0.0           39
13        delhi        42            1.2           41
14        delhi        47            0.0           42
0      new_york        70            3.2           25
1      new_york        65            5.1           28
2      new_york        68            4.0           22
3      new_york        72            2.8           27
4      new_york        75            6.5           30
5   los_angeles        55            0.0           32
6   los_angeles        50            0.2           34
7   los_angeles        52            0.0           33
8   los_angeles        48            0.1           31
9   los_angeles        53            0.0           35
10      chicago        60            4.0           20
11      chicago        62            3.5           18
12      chicago        58            6.0           22
13      chicago        65            2.0           19
14      chicago        63            5.2           21

### Explaiantion:
```pd.concat([df_india,df_usa])``` takes in multiple dataFrames in a list, concatinates it and then returns a new dataFrame as a result. This ```.concat()``` function can concatinate multiple dataFrames either row wise or column wise based on wheather you pass ```axis=0``` (default, row wise concatination) or ```axis=1``` (column wise concatination). Since I passed nothing in the ```axis``` parameter it concatinated the ```df_india``` dataFrame and ```df_usa``` dataFrame row-wise. 

### Internal working:
1. Takes in the list of DataFrames :
   - It expects them to have the same of atleast overloapping columns.
   - If columns don't match, it fills missing values with ```NaN```.
2. Determines axis (default is ```axis=0```) :
   - ```axis=0``` row wise (vertical stacking)
   - ```axis=1``` column wise (horizontal stacking)
3. Aligns by column or index :
   - If ```axis=0``` -> aligns by column names.
   - If ```axis=1``` -> alings by index values.
4. Creates a new DataFrame
   - The result is a brand-new dataFrame . No changes are made to the original dataFrames.

### Limitations of ```pd.concat```
1. Columns mismatch:
   - If ```df_india``` has ```["city", "temperature"]``` and ```df_usa``` has ```["city","humidity"]```,  the missing columns will be filled with ```NaN```. The resulting DataFrame will contain both the columns with NaNs where data is missing.
2. Index issues:
   - By default it preserves the original indexes.
   - This can lead to duplicate indexes.
   - Example both DataFrames starts with ```0,1,2,3``` the concatinated result will have dataFrame indexes like this ```0,1,2,3,0,1,2,3```.
   - Solution : ```pd.concate([df1,df2],ignore_index=True)```
   - This is what is happening in the above example ```concatinated_df```
3. Not relational joining:
   - Concat just stacks data. It doesn't merge based on keys like SQL ```JOIN```.
   - For relational joining use ```pd.merge()``` . If you ever wish to use merge function then you must atleast one common column that can be used by this function to join the two dataFrame : <br>
     Example -> <br>
     ```python
        df_india_temps = {
            "city" : ["Lucknow", "Pune"],
            "temperature" : [22,32],
        }
        df_india_humidity = {
            "city" : ["Lucknow","Pune"],
            "humidity" : [70,89]
        }
        merged_df = pd.merge(df_india_temps,df_india_humidity,on="city")
        print(f"merged_df --> \n {merged_df}")
     ```
4. Memory usage:
   - Concatenation creates a new DataFrame (copies data) which can be very expensive when it comes to hardware resource usage for very large DataFrames.

### When to use ```pd.concat()```:
- You want to stack multiple datasets with the same schema (like monthly sales, wheather data of multiple countires , sensor logs etc.)
- You want column-wise combination of related data aligned by index (axis=1).
- You need to quickly glue multiple DataFrames into one.

### When not to use ```pd.concat()```:
- You need to join datasets by keys/IDs (like customer_id, order_id) --> Use ```pd.merge()``` instead.
- Your DataFrames have mismatched schemas (too many missing values after concat).
- You want to append only few rows repeatedly instead of pd.concat in a loop better to collect rows in a list and dataFrame once (Improves the performance drastically)

In [60]:
concatinated_df2 = pd.concat([df_india,df_usa],ignore_index=True)
concatinated_df2

           city  humidity  precipitation  Temperature
0        mumbai        82           15.2           29
1        mumbai        85           12.5           30
2        mumbai        80           20.1           31
3        mumbai        88           10.0           28
4        mumbai        90           18.3           29
5       lucknow        60            5.0           34
6       lucknow        65            2.2           36
7       lucknow        70            0.0           33
8       lucknow        55            3.1           35
9       lucknow        62            1.5           37
10        delhi        45            0.0           38
11        delhi        50            0.5           40
12        delhi        40            0.0           39
13        delhi        42            1.2           41
14        delhi        47            0.0           42
15     new_york        70            3.2           25
16     new_york        65            5.1           28
17     new_york        68            4.0           22
18     new_york        72            2.8           27
19     new_york        75            6.5           30
20  los_angeles        55            0.0           32
21  los_angeles        50            0.2           34
22  los_angeles        52            0.0           33
23  los_angeles        48            0.1           31
24  los_angeles        53            0.0           35
25      chicago        60            4.0           20
26      chicago        62            3.5           18
27      chicago        58            6.0           22
28      chicago        65            2.0           19
29      chicago        63            5.2           21

### You can also use keys to concat two dataFrames using ```.concat()``` function into a single dataFrame.

In [61]:
df_concat_using_keys = pd.concat([df_india,df_usa],ignore_index=False,keys=["INDIA","U.S.A"])
df_concat_using_keys

                 city  humidity  precipitation  Temperature
INDIA 0        mumbai        82           15.2           29
      1        mumbai        85           12.5           30
      2        mumbai        80           20.1           31
      3        mumbai        88           10.0           28
      4        mumbai        90           18.3           29
      5       lucknow        60            5.0           34
      6       lucknow        65            2.2           36
      7       lucknow        70            0.0           33
      8       lucknow        55            3.1           35
      9       lucknow        62            1.5           37
      10        delhi        45            0.0           38
      11        delhi        50            0.5           40
      12        delhi        40            0.0           39
      13        delhi        42            1.2           41
      14        delhi        47            0.0           42
U.S.A 0      new_york        70            3.2           25
      1      new_york        65            5.1           28
      2      new_york        68            4.0           22
      3      new_york        72            2.8           27
      4      new_york        75            6.5           30
      5   los_angeles        55            0.0           32
      6   los_angeles        50            0.2           34
      7   los_angeles        52            0.0           33
      8   los_angeles        48            0.1           31
      9   los_angeles        53            0.0           35
      10      chicago        60            4.0           20
      11      chicago        62            3.5           18
      12      chicago        58            6.0           22
      13      chicago        65            2.0           19
      14      chicago        63            5.2           21

### Explaination : 
```pd.concat([df_india,df_usa],ignore_index=False,keys=["INDIA","U.S.A"])``` The keys parameter in ```.concat()``` function will create additional indexes after the two dataFrames are concatinated into a new dataFrame successfully.

### NOTICE : 
If you set the flag ```ignore_index``` to True then the effect will not take place when you try to use this ```keys=["INDIA","U.S.A"]```. So you need to set this ```ignore_index``` to False before you try to set your own index in the newly created dataFrame that you get after firing up the ```.concat()``` function.

### When to use?
This is particularly useful when you have concatinated the two DataFrames into one DataFrame and for some reason you want the original dataFrame back from the newly concatinated dataFrame that the ```.concat()``` function generates.

### Retrieve data related to india using the newly created indexes by the ```keys``` parameter in the ```.concat()``` function.

In [62]:
df_concat_using_keys.loc["INDIA"]

       city  humidity  precipitation  Temperature
0    mumbai        82           15.2           29
1    mumbai        85           12.5           30
2    mumbai        80           20.1           31
3    mumbai        88           10.0           28
4    mumbai        90           18.3           29
5   lucknow        60            5.0           34
6   lucknow        65            2.2           36
7   lucknow        70            0.0           33
8   lucknow        55            3.1           35
9   lucknow        62            1.5           37
10    delhi        45            0.0           38
11    delhi        50            0.5           40
12    delhi        40            0.0           39
13    delhi        42            1.2           41
14    delhi        47            0.0           42

### Retrieve data related to usa using the newly created indexes by the keys parameter in the .concat() function.¶

In [63]:
df_concat_using_keys.loc["U.S.A"]

           city  humidity  precipitation  Temperature
0      new_york        70            3.2           25
1      new_york        65            5.1           28
2      new_york        68            4.0           22
3      new_york        72            2.8           27
4      new_york        75            6.5           30
5   los_angeles        55            0.0           32
6   los_angeles        50            0.2           34
7   los_angeles        52            0.0           33
8   los_angeles        48            0.1           31
9   los_angeles        53            0.0           35
10      chicago        60            4.0           20
11      chicago        62            3.5           18
12      chicago        58            6.0           22
13      chicago        65            2.0           19
14      chicago        63            5.2           21

## Lets see how ```pd.merge()``` function works

In [64]:
df_india_temps = pd.DataFrame(
    {
    "city" : ["Lucknow", "Pune"],
    "temperature" : [22,32],
}
)

df_india_humidity = pd.DataFrame(
    {
    "city" : ["Lucknow","Pune"],
    "humidity" : [70,89]
}
)
merged_df = pd.merge(df_india_temps,df_india_humidity,on="city")
print(f"merged_df --> \n {merged_df}")

merged_df -->
       city  temperature  humidity
0  Lucknow           22        70
1     Pune           32        89

### Explaination : 
```pd.merge()``` takes in 3 arguments left,right and on :
- left : It is the first dataFrame whose data after the merge is complete will appear on the left hand side of the brand new dataFrame.
- right : It is the second dataFrame whose data after the merge is complete will appear on the right hand side of the brand new dataFrame.
- on : It is used to tell the ```.merge()``` function what column so be used as a common column between the two original dataFrames.

### Difference between ```.merge()``` and ```.concat()``` :
- ```pd.concat()``` Just stacks the two dataFrames either horizondally (axis=1, column-wise) or vertically (axis=0 , row-wise).
- ```pd.merge()``` Like SQL JOIN, it requires a common column (or index) to match rows between DataFrames.

### When to use use ```.merge()```:
- Relational Data (Foreign key - Primary key relationship). Example : You have a customer's table and orders table and you want to combine them into one table.
- Data Enrichment (add new attributes to the already existing data in the table). Example : Attaching weather data to a city dataset
- SQL-Like JOINs (inner, outer, left, right)

### When not to use merge
- Don't use merge when you don't have a common column/index to merge.
- If you want to append rows (like adding more data from the same schema)
- Performance concerns large data
  - ```merge``` can be slow with millions if not indexed properly.
  - If you don't need a key-based join, ```concat``` is much faster.
- Accidental cartesian products (explosion of rows)
- IF your key column isn't unique in both DataFrames , you will get dupliates multiplied. The output will have 4 rows instead of 2 (2x2 join).

## Concatinate df_india and df_usa into one dataFrame (Column-wise concatination)

In [66]:
# create a dummy data for INDIA cities
india_weather_humidity = {
    "city": ["mumbai"] * 5 + ["lucknow"] * 5 + ["delhi"] * 5,
    "humidity": [
        # Mumbai (humid, coastal)
        82, 85, 80, 88, 90,
        # Lucknow (moderate humidity)
        60, 65, 70, 55, 62,
        # Delhi (dry, lower humidity)
        45, 50, 40, 42, 47
    ]
}

india_weather_precipitation = {
    "city": ["mumbai"] * 5 + ["lucknow"] * 5 + ["delhi"] * 5,
    "precipitation": [
        # Mumbai (frequent rain in monsoon season)
        15.2, 12.5, 20.1, 10.0, 18.3,
        # Lucknow (occasional rain)
        5.0, 2.2, 0.0, 3.1, 1.5,
        # Delhi (less rainfall generally)
        0.0, 0.5, 0.0, 1.2, 0.0
    ]
}
india_weather_temperature = {
    "city": ["mumbai"] * 5 + ["lucknow"] * 5 + ["delhi"] * 5,
    "Temperature": [
        # Mumbai (warm and stable)
        29, 30, 31, 28, 29,
        # Lucknow (hotter variation)
        34, 36, 33, 35, 37,
        # Delhi (very hot summers)
        38, 40, 39, 41, 42
    ]
}

india_weather_humidity_df = pd.DataFrame(india_weather_humidity)
india_weather_humidity_df

       city  humidity
0    mumbai        82
1    mumbai        85
2    mumbai        80
3    mumbai        88
4    mumbai        90
5   lucknow        60
6   lucknow        65
7   lucknow        70
8   lucknow        55
9   lucknow        62
10    delhi        45
11    delhi        50
12    delhi        40
13    delhi        42
14    delhi        47

In [67]:
india_weather_precipitation_df = pd.DataFrame(india_weather_precipitation)
india_weather_precipitation_df

       city  precipitation
0    mumbai           15.2
1    mumbai           12.5
2    mumbai           20.1
3    mumbai           10.0
4    mumbai           18.3
5   lucknow            5.0
6   lucknow            2.2
7   lucknow            0.0
8   lucknow            3.1
9   lucknow            1.5
10    delhi            0.0
11    delhi            0.5
12    delhi            0.0
13    delhi            1.2
14    delhi            0.0

In [68]:
india_weather_temperature_df = pd.DataFrame(india_weather_temperature)
india_weather_temperature_df

       city  Temperature
0    mumbai           29
1    mumbai           30
2    mumbai           31
3    mumbai           28
4    mumbai           29
5   lucknow           34
6   lucknow           36
7   lucknow           33
8   lucknow           35
9   lucknow           37
10    delhi           38
11    delhi           40
12    delhi           39
13    delhi           41
14    delhi           42

### Now lets join india_weather_humidity_df, india_weather_precipitation_df and india_weather_temperature_df dataFrames column-wise (horizontal stacking) using ```.concat()``` method

In [69]:
concatinated_column_wise_df = pd.concat([india_weather_humidity_df,india_weather_precipitation_df,india_weather_temperature_df],axis=1)
concatinated_column_wise_df

       city  humidity     city  precipitation     city  Temperature
0    mumbai        82   mumbai           15.2   mumbai           29
1    mumbai        85   mumbai           12.5   mumbai           30
2    mumbai        80   mumbai           20.1   mumbai           31
3    mumbai        88   mumbai           10.0   mumbai           28
4    mumbai        90   mumbai           18.3   mumbai           29
5   lucknow        60  lucknow            5.0  lucknow           34
6   lucknow        65  lucknow            2.2  lucknow           36
7   lucknow        70  lucknow            0.0  lucknow           33
8   lucknow        55  lucknow            3.1  lucknow           35
9   lucknow        62  lucknow            1.5  lucknow           37
10    delhi        45    delhi            0.0    delhi           38
11    delhi        50    delhi            0.5    delhi           40
12    delhi        40    delhi            0.0    delhi           39
13    delhi        42    delhi            1.2    delhi           41
14    delhi        47    delhi            0.0    delhi           42

### Explaination : 
There might be a situation where you don't want to append the dataFrame row-wise (Vertical Stacking), you want to append dataFrame column-wise (Horizontal Stacking).

### But what's this ? I am getting the city column multiple times why is that?
The reason this happens because when I concat column-wise (```axis=1```) then Pandas just sticks the DataFrames side by side without trying to merge on a common column. <br>
So if each of your DataFrames (```india_weather_humidity_df,india_weather_precipitation_df,india_weather_temperature_df```) already has a ```city``` column, you will end up with multiple ```city``` columns. <br>
One of the solution which I went with is to drop the city column from the second and third dataFrame when concatinating them using the ```.concat()``` function.

In [70]:
concatinated_column_wise_fixed_df = pd.concat([india_weather_humidity_df,
                                               india_weather_precipitation_df.drop(columns=["city"]),
                                               india_weather_temperature_df.drop(columns=["city"])],axis=1)
concatinated_column_wise_fixed_df

       city  humidity  precipitation  Temperature
0    mumbai        82           15.2           29
1    mumbai        85           12.5           30
2    mumbai        80           20.1           31
3    mumbai        88           10.0           28
4    mumbai        90           18.3           29
5   lucknow        60            5.0           34
6   lucknow        65            2.2           36
7   lucknow        70            0.0           33
8   lucknow        55            3.1           35
9   lucknow        62            1.5           37
10    delhi        45            0.0           38
11    delhi        50            0.5           40
12    delhi        40            0.0           39
13    delhi        42            1.2           41
14    delhi        47            0.0           42

### Now the dataFrame is looking good

### In real world clean data doesn't exist. Lets se how to stack multiple dataFrames column-wise when data is messy.
Senarios covered : 
- The position of cities are interchanged For example :
  - In the first dataFrame the city Mumbai might be in the first position but in second dataFrame Mumbai is in second position
- There are some missing data in one of the dataFrame example :
  - Let's say the dataFrame doesn't have some data related to the delhi city.

In [75]:
india_weather_humidity = {
    "city":  ["lucknow"] * 5 + ["mumbai"] * 5 + ["delhi"] * 5,
    "humidity": [
        # Lucknow (moderate humidity)
        60, 65, 70, 55, 62,
        # Mumbai (humid, coastal)
        82, 85, 80, 88, 90,
        # Delhi (dry, lower humidity)
        45, 50, 40, 42, 47
    ]
}

india_weather_precipitation = {
    "city": ["mumbai"] * 5 + ["lucknow"] * 5 + ["delhi"] * 5,
    "precipitation": [
        # Mumbai
        15.2, 12.5, 20.1, 10.0, 18.3, 
        # Lucknow
        5.0, 2.2, 0.0, 3.1, 1.5,    
        # Delhi (with missing values)
        0.0, 0.5, 0.0, None, None       
    ]
}

india_weather_temperature = {
    "city": ["mumbai"] * 5 + ["delhi"] * 5 + ["lucknow"] * 5,
    "Temperature": [
        # Mumbai (warm and stable)
        29, 30, 31, 28, 29,
        # Delhi (very hot summers)
        38, 40, 39, 41, 42,
        # Lucknow (hotter variation)
        34, 36, 33, 35, 37,
    ]
}
messy_df_india_temperature = pd.DataFrame(india_weather_temperature)
messy_df_india_temperature

       city  Temperature
0    mumbai           29
1    mumbai           30
2    mumbai           31
3    mumbai           28
4    mumbai           29
5     delhi           38
6     delhi           40
7     delhi           39
8     delhi           41
9     delhi           42
10  lucknow           34
11  lucknow           36
12  lucknow           33
13  lucknow           35
14  lucknow           37

In [76]:
messy_df_india_precipitation = pd.DataFrame(india_weather_precipitation)
messy_df_india_precipitation

       city  precipitation
0    mumbai           15.2
1    mumbai           12.5
2    mumbai           20.1
3    mumbai           10.0
4    mumbai           18.3
5   lucknow            5.0
6   lucknow            2.2
7   lucknow            0.0
8   lucknow            3.1
9   lucknow            1.5
10    delhi            0.0
11    delhi            0.5
12    delhi            0.0
13    delhi            NaN
14    delhi            NaN

In [77]:
messy_df_india_humidity = pd.DataFrame(india_weather_humidity)
messy_df_india_humidity

       city  humidity
0   lucknow        60
1   lucknow        65
2   lucknow        70
3   lucknow        55
4   lucknow        62
5    mumbai        82
6    mumbai        85
7    mumbai        80
8    mumbai        88
9    mumbai        90
10    delhi        45
11    delhi        50
12    delhi        40
13    delhi        42
14    delhi        47

In [78]:
pd.concat([messy_df_india_humidity,messy_df_india_precipitation,messy_df_india_temperature],axis=1)

       city  humidity     city  precipitation     city  Temperature
0   lucknow        60   mumbai           15.2   mumbai           29
1   lucknow        65   mumbai           12.5   mumbai           30
2   lucknow        70   mumbai           20.1   mumbai           31
3   lucknow        55   mumbai           10.0   mumbai           28
4   lucknow        62   mumbai           18.3   mumbai           29
5    mumbai        82  lucknow            5.0    delhi           38
6    mumbai        85  lucknow            2.2    delhi           40
7    mumbai        80  lucknow            0.0    delhi           39
8    mumbai        88  lucknow            3.1    delhi           41
9    mumbai        90  lucknow            1.5    delhi           42
10    delhi        45    delhi            0.0  lucknow           34
11    delhi        50    delhi            0.5  lucknow           36
12    delhi        40    delhi            0.0  lucknow           33
13    delhi        42    delhi            NaN  lucknow           35
14    delhi        47    delhi            NaN  lucknow           37

#### As you can see the generated dataFrame after concatinaton function gets executed is not looking right 
If you look closely you will see that the first row first column has city Lucknow and then the second city column has Mumbai. The rows are not organized properly after the concatination process is complete. It will be difficult to understand data using this dataFrame.
#### Solution :
- Group the data in each of the dataFrames by cities using ```.groupby()``` function
- Figure out a way to index each group individually. This is necessary to make sure that the first record in the dataFrame of the city Mumbai lines up correctly with the rest of the data in other dataFrames.
- Create a helper column for storing rows. This column will be used to align the data based on indexes.
- Merge instead of concat and then drop the the helper column row after its role is done

In [85]:
messy_df_india_humidity["row"] = messy_df_india_humidity.groupby("city").cumcount()
messy_df_india_precipitation["row"] = messy_df_india_precipitation.groupby("city").cumcount()
messy_df_india_temperature["row"] = messy_df_india_temperature.groupby("city").cumcount()

df_final = (messy_df_india_humidity
            .merge(messy_df_india_precipitation, on=["city","row"])
            .merge(messy_df_india_temperature, on=["city","row"])
            .drop(columns="row"))
df_final

       city  humidity  precipitation  Temperature
0   lucknow        60            5.0           34
1   lucknow        65            2.2           36
2   lucknow        70            0.0           33
3   lucknow        55            3.1           35
4   lucknow        62            1.5           37
5    mumbai        82           15.2           29
6    mumbai        85           12.5           30
7    mumbai        80           20.1           31
8    mumbai        88           10.0           28
9    mumbai        90           18.3           29
10    delhi        45            0.0           38
11    delhi        50            0.5           40
12    delhi        40            0.0           39
13    delhi        42            NaN           41
14    delhi        47            NaN           42

#### Explaination
- ```groupby("city")``` groups the DataFrame by each unique city ```(mumbai, lucknow, delhi)```.
- ```.cumcount()``` generates a running counter within each group:
  - For the first row of each city → ```0```
  - Second row → ```1```
  - Third row → ```2``` … etc.
- This ensures that the 1st Mumbai record in humidity lines up with the 1st Mumbai record in precipitation and the 1st Mumbai record in temperature.
- ```First, messy_df_india_humidity.merge(messy_df_india_precipitation, on=["city","row"])```
  -  Combines humidity + precipitation for each (city, row) pair.
- Then ```.merge(messy_df_india_temperature, on=["city","row"])```
  - Adds the temperature data for the same ```(city, row)``` pair.
- Finally ```.drop(columns="row")```
  - Removes the helper column row since it’s no longer needed in the final dataset.
 
#### Why this works ?
- Automatically aligns rows across multiple DataFrames without relying on manual indexes.
- Works even when different dictionaries had different orderings.
- Preserves the missing values ```NaN``` instead of misaligning them.