# Merge function in pandas

### Import necessary libraries

In [6]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

## How to handle uncleaned and messy data when merging multiple dataFrames into a single dataFrame.

### Create data in python dictionaries

In [13]:
india_weather_humidity = {
    "city":  ["lucknow"] * 5 + ["mumbai"] * 5 + ["delhi"] * 5,
    "humidity": [
        # Lucknow (moderate humidity)
        60, 65, 70, 55, 62,
        # Mumbai (humid, coastal)
        82, 85, 80, 88, 90,
        # Delhi (dry, lower humidity)
        45, 50, 40, 42, 47
    ]
}

india_weather_precipitation = {
    "city": ["mumbai"] * 5 + ["lucknow"] * 5 + ["delhi"] * 5,
    "precipitation": [
        # Mumbai
        15.2, 12.5, 20.1, 10.0, 18.3, 
        # Lucknow
        5.0, 2.2, 0.0, 3.1, 1.5,    
        # Delhi (with missing values)
        0.0, 0.5, 0.0, None, None       
    ]
}

india_weather_temperature = {
    "city": ["mumbai"] * 5 + ["delhi"] * 5 + ["lucknow"] * 5,
    "Temperature": [
        # Mumbai (warm and stable)
        29, 30, 31, 28, 29,
        # Delhi (very hot summers)
        38, 40, 39, 41, 42,
        # Lucknow (hotter variation)
        34, 36, 33, 35, 37,
    ]
}

### Create dataFrame from the data created earlier

In [14]:
messy_df_india_temperature = pd.DataFrame(india_weather_temperature)
messy_df_india_temperature

       city  Temperature
0    mumbai           29
1    mumbai           30
2    mumbai           31
3    mumbai           28
4    mumbai           29
5     delhi           38
6     delhi           40
7     delhi           39
8     delhi           41
9     delhi           42
10  lucknow           34
11  lucknow           36
12  lucknow           33
13  lucknow           35
14  lucknow           37

In [15]:
messy_df_india_precipitation = pd.DataFrame(india_weather_precipitation)
messy_df_india_precipitation

       city  precipitation
0    mumbai           15.2
1    mumbai           12.5
2    mumbai           20.1
3    mumbai           10.0
4    mumbai           18.3
5   lucknow            5.0
6   lucknow            2.2
7   lucknow            0.0
8   lucknow            3.1
9   lucknow            1.5
10    delhi            0.0
11    delhi            0.5
12    delhi            0.0
13    delhi            NaN
14    delhi            NaN

In [16]:
messy_df_india_humidity = pd.DataFrame(india_weather_humidity)
messy_df_india_humidity

       city  humidity
0   lucknow        60
1   lucknow        65
2   lucknow        70
3   lucknow        55
4   lucknow        62
5    mumbai        82
6    mumbai        85
7    mumbai        80
8    mumbai        88
9    mumbai        90
10    delhi        45
11    delhi        50
12    delhi        40
13    delhi        42
14    delhi        47

### Group all the data in the dataFrames and Index the dataFrames and create a helping column called rows to store the generated indexes in the respective dataFrame

In [17]:
messy_df_india_humidity["row"] = messy_df_india_humidity.groupby("city").cumcount()
messy_df_india_precipitation["row"] = messy_df_india_precipitation.groupby("city").cumcount()
messy_df_india_temperature["row"] = messy_df_india_temperature.groupby("city").cumcount()

In [18]:
merged_df = (messy_df_india_humidity.merge(messy_df_india_precipitation, on=["city","row"]).merge(messy_df_india_temperature,on=["city","row"]).drop(columns="row"))
merged_df

       city  humidity  precipitation  Temperature
0   lucknow        60            5.0           34
1   lucknow        65            2.2           36
2   lucknow        70            0.0           33
3   lucknow        55            3.1           35
4   lucknow        62            1.5           37
5    mumbai        82           15.2           29
6    mumbai        85           12.5           30
7    mumbai        80           20.1           31
8    mumbai        88           10.0           28
9    mumbai        90           18.3           29
10    delhi        45            0.0           38
11    delhi        50            0.5           40
12    delhi        40            0.0           39
13    delhi        42            NaN           41
14    delhi        47            NaN           42