# Read database records into pandas dataFrame and write it back

This will cover:
- pd.read_sql_table
- pd.read_sql_query
- df.to_sql
- pd.read_sql (which is just a wrapper for the first two methods)

## Create the table by using PGAdmin

The reason I am using posgreSql because I am familiar with it since I mostly work with PostgreSQL when working in Django and FastAPI. You are Free to use any database of your choose the steps are the same only some of the implementation will change if you choose to use a non-relational database example : MongoDB. 
Libraries that I had to install : 
1. psycopg
2. SQLAlchemy (manage database connections)
3. python-decouple (To get the database creds from .env file)
4. Pydantic (You can skip it if you don't want to write type safe functions) 
<br>

```
-- Create a customers table
CREATE TABLE Customers (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
phone_number VARCHAR(10) 
);

-- Insert data into the customers table
INSERT INTO Customers (name,phone_number) VALUES
('Rollex', '9972688590'),
('Ballistic', '1000688590'),
('Barricade', '2472688590'),
('Bullet', '7622688590'),
('Barbatos', '1172688590'),
('Artillery', '1502688590'),
('Shotgun', '1852688590'),
('Kombat', '3652688590'),
('Lockdown', '1442688590'),
('Ignition', '6000688590'),
('Shockwave', '3602688590'),
('PointBreak', '7472688590'),
('GroundZero', '8002688590'),
('Interceptor','9112688590');

-- check if the data has been successfully inserted into the customers table
SELECT * FROM Customers;

-- Create an orders table
CREATE TABLE Orders (
id BIGSERIAL PRIMARY KEY,
customer_id BIGINT NOT NULL,
name VARCHAR(255) NOT NULL,
amount MONEY NOT NULL,
order_date TIMESTAMP DEFAULT NOW(),
CONSTRAINT fk_customer FOREIGN KEY (customer_id)
REFERENCES Customers (id)
ON DELETE CASCADE
);

-- insert the data into the orders table
INSERT INTO Orders (customer_id,name,amount) VALUES
(1,'50 calibure fully automatic Browning machine gun',9978.123),
(2,'50 calibure desert eagle handgun',1000.123),
(3,'500 S and W Magnum',2470.123),
(4,'Anzio 20mm anti material sniper rifle',7620.123),
(5,'Beretta m9 9mm',1170.123),
(6,'Milkor MGL (40mm Multiple Grenade Launcher)',1500.123),
(7,'Benelli M4 (M1014) 12 gauge shotgun shell',1850.123),
(8,'AK-47',3650.123),
(9,'M249 SAW Mk 48 Mod 1 7.62×51mm',3650.123),
(10,'Javelin rocket launcher',6000.123),
(11,'Milkor MGL (40mm Multiple Grenade Launcher)',3600.123),
(12,'FN SCAR-H (Special Operations Forces Combat Assault Rifle - Heavy)',7470.123),
(13,'M249 SAW Mk 48 Mod 1 7.62×51mm',8000.123),
(14,'Beretta m9 9mm',9110.123);

-- check if the data is present in the orders table
SELECT * FROM Orders;
```

## Import all the necessary packages

In [1]:
from pydantic import BaseModel, Field, ValidationError
from typing import List,Optional
from decouple import config, Config,RepositoryEnv

from sqlalchemy import create_engine
from sqlalchemy.engine import Engine
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import itertools

# import path so that I can tell pandas where to look for env file in the file system.
from pathlib import Path

## Create a Pydantic model for database configuration

In [2]:
class DBConfig(BaseModel):
    db_name:str=Field(default=None)
    user:str=Field(default=None)
    password:str=Field(default=None)
    host:str=Field(default="localhost")
    port:str=Field(default=5432)

## Create a common function to create a database connection using sqlAlchemy database engine

In [3]:
def database_engine(config:DBConfig) -> Engine:
    engine = create_engine(
        f"postgresql+psycopg2://{config.user}:{config.password}@{config.host}:{config.port}/{config.db_name}"
    )
    return engine

## Tell pandas where to look for env file

In [4]:

env_path = Path("/home/aditya/github/Deep-learning-prerequisite/pandas/pandas_code/database_to_pandas/.env")
config = Config(RepositoryEnv(env_path))

## Change the working directory in Jupyter

In [5]:
import os
os.chdir("/home/aditya/github/Deep-learning-prerequisite/pandas/pandas_code/database_to_pandas/")

## Create db engine object

In [6]:
db_config=DBConfig(
    db_name=config("DB_NAME"),
    user=config("DB_USER"),
    password=config("DB_PASSWORD"),
    host=config("DB_HOST"),
    port=config("DB_PORT")
)
engine_obj=database_engine(db_config)
engine_obj

Engine(postgresql+psycopg2://postgres:***@localhost:5432/Pandas)

## Create a Pydantic model for reading table from database

In [7]:
class ReadDbTableModel(BaseModel):
    table_name:str=Field(default=None)
    engine:Engine

PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'sqlalchemy.engine.base.Engine'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.11/u/schema-for-unknown-type

### Analysis : 
```
PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'sqlalchemy.engine.base.Engine'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
```

<br>

This error is acutally coming from Pydantic and it's expected when I try to use arbitrary Python types (like ```sqlalchemy.engine.base.Engine```) as fields.
By default Pydantic cannot generate a schema for ```Engine``` because it's not a "standard" type, You have two ways to fix it:
### Solution:
There are two solutions to this predicament that I am in 
- Solution 1 : Use a validator or store as Any
  - If you don't care about the type checking for engine but just want Pydantic to accept it . This works but you lose "type hint" benefits.
- Solution 2 : Allow arbitary types
  - You can tell Pydantic to allow any type in the model using ```model_config```:

<br>

I went with solution 2 because I don't want to loose type hint.

In [8]:
class ReadDbTableModel(BaseModel):
    table_name:str=Field(default=None)
    columns:List[str]=Field(default=[])
    engine:Engine
    model_config = {
    "arbitrary_types_allowed":True
    }

In [9]:
def read_db_table(config:ReadDbTableModel) -> pd.DataFrame:
    if not config.table_name:
        raise ValueError("Table name is required!")
    try:
        if not len(config.columns): 
            df = pd.read_sql_table(config.table_name,con=config.engine)
        else:
            df = pd.read_sql_table(config.table_name, con=config.engine, columns=config.columns)
        return df
    except Exception as e:
        raise RuntimeError(f"Failed to read table '{config.table_name}': {e}")

### NOTICE : 
The reason I don't need to manually open or close connection here:
- ```pandas.read_sql_table()``` uses the SQLALchemy engine (```engine```)
- ```SQLAlchemy``` engines manage connection pooling automatically. When I call ```read_sql_table```:
  - It borrows a connection from the pool.
  - Executes the query.
  - Closes (releases) the connection back to the pool when done.
- So connections are managed automatically.

<br>

If I were using a raw connection (like ```psycopg2.connect()```), I'd have to open/close manually. But since I am using ```SQLAlchemy engine``` + ```pandas```, I don't need to.

## Generate a dataFrame from the sql_table from the database

### Get customers data from the database

In [10]:
config_read_customers_table = ReadDbTableModel(table_name="customers", engine=engine_obj)
customers_df = read_db_table(config_read_customers_table)
customers_df

    id         name phone_number
0    1       Rollex   9972688590
1    2    Ballistic   1000688590
2    3    Barricade   2472688590
3    4       Bullet   7622688590
4    5     Barbatos   1172688590
5    6    Artillery   1502688590
6    7      Shotgun   1852688590
7    8       Kombat   3652688590
8    9     Lockdown   1442688590
9   10     Ignition   6000688590
10  11    Shockwave   3602688590
11  12   PointBreak   7472688590
12  13   GroundZero   8002688590
13  14  Interceptor   9112688590

### Get customers data from database and create dataFrame of the selected columns

#### Get data and create dataFrame of selected name column

In [11]:
config_read_customers_name_table = ReadDbTableModel(table_name="customers", engine=engine_obj,columns=["name"])
customers_name_df = read_db_table(config_read_customers_name_table)
customers_name_df

           name
0        Rollex
1     Ballistic
2     Barricade
3        Bullet
4      Barbatos
5     Artillery
6       Shotgun
7        Kombat
8      Lockdown
9      Ignition
10    Shockwave
11   PointBreak
12   GroundZero
13  Interceptor

#### Get data and create dataFrame of selected phone_number column

In [12]:
config_read_customers_phone_no_table = ReadDbTableModel(table_name="customers",engine=engine_obj,columns=["phone_number"])
customer_phone_number_df = read_db_table(config_read_customers_phone_no_table)
customer_phone_number_df

   phone_number
0    9972688590
1    1000688590
2    2472688590
3    7622688590
4    1172688590
5    1502688590
6    1852688590
7    3652688590
8    1442688590
9    6000688590
10   3602688590
11   7472688590
12   8002688590
13   9112688590

### Get orders data from the database

In [13]:
config_read_orders_table = ReadDbTableModel(table_name="orders", engine=engine_obj)
orders_df = read_db_table(config_read_orders_table)
orders_df

,id,customer_id,name,amount,order_date
0,1,1,50 calibure fully automatic Browning machine gun,"$9,978.12",2025-09-02 16:30:33.322422
1,2,2,50 calibure desert eagle handgun,"$1,000.12",2025-09-02 16:30:33.322422
2,3,3,500 S and W Magnum,"$2,470.12",2025-09-02 16:30:33.322422
3,4,4,Anzio 20mm anti material sniper rifle,"$7,620.12",2025-09-02 16:30:33.322422
4,5,5,Beretta m9 9mm,"$1,170.12",2025-09-02 16:30:33.322422
5,6,6,Milkor MGL (40mm Multiple Grenade Launcher),"$1,500.12",2025-09-02 16:30:33.322422
6,7,7,Benelli M4 (M1014) 12 gauge shotgun shell,"$1,850.12",2025-09-02 16:30:33.322422
7,8,8,AK-47,"$3,650.12",2025-09-02 16:30:33.322422
8,9,9,M249 SAW Mk 48 Mod 1 7.62×51mm,"$3,650.12",2025-09-02 16:30:33.322422
9,10,10,Javelin rocket launcher,"$6,000.12",2025-09-02 16:30:33.322422
10,11,11,Milkor MGL (40mm Multiple Grenade Launcher),"$3,600.12",2025-09-02 16:30:33.322422
11,12,12,FN SCAR-H (Special Operations Forces Combat As...,"$7,470.12",2025-09-02 16:30:33.322422
12,13,13,M249 SAW Mk 48 Mod 1 7.62×51mm,"$8,000.12",2025-09-02 16:30:33.322422
13,14,14,Beretta m9 9mm,"$9,110.12",2025-09-02 16:30:33.322422

#### Read data from the database and only create dataFrame of selected name and amount columns

In [14]:
config_read_orders_table = ReadDbTableModel(table_name="orders",engine=engine_obj,columns=["name","amount"])
oders_name_amount_df = read_db_table(config_read_orders_table)
oders_name_amount_df

                                                 name     amount
0    50 calibure fully automatic Browning machine gun  $9,978.12
1                    50 calibure desert eagle handgun  $1,000.12
2                                  500 S and W Magnum  $2,470.12
3               Anzio 20mm anti material sniper rifle  $7,620.12
4                                      Beretta m9 9mm  $1,170.12
5         Milkor MGL (40mm Multiple Grenade Launcher)  $1,500.12
6           Benelli M4 (M1014) 12 gauge shotgun shell  $1,850.12
7                                               AK-47  $3,650.12
8                      M249 SAW Mk 48 Mod 1 7.62×51mm  $3,650.12
9                             Javelin rocket launcher  $6,000.12
10        Milkor MGL (40mm Multiple Grenade Launcher)  $3,600.12
11  FN SCAR-H (Special Operations Forces Combat As...  $7,470.12
12                     M249 SAW Mk 48 Mod 1 7.62×51mm  $8,000.12
13                                     Beretta m9 9mm  $9,110.12

#### Read data from the database and only create dataFrame of selected name and order_date columns

In [15]:
config_read_orders_table = ReadDbTableModel(table_name="orders",engine=engine_obj,columns=["name","order_date"])
oders_name_order_date_df = read_db_table(config_read_orders_table)
oders_name_order_date_df

,name,order_date
0,50 calibure fully automatic Browning machine gun,2025-09-02 16:30:33.322422
1,50 calibure desert eagle handgun,2025-09-02 16:30:33.322422
2,500 S and W Magnum,2025-09-02 16:30:33.322422
3,Anzio 20mm anti material sniper rifle,2025-09-02 16:30:33.322422
4,Beretta m9 9mm,2025-09-02 16:30:33.322422
5,Milkor MGL (40mm Multiple Grenade Launcher),2025-09-02 16:30:33.322422
6,Benelli M4 (M1014) 12 gauge shotgun shell,2025-09-02 16:30:33.322422
7,AK-47,2025-09-02 16:30:33.322422
8,M249 SAW Mk 48 Mod 1 7.62×51mm,2025-09-02 16:30:33.322422
9,Javelin rocket launcher,2025-09-02 16:30:33.322422
10,Milkor MGL (40mm Multiple Grenade Launcher),2025-09-02 16:30:33.322422
11,FN SCAR-H (Special Operations Forces Combat As...,2025-09-02 16:30:33.322422
12,M249 SAW Mk 48 Mod 1 7.62×51mm,2025-09-02 16:30:33.322422
13,Beretta m9 9mm,2025-09-02 16:30:33.322422

## There is another way to create a dataFrame by reading table from the database that is using raw SQL Queries in Pandas

In [16]:
query = """SELECT 
                c.id AS customer_id , 
                c.name AS customer_name,
                c.phone_number as phone_no,
                o.id AS order_id,
                o.name AS order_name,
                o.amount,
                o.order_date
            FROM customers c
            INNER JOIN Orders o on c.id = o.customer_id ORDER BY o.order_date DESC;
        """
df=pd.read_sql_query(query,engine_obj)
df

,customer_id,customer_name,phone_no,order_id,order_name,amount,order_date
0,1,Rollex,9972688590,1,50 calibure fully automatic Browning machine gun,"$9,978.12",2025-09-02 16:30:33.322422
1,2,Ballistic,1000688590,2,50 calibure desert eagle handgun,"$1,000.12",2025-09-02 16:30:33.322422
2,3,Barricade,2472688590,3,500 S and W Magnum,"$2,470.12",2025-09-02 16:30:33.322422
3,4,Bullet,7622688590,4,Anzio 20mm anti material sniper rifle,"$7,620.12",2025-09-02 16:30:33.322422
4,5,Barbatos,1172688590,5,Beretta m9 9mm,"$1,170.12",2025-09-02 16:30:33.322422
5,6,Artillery,1502688590,6,Milkor MGL (40mm Multiple Grenade Launcher),"$1,500.12",2025-09-02 16:30:33.322422
6,7,Shotgun,1852688590,7,Benelli M4 (M1014) 12 gauge shotgun shell,"$1,850.12",2025-09-02 16:30:33.322422
7,8,Kombat,3652688590,8,AK-47,"$3,650.12",2025-09-02 16:30:33.322422
8,9,Lockdown,1442688590,9,M249 SAW Mk 48 Mod 1 7.62×51mm,"$3,650.12",2025-09-02 16:30:33.322422
9,10,Ignition,6000688590,10,Javelin rocket launcher,"$6,000.12",2025-09-02 16:30:33.322422
10,11,Shockwave,3602688590,11,Milkor MGL (40mm Multiple Grenade Launcher),"$3,600.12",2025-09-02 16:30:33.322422
11,12,PointBreak,7472688590,12,FN SCAR-H (Special Operations Forces Combat As...,"$7,470.12",2025-09-02 16:30:33.322422
12,13,GroundZero,8002688590,13,M249 SAW Mk 48 Mod 1 7.62×51mm,"$8,000.12",2025-09-02 16:30:33.322422
13,14,Interceptor,9112688590,14,Beretta m9 9mm,"$9,110.12",2025-09-02 16:30:33.322422

### Analysis
- Now this works fine but according to what I have learned from my past experience that raw SQL queries must not exist in the code (correct me if I am wrong). 
- In django there is a way that you can use raw sql queries instead of built in ORM. In some cases when executing complex queries we may have to use raw sql queries. It is very tempting but it must be avoided at all cost.
- For example : Lets's suppose there are two tables customers and orders and you want to join the two table and return the data to the front-end. It is very tempting to just use raw sql query like this
  - Create a serializer : 
  ```python

    from rest_framework import serializers
    
    class CustomerOrderSerializer(serializers.Serializer):
        customer_id = serializers.IntegerField()
        customer_name = serializers.CharField()
        phone_number = serializers.CharField()
        order_id = serializers.IntegerField()
        order_name = serializers.CharField()
        amount = serializers.DecimalField(max_digits=12, decimal_places=2)
        order_date = serializers.DateTimeField()
  ```
   - This serialzies the data into JSON from a python object.
  - Create a view:
    ```python
    from django.db import connection
    from rest_framework.views import APIView
    from rest_framework.response import Response
    from .serializers import CustomerOrderSerializer
    
    class CustomerOrderListView(APIView):
        def get(self, request):
            query = """
            SELECT 
                c.id AS customer_id,
                c.name AS customer_name,
                c.phone_number,
                o.id AS order_id,
                o.name AS order_name,
                o.amount,
                o.order_date
            FROM Customers c
            INNER JOIN Orders o ON c.id = o.customer_id
            ORDER BY c.id;
            """
            with connection.cursor() as cursor:
                cursor.execute(query)
                columns = [col[0] for col in cursor.description]
                results = [
                    dict(zip(columns, row))
                    for row in cursor.fetchall()
                ]
    
            serializer = CustomerOrderSerializer(results, many=True)
            return Response(serializer.data)    
    ```
    - As you can see in this example I have used a raw SQL query to join the two table togeather and then sending it to the front-end (BEWARE don't do it). I literally got chewed on by my senior during my PR review when I was just a traniee for this unforgivable blasphemy.
### Reasons why raw sql queries must be avoided?
- For basic CRUD operations (Create, Read, Update, Delete) – the ORM is safer, cleaner, and prevents SQL injection.
- For maintainability – ORM queries adapt better if you change your database engine (e.g., PostgreSQL → MySQL).
- For security – ORM parameterization reduces risk of SQL injection.
### So what to do if raw sql queries must be avoided in code and you still want to execute complex sql query
- One of the way to do that is use a database Views or database functions depending on what you are trying to do.
- Create a model
  ```python
    class CustomerOrder(models.Model):
    customer_id = models.BigIntegerField()
    customer_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=10)
    order_id = models.BigIntegerField()
    order_name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    order_date = models.DateTimeField()

    class Meta:
        managed = False  # Django won't try to create or alter this table
        db_table = "customer_orders_view"
  ```
  Now I can use Django ORM queries <br>
  ```python
      CustomerOrder.objects.filter(customer_name__icontains="Rollex").order_by("-order_date")
  ```
### Reasons to use Database Views instead of raw sql queries 
- Encaplusation of complexity:
  - I defined the ```INNER JOIN``` (or any complex query) once in the database.
  - In Django, I can query the view like a normal table -- no raw sql query needed every time.
- Maintainability
  - If my query logic changes, I just need to update the view in PostgreSQL.
  - Django code does not need to change, as long as the column names in the view remain the same.
- Security
  - No direct raw SQL in Python; ORM queries against the view are automatically parameterized.
  - Reduces risk of SQL injection.

## Let's use database Views to fetch the data from the database in Pandas 
For the reasons which I discussed above by taking the example of django. I am going to try to achieve the similar results i.e create a dataFrame but instead of executing raw sql query I am going to use database View. <br>
Now before I start working on Pandas I need to create a database View that I can use in here <br>
```sql
    CREATE OR REPLACE FUNCTION get_customer_orders()
    RETURNS TABLE (
    customer_id BIGINT,
    customer_name VARCHAR,
    phone_number VARCHAR,
    order_id BIGINT,
    order_name VARCHAR,
    amount MONEY,
    order_date TIMESTAMP
    )
    LANGUAGE plpgsql
    AS $$
    BEGIN
    
    	RETURN QUERY
    	SELECT 
    		c.id AS customer_id,
    		c.name AS customer_name,
    		c.phone_number,
    		o.id AS order_id,
    		o.name AS order_name,
    		o.amount,
    		o.order_date
    	FROM customers c 
    	INNER JOIN Orders o on c.id = o.customer_id ORDER BY o.order_date DESC;
    END;
    $$
    
    CREATE OR REPLACE VIEW customer_orders_view AS
    SELECT * FROM get_customer_orders();
```
<br>
Test if the view created works or not : <br>

```sql
    SELECT * FROM customer_orders_view;
```

### I am going to create a common function that reads the data from the database and returns a dataFrame which can be used everywhere

#### Create a pydantic model to make the function type safe

In [17]:
class ReadDBViewModel(BaseModel):
    database_view_name:str=Field(default=None)
    table_name:str=Field(default=None)
    columns:List[str]=Field(default=[])
    engine:Engine
    model_config={
        "arbitrary_types_allowed":True
    }

In [18]:
def read_db_table_db_view_support(config:ReadDBViewModel) -> pd.DataFrame:
    if not config.table_name and not config.database_view_name:
        raise ValueError("Either provide table_name or database_view_name to successfully generate the dataFrame!")
    if config.database_view_name and not config.table_name:
        try:
            if not len(config.columns):
                df = pd.read_sql_table(f"SELECT * FROM {config.database_view_name}",con=config.engine)
            else:
                df = pd.read_sql_table(query,con=config.engine,columns=config.columns)
            return df
        except Exception as e:
            raise RuntimeError(f"Failed to read table '{config.database_view_name}' : {e}")
    if config.table_name and not config.database_view_name:
        try:
            if not len(config.columns):
                df = pd.read_sql_table(config.table_name,con=config.engine)
            else:
                df = pd.read_sql_table(config.table_name,con=config.engine,columns=config.columns)
            return df
        except Exception as e:
            raise RuntimeError(f"Failed to read table '{config.table_name}' : {e}")

In [19]:
db_view_name = "customer_orders_view"
database_view_table = ReadDBViewModel(database_view_name=db_view_name, engine=engine_obj)
database_view_df = read_db_table_db_view_support(database_view_table)
database_view_df

RuntimeError: Failed to read table 'customer_orders_view' : Table SELECT * FROM customer_orders_view not found

### Analysis:
```pd.read_sql_table()``` <br>
- This only works with actual tables in the database (or SQLAlchemy table objects)
- You cannot pass a full SQL query like
  ```python
        query = "SELECT * FROM customer_orders_view"
        df = pd.read_sql_table(query, con=engine_obj)  # ❌ fails
  ```
- Here, read_sql_table tries to find a table literally named ```"SELECT * FROM customer_orders_view"```, which does not exist, hence the error.
### Solution:
After some digging I found out that there is another method that could be used to get the dataFrame using the database View <br>
I have to use this function ```.read_sql_query()``` instead of this function ```read_sql_table()``` 
- ```.read_sql_table()``` function will look for table literally hence it was failing when I tried executing the database view using this query ```SELECT * FROM customer_orders_view```
- ```.read_sql_query()``` function will help us execute the query that will trigger our database View and allow us to get the dataFrame that we desire.

### read_db_table_db_view_support function version 1 : Fixed function that allows us to create dataFrames from database by either supplying table or database view in it as an argument.

In [20]:
def read_db_table_db_view_support(config:ReadDBViewModel) -> pd.DataFrame:
    if not config.table_name and not config.database_view_name:
        raise ValueError("Either provide table_name or database_view_name to successfully generate the dataFrame!")
    if config.database_view_name and not config.table_name:
        try:
            if not len(config.columns):
                df = pd.read_sql_query(f"SELECT * FROM {config.database_view_name}",con=config.engine)
            else:
                df = pd.read_sql_query(f"SELECT * FROM {config.database_view_name}",con=config.engine,columns=config.columns)
            return df
        except Exception as e:
            raise RuntimeError(f"Failed to read table '{config.database_view_name}' : {e}")
    if config.table_name and not config.database_view_name:
        try:
            if not len(config.columns):
                df = pd.read_sql_table(config.table_name,con=config.engine)
            else:
                df = pd.read_sql_table(config.table_name,con=config.engine,columns=config.columns)
            return df
        except Exception as e:
            raise RuntimeError(f"Failed to read table '{config.table_name}' : {e}")

#### Create a dataFrame using database view

In [21]:
db_view_name = "customer_orders_view"
database_view_table = ReadDBViewModel(database_view_name=db_view_name, engine=engine_obj)
database_view_df = read_db_table_db_view_support(database_view_table)
database_view_df

,customer_id,customer_name,phone_number,order_id,order_name,amount,order_date
0,1,Rollex,9972688590,1,50 calibure fully automatic Browning machine gun,"$9,978.12",2025-09-02 16:30:33.322422
1,2,Ballistic,1000688590,2,50 calibure desert eagle handgun,"$1,000.12",2025-09-02 16:30:33.322422
2,3,Barricade,2472688590,3,500 S and W Magnum,"$2,470.12",2025-09-02 16:30:33.322422
3,4,Bullet,7622688590,4,Anzio 20mm anti material sniper rifle,"$7,620.12",2025-09-02 16:30:33.322422
4,5,Barbatos,1172688590,5,Beretta m9 9mm,"$1,170.12",2025-09-02 16:30:33.322422
5,6,Artillery,1502688590,6,Milkor MGL (40mm Multiple Grenade Launcher),"$1,500.12",2025-09-02 16:30:33.322422
6,7,Shotgun,1852688590,7,Benelli M4 (M1014) 12 gauge shotgun shell,"$1,850.12",2025-09-02 16:30:33.322422
7,8,Kombat,3652688590,8,AK-47,"$3,650.12",2025-09-02 16:30:33.322422
8,9,Lockdown,1442688590,9,M249 SAW Mk 48 Mod 1 7.62×51mm,"$3,650.12",2025-09-02 16:30:33.322422
9,10,Ignition,6000688590,10,Javelin rocket launcher,"$6,000.12",2025-09-02 16:30:33.322422
10,11,Shockwave,3602688590,11,Milkor MGL (40mm Multiple Grenade Launcher),"$3,600.12",2025-09-02 16:30:33.322422
11,12,PointBreak,7472688590,12,FN SCAR-H (Special Operations Forces Combat As...,"$7,470.12",2025-09-02 16:30:33.322422
12,13,GroundZero,8002688590,13,M249 SAW Mk 48 Mod 1 7.62×51mm,"$8,000.12",2025-09-02 16:30:33.322422
13,14,Interceptor,9112688590,14,Beretta m9 9mm,"$9,110.12",2025-09-02 16:30:33.322422

#### Create a dataFrame using database View where customer_name, order_name is selected

In [22]:
db_view_name = "customer_orders_view"
database_view_table = ReadDBViewModel(database_view_name=db_view_name, engine=engine_obj,columns=["customer_name","order_name"])
database_view_df = read_db_table_db_view_support(database_view_table)
database_view_df

RuntimeError: Failed to read table 'customer_orders_view' : read_sql_query() got an unexpected keyword argument 'columns'

### Analysis:
Huh? ... Intreseting ... It looks like,  unlike ```.read_sql_table()``` ```.read_sql_query()``` doesn't have a columns argument which means we cannot use it to select columns. <br>
You can refer to this doc if you like https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html 
### Solution:
I have to manually modify the query itself in other words I need to make some changes in the function to make ```read_sql_query()``` function behave like ```.read_sql_table()``` function <br>
### Things I want to achieve:
- Write a function so that the end user who is calling that function can't tell the difference between ```.read_sql_table()``` and ```.read_sql_query()``` which means I will have to keep the arguments passed in this function the same

### read_db_table_db_view_support function version 2 : Adding the support for column selection when using database View to generate the dataFrame

In [23]:
def read_db_table_db_view_support(config:ReadDBViewModel) -> pd.DataFrame:
    if not config.table_name and not config.database_view_name:
        raise ValueError("Either provide table_name or database_view_name to successfully generate the dataFrame!")
    if config.database_view_name and not config.table_name:
        try:
            # database_view = 
            if not len(config.columns):
                df = pd.read_sql_query(f"SELECT * FROM {config.database_view_name}",con=config.engine)
            else:
                df = pd.read_sql_query(f"SELECT {', '.join(config.columns)} FROM {config.database_view_name}",con=config.engine)
            return df
        except Exception as e:
            raise RuntimeError(f"Failed to read table '{config.database_view_name}' : {e}")
    if config.table_name and not config.database_view_name:
        try:
            if not len(config.columns):
                df = pd.read_sql_table(config.table_name,con=config.engine)
            else:
                df = pd.read_sql_table(config.table_name,con=config.engine,columns=config.columns)
            return df
        except Exception as e:
            raise RuntimeError(f"Failed to read table '{config.table_name}' : {e}")

#### Generate a dataFrame from the database using database View using all the columns

In [27]:
db_view_name = "customer_orders_view"
database_view_table = ReadDBViewModel(database_view_name=db_view_name, engine=engine_obj)
database_view_df = read_db_table_db_view_support(database_view_table)
database_view_df

,customer_id,customer_name,phone_number,order_id,order_name,amount,order_date
0,1,Rollex,9972688590,1,50 calibure fully automatic Browning machine gun,"$9,978.12",2025-09-02 16:30:33.322422
1,2,Ballistic,1000688590,2,50 calibure desert eagle handgun,"$1,000.12",2025-09-02 16:30:33.322422
2,3,Barricade,2472688590,3,500 S and W Magnum,"$2,470.12",2025-09-02 16:30:33.322422
3,4,Bullet,7622688590,4,Anzio 20mm anti material sniper rifle,"$7,620.12",2025-09-02 16:30:33.322422
4,5,Barbatos,1172688590,5,Beretta m9 9mm,"$1,170.12",2025-09-02 16:30:33.322422
5,6,Artillery,1502688590,6,Milkor MGL (40mm Multiple Grenade Launcher),"$1,500.12",2025-09-02 16:30:33.322422
6,7,Shotgun,1852688590,7,Benelli M4 (M1014) 12 gauge shotgun shell,"$1,850.12",2025-09-02 16:30:33.322422
7,8,Kombat,3652688590,8,AK-47,"$3,650.12",2025-09-02 16:30:33.322422
8,9,Lockdown,1442688590,9,M249 SAW Mk 48 Mod 1 7.62×51mm,"$3,650.12",2025-09-02 16:30:33.322422
9,10,Ignition,6000688590,10,Javelin rocket launcher,"$6,000.12",2025-09-02 16:30:33.322422
10,11,Shockwave,3602688590,11,Milkor MGL (40mm Multiple Grenade Launcher),"$3,600.12",2025-09-02 16:30:33.322422
11,12,PointBreak,7472688590,12,FN SCAR-H (Special Operations Forces Combat As...,"$7,470.12",2025-09-02 16:30:33.322422
12,13,GroundZero,8002688590,13,M249 SAW Mk 48 Mod 1 7.62×51mm,"$8,000.12",2025-09-02 16:30:33.322422
13,14,Interceptor,9112688590,14,Beretta m9 9mm,"$9,110.12",2025-09-02 16:30:33.322422

#### Generate a dataFrame from database by using database Views after selecting the columns customer_name, order_name

In [28]:
db_view_name = "customer_orders_view"
database_view_table = ReadDBViewModel(database_view_name=db_view_name, engine=engine_obj,columns=["customer_name","order_name"])
database_view_df = read_db_table_db_view_support(database_view_table)
database_view_df

   customer_name                                         order_name
0         Rollex   50 calibure fully automatic Browning machine gun
1      Ballistic                   50 calibure desert eagle handgun
2      Barricade                                 500 S and W Magnum
3         Bullet              Anzio 20mm anti material sniper rifle
4       Barbatos                                     Beretta m9 9mm
5      Artillery        Milkor MGL (40mm Multiple Grenade Launcher)
6        Shotgun          Benelli M4 (M1014) 12 gauge shotgun shell
7         Kombat                                              AK-47
8       Lockdown                     M249 SAW Mk 48 Mod 1 7.62×51mm
9       Ignition                            Javelin rocket launcher
10     Shockwave        Milkor MGL (40mm Multiple Grenade Launcher)
11    PointBreak  FN SCAR-H (Special Operations Forces Combat As...
12    GroundZero                     M249 SAW Mk 48 Mod 1 7.62×51mm
13   Interceptor                                     Beretta m9 9mm

#### Generate a dataFrame from database by using database Views after selecting the columns customer_name, order_name, amount

In [33]:
db_view_name = "customer_orders_view"
database_view_table = ReadDBViewModel(database_view_name=db_view_name, engine=engine_obj,columns=["customer_name","order_name","amount"])
database_view_df = read_db_table_db_view_support(database_view_table)
database_view_df

   customer_name                                         order_name     amount
0         Rollex   50 calibure fully automatic Browning machine gun  $9,978.12
1      Ballistic                   50 calibure desert eagle handgun  $1,000.12
2      Barricade                                 500 S and W Magnum  $2,470.12
3         Bullet              Anzio 20mm anti material sniper rifle  $7,620.12
4       Barbatos                                     Beretta m9 9mm  $1,170.12
5      Artillery        Milkor MGL (40mm Multiple Grenade Launcher)  $1,500.12
6        Shotgun          Benelli M4 (M1014) 12 gauge shotgun shell  $1,850.12
7         Kombat                                              AK-47  $3,650.12
8       Lockdown                     M249 SAW Mk 48 Mod 1 7.62×51mm  $3,650.12
9       Ignition                            Javelin rocket launcher  $6,000.12
10     Shockwave        Milkor MGL (40mm Multiple Grenade Launcher)  $3,600.12
11    PointBreak  FN SCAR-H (Special Operations Forces Combat As...  $7,470.12
12    GroundZero                     M249 SAW Mk 48 Mod 1 7.62×51mm  $8,000.12
13   Interceptor                                     Beretta m9 9mm  $9,110.12

## Now I am going to attempt to wirte the data from a csv file into the database

In [34]:
csv_orders_df=pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/read_orders_table_read_db_df.csv")
csv_orders_df

,id,customer_id,name,amount,order_date
0,1,1,Axe,"$9,978.12",2025-09-01 12:01:26.625465
1,2,2,Sledge Hammer,"$1,000.12",2025-09-01 12:01:26.625465
2,3,3,Showel,"$2,470.12",2025-09-01 12:01:26.625465
3,4,4,Cross blade Axe,"$7,620.12",2025-09-01 12:01:26.625465
4,5,5,Pick Axe,"$1,170.12",2025-09-01 12:01:26.625465
5,6,6,Michetti,"$1,500.12",2025-09-01 12:01:26.625465
6,7,7,Crow-bar,"$1,850.12",2025-09-01 12:01:26.625465
7,8,8,Titanium base ball bat,"$3,650.12",2025-09-01 12:01:26.625465
8,9,9,Mace,"$3,650.12",2025-09-01 12:01:26.625465
9,10,10,Gurkha dagger,"$6,000.12",2025-09-01 12:01:26.625465
10,11,11,Throwing knife,"$3,600.12",2025-09-01 12:01:26.625465
11,12,12,Tawma Hawk Axe,"$7,470.12",2025-09-01 12:01:26.625465
12,13,13,ice Axe,"$8,000.12",2025-09-01 12:01:26.625465
13,14,14,Military knife,"$9,110.12",2025-09-01 12:01:26.625465

### In a same way that I had previously created a function for reading the database In the same way I want to write a function to write the data into the database after reading the data from a csv file

In [35]:
class WritePandasToDBModel(BaseModel):
    df:pd.DataFrame=Field(default=None)
    table_name:str=Field(default=None)
    index:bool=Field(default=False)
    if_exists:str=Field(default=False)
    engine:Engine
    model_config={
        "arbitrary_types_allowed":True
    }
def write_df_to_database(config:WritePandasToDBModel):
    if config.df is None or config.df.empty:
        raise ValueError("DataFrame is required and cannot be empty to write into the database")
    if not table_name:
        raise ValueError("Table name is required to be able to write the data into the database.")
    if config.table_name:
        try:
            # remove the id (primary key column) if exists
            if "id" in config.df.columns:
                config.df = config.df.drop(columns=["id"])\
            
            if config.if_exists:
                config.df.to_sql(name=config.table_name,con=config.engine,index=config.index,if_exists=config.if_exists)
            elif config.if_exists:
                config.df.to_sql(name=config.table_name,con=config.engine,index=config.index,if_exists=config.if_exists)
            else:
                config.df.to_sql(name=config.table_name,con=config.engine,index=config.index)
        except Exception as e:
            raise RuntimeError(f"Failed to read table '{config.table_name}':{e}")

In [36]:
table_name = "orders"
engine=engine_obj
if_exists="append"
index=False
write_to_db = WritePandasToDBModel(df=csv_orders_df,table_name=table_name,engine=engine,if_exists=if_exists,index=index)
write_df_to_database =write_df_to_database(write_to_db)

#### To verify if it worked or not I am going to create another dataFrame using the orders table from the database

In [37]:
db_view_name = "orders"
database_view_table = ReadDBViewModel(database_view_name=db_view_name, engine=engine_obj)
database_view_df = read_db_table_db_view_support(database_view_table)
database_view_df

,id,customer_id,name,amount,order_date
0,1,1,50 calibure fully automatic Browning machine gun,"$9,978.12",2025-09-02 16:30:33.322422
1,2,2,50 calibure desert eagle handgun,"$1,000.12",2025-09-02 16:30:33.322422
2,3,3,500 S and W Magnum,"$2,470.12",2025-09-02 16:30:33.322422
3,4,4,Anzio 20mm anti material sniper rifle,"$7,620.12",2025-09-02 16:30:33.322422
4,5,5,Beretta m9 9mm,"$1,170.12",2025-09-02 16:30:33.322422
5,6,6,Milkor MGL (40mm Multiple Grenade Launcher),"$1,500.12",2025-09-02 16:30:33.322422
6,7,7,Benelli M4 (M1014) 12 gauge shotgun shell,"$1,850.12",2025-09-02 16:30:33.322422
7,8,8,AK-47,"$3,650.12",2025-09-02 16:30:33.322422
8,9,9,M249 SAW Mk 48 Mod 1 7.62×51mm,"$3,650.12",2025-09-02 16:30:33.322422
9,10,10,Javelin rocket launcher,"$6,000.12",2025-09-02 16:30:33.322422
10,11,11,Milkor MGL (40mm Multiple Grenade Launcher),"$3,600.12",2025-09-02 16:30:33.322422
11,12,12,FN SCAR-H (Special Operations Forces Combat As...,"$7,470.12",2025-09-02 16:30:33.322422
12,13,13,M249 SAW Mk 48 Mod 1 7.62×51mm,"$8,000.12",2025-09-02 16:30:33.322422
13,14,14,Beretta m9 9mm,"$9,110.12",2025-09-02 16:30:33.322422
14,15,1,Axe,"$9,978.12",2025-09-01 12:01:26.625465
15,16,2,Sledge Hammer,"$1,000.12",2025-09-01 12:01:26.625465
16,17,3,Showel,"$2,470.12",2025-09-01 12:01:26.625465
17,18,4,Cross blade Axe,"$7,620.12",2025-09-01 12:01:26.625465
18,19,5,Pick Axe,"$1,170.12",2025-09-01 12:01:26.625465
19,20,6,Michetti,"$1,500.12",2025-09-01 12:01:26.625465
20,21,7,Crow-bar,"$1,850.12",2025-09-01 12:01:26.625465
21,22,8,Titanium base ball bat,"$3,650.12",2025-09-01 12:01:26.625465
22,23,9,Mace,"$3,650.12",2025-09-01 12:01:26.625465
23,24,10,Gurkha dagger,"$6,000.12",2025-09-01 12:01:26.625465
24,25,11,Throwing knife,"$3,600.12",2025-09-01 12:01:26.625465
25,26,12,Tawma Hawk Axe,"$7,470.12",2025-09-01 12:01:26.625465
26,27,13,ice Axe,"$8,000.12",2025-09-01 12:01:26.625465
27,28,14,Military knife,"$9,110.12",2025-09-01 12:01:26.625465

#### As you can see that the data in the database has been updated now there exists new rows of data

# TODO Make sure to drop the tables in the database before working on this notebook