# Melt function in Pandas
Melt function just like ```pivot``` function is used to reshape the dataFrame

In [1]:
import pandas as pd
import numpy as np
import itertools
from matplotlib import pyplot as plt
from Typing import List, Optional

weather_df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/weather_data_melt_func_demo.csv")
weather_df

         day  chicago  chennai  berlin  tokyo  sydney
0     Monday       32       75      41     55      65
1    Tuesday       30       77      43     58      68
2  Wednesday       28       75      45     53      64
3   Thursday       22       82      38     50      63
4     Friday       30       83      30     56      66
5   Saturday       20       81      45     54      67
6     Sunday       25       77      47     52      65

In [2]:
melted_df = pd.melt(weather_df,id_vars=["day"])
melted_df

          day variable  value
0      Monday  chicago     32
1     Tuesday  chicago     30
2   Wednesday  chicago     28
3    Thursday  chicago     22
4      Friday  chicago     30
5    Saturday  chicago     20
6      Sunday  chicago     25
7      Monday  chennai     75
8     Tuesday  chennai     77
9   Wednesday  chennai     75
10   Thursday  chennai     82
11     Friday  chennai     83
12   Saturday  chennai     81
13     Sunday  chennai     77
14     Monday   berlin     41
15    Tuesday   berlin     43
16  Wednesday   berlin     45
17   Thursday   berlin     38
18     Friday   berlin     30
19   Saturday   berlin     45
20     Sunday   berlin     47
21     Monday    tokyo     55
22    Tuesday    tokyo     58
23  Wednesday    tokyo     53
24   Thursday    tokyo     50
25     Friday    tokyo     56
26   Saturday    tokyo     54
27     Sunday    tokyo     52
28     Monday   sydney     65
29    Tuesday   sydney     68
30  Wednesday   sydney     64
31   Thursday   sydney     63
32     Friday   sydney     66
33   Saturday   sydney     67
34     Sunday   sydney     65

### Huh? ... Interesting what do we have here 
### Let's use pivot on this ```melted_df``` and see if my gut feeling right

In [4]:
pivoted_df = melted_df.pivot(index="day",columns="variable",values="value")
pivoted_df

variable   berlin  chennai  chicago  sydney  tokyo
day
Friday         30       83       30      66     56
Monday         41       75       32      65     55
Saturday       45       81       20      67     54
Sunday         47       77       25      65     52
Thursday       38       82       22      63     50
Tuesday        43       77       30      68     58
Wednesday      45       75       28      64     53

### I knew it! ```pd.melt()``` function is nothing but opposite to ```df.pivot()``` function. 
### Theory:
- ```pd.melt()``` this function reshapes a DataFrame by converting columns into rows.
- Wide format -> many columns for variable
- Long format -> fewer columns, but more rows (tidy)
#### What is ```pd.melt()```:
- Your columns represent variable names (like years, months, metrics) instead of values.
- You want to prepare data for plotting (most plotting libraries prefer long format).
- You want to normalize messy spreadsheets into a standard structure.
#### When not to use ```pd.melt()```:
- Your data is already in long/tidy format.
- You want a pivoted summary (example, aggregating sales per product).
- You need aggregations/grouping -> use ```pivot_table``` instead
### Analysis
```pd.melt()``` function is also used to rehape the dataFrame just like the ```pivot``` function.
- First argument taken by this function is the dataFrame.
- Second argument taken by this function is ```id_vars[]```. The id variables is basically the thing that you want in your x axis in other words you pass in the columns that you want to keep intact after the rehaping of the dataFrame is complete.

#### How to set variable name and value name in melt function

In [6]:
melt_df = pd.melt(weather_df,id_vars=["day"],var_name="city",value_name="temperature")
melt_df

          day     city  temperature
0      Monday  chicago           32
1     Tuesday  chicago           30
2   Wednesday  chicago           28
3    Thursday  chicago           22
4      Friday  chicago           30
5    Saturday  chicago           20
6      Sunday  chicago           25
7      Monday  chennai           75
8     Tuesday  chennai           77
9   Wednesday  chennai           75
10   Thursday  chennai           82
11     Friday  chennai           83
12   Saturday  chennai           81
13     Sunday  chennai           77
14     Monday   berlin           41
15    Tuesday   berlin           43
16  Wednesday   berlin           45
17   Thursday   berlin           38
18     Friday   berlin           30
19   Saturday   berlin           45
20     Sunday   berlin           47
21     Monday    tokyo           55
22    Tuesday    tokyo           58
23  Wednesday    tokyo           53
24   Thursday    tokyo           50
25     Friday    tokyo           56
26   Saturday    tokyo           54
27     Sunday    tokyo           52
28     Monday   sydney           65
29    Tuesday   sydney           68
30  Wednesday   sydney           64
31   Thursday   sydney           63
32     Friday   sydney           66
33   Saturday   sydney           67
34     Sunday   sydney           65

## Exmaple 1: Sales by year

### Generate data

In [ ]:
def generate_sales_data(products:List[str]=None, 
                        start_year:int=None, 
                        end_year:int=None, 
                        seed:int=None)->pd.DataFrame:
    # check the type of each arguments that is passed into this function
    if not isinstance(products,list):
        raise TypeError("products must be of type list")
    if not isinstance()
    
    np.random.seed(seed)  # for reproducibility
    
    # Years as columns
    years = list(map(str, range(start_year, end_year + 1)))
    
    # Random sales data between 100 and 5000
    data = {year: np.random.randint(100, 5000, size=len(products)) for year in years}
    
    # Build DataFrame
    df = pd.DataFrame(data)
    df.insert(0, "product", products)  # insert product column at start
    
    return df

In [ ]:
start_year=2004
end_year=2025
seed=42