# Pivot in pandas

## Import libraries

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

## what is pivot?
In Pandas, ```.pivot()``` function is used to reshape your DataFrame by turning unique values from one column into new columns, while reorganizing the data around an index. <br>
syntax : ```DataFrame.pivot(index=None, columns=None, values=None)``` <br>
**Parameters** : <br>
- index : column(s) to use as row labels
- columns : column whose unique values will become new columns
- values : column whose values will fill new table (cells)'
## Let's look at an example:

In [4]:
#generate a sample data for pivot demonstration
data = {
    "city": ["mumbai", "mumbai", "delhi", "delhi", "lucknow", "lucknow"],
    "date": ["2025-08-01", "2025-08-02", "2025-08-01", "2025-08-02", "2025-08-01", "2025-08-02"],
    "temperature": [30, 32, 40, 42, 35, 37]
}

In [5]:
df_pivot = pd.DataFrame(data)
df_pivot

      city        date  temperature
0   mumbai  2025-08-01           30
1   mumbai  2025-08-02           32
2    delhi  2025-08-01           40
3    delhi  2025-08-02           42
4  lucknow  2025-08-01           35
5  lucknow  2025-08-02           37

In [7]:
pivoted_df = df_pivot.pivot(index="date",columns="city",values="temperature")
pivoted_df

city        delhi  lucknow  mumbai
date
2025-08-01     40       35      30
2025-08-02     42       37      32

### Explaination:
- ```date``` became the index (rows)
- ```city``` values (```mumbai```, ```delhi```, ```lucknow```) became new columns.
- ```temperature``` values filled the table.
<br>
So instead of having a long format data (row-wise) now we have a wide format table where each city's temperature is in its own column.

### Limitations of ```pivot```
1. It doen't allow duplicates for the combination of ```index``` + ```columns```
   - If you have duplicates, Pandas will throw an error.
   - Exmple : If ```mumbai``` city has two temperature recorded on the same date then ```pivot``` won't know which one to use.
   - In that case, you should use ```pivot_table()``` instead, because it allows aggregation (mean,sum,etc...)
2. Works best with clean and tidy data where one combination of index and column is unique.