# Crosstab in pandas
```.crosstab()``` function allows you to compute a frequency table of two or more variables, which summarizes the distribution of values in the data and provides insightes into the relationships between the variables. It is a type of table in a matrix format that displays the multivariate frequency distribution of variables. They are heavily used in survey research, business, intelligence, engineering and scientific research. <br>
A variable having two categories is called binary variable. When both variables are binary, the resulting contingency table is a 2 X 2 table. Also, commonly known as a four-fold table because there are four cells. <br>
**Each cell in the table tells you how many items fall into both categories at the same time.**

<br>

| Alcohol consumption | Smoke: Yes | Smoke: No | Total |
| ------------------- | ---------- | --------- | ----- |
| Low                 | 10         | 80        | 90    |
| High                | 50         | 40        | 90    |
| Total               | 60         | 120       | 180   |


<br>

A contingency table can summarize three probability distributions - Joint, marginal and conditional.
- The joint distribution describes the proportion of the subjects jointly classified by a category of X and a category of Y. The cells of the contingency table divided by the total provides the joint distribution. The sum of the joint distribution is 1.
- The marginal distributions describes the distribution of the X (row) or Y (column) variable alone. The row column totals of the contingency table divided by the total provides the joint distribution. The sum of the joint distribution is 1.
- The conditional distributions describe the distribution of one variable given the levels of the other variable. The cells of the contingency table divided by the row or column totals provide the conditional distributions. The sum of a conditional distribution is 1.

<br>

**Interpretation:**
- 10 people drink little alcohol and smoke.
- 80 people drink little alcohol and don’t smoke.
- 50 people drink a lot and smoke.
- 40 people drink a lot and don’t smoke.

<br>

So the table summarizes the joint distribution of the two variables. <br>

If you want to quickly see the pattern (e.g., “Do heavy drinkers smoke more often?”), scanning row by row is painful.
A contingency table condenses raw data into a simple grid so patterns & relationships are visible. <br>

**When is it used?**
- Exploratory Data Analysis (EDA): When you’re trying to understand relationships between two categorical variables.
  e.g. Do smokers tend to drink more? Do males/females prefer different products?
- Feature Engineering in ML:
  - Sometimes categorical relationships matter when building models (like Naive Bayes, Decision Trees).
  - ontingency tables help you understand which categories are related.
- Hypothesis Testing (Chi-square test):
  - Used to check if two variables are independent or related.
  - Example: Is smoking related to alcohol consumption?
- Business/Health decisions:
  - Hospitals: Does a treatment’s success depend on gender?
  - E-commerce: Are product preferences related to age group?

In [2]:
import pandas as pd
import numpy as np
import itertools

df = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/survey_cross_tab.xls")
df

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima   Bangadesh  Female   31       Left
5    Kadir   Bangadesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

## Create a contingency table using ```.crosstab()``` function

### Create a contingency table between Nationality vs Handedness

In [8]:
pd.crosstab(df["Nationality"], df["Handedness"])

Handedness   Left  Right
Nationality
Bangadesh       2      0
China           2      1
India           2      1
USA             1      3

### Created contingency table between Sex vs Handedness

In [10]:
pd.crosstab(df["Sex"],df["Handedness"])

Handedness  Left  Right
Sex
Female         2      3
Male           5      2

### Create a contingency table between Nationality vs Age

In [12]:
pd.crosstab(df["Nationality"],df["Age"])

Age          18  19  22  23  25  31  35  37  43  52  58
Nationality
Bangadesh     0   0   0   0   1   1   0   0   0   0   0
China         0   0   0   0   0   0   0   0   1   1   1
India         0   0   0   0   0   1   1   1   0   0   0
USA           1   1   1   1   0   0   0   0   0   0   0

### Create a crosstab between NAtionality vs Sex

In [14]:
pd.crosstab(df["Nationality"],df["Sex"])

Sex          Female  Male
Nationality
Bangadesh         1     1
China             2     1
India             0     3
USA               2     2