# Crosstab in pandas
```.crosstab()``` function allows you to compute a frequency table of two or more variables, which summarizes the distribution of values in the data and provides insightes into the relationships between the variables. It is a type of table in a matrix format that displays the multivariate frequency distribution of variables. They are heavily used in survey research, business, intelligence, engineering and scientific research. <br>
A variable having two categories is called binary variable. When both variables are binary, the resulting contingency table is a 2 X 2 table. Also, commonly known as a four-fold table because there are four cells. <br>
**Each cell in the table tells you how many items fall into both categories at the same time.**

<br>

| Alcohol consumption | Smoke: Yes | Smoke: No | Total |
| ------------------- | ---------- | --------- | ----- |
| Low                 | 10         | 80        | 90    |
| High                | 50         | 40        | 90    |
| Total               | 60         | 120       | 180   |


<br>

A contingency table can summarize three probability distributions - Joint, marginal and conditional.
- The joint distribution describes the proportion of the subjects jointly classified by a category of X and a category of Y. The cells of the contingency table divided by the total provides the joint distribution. The sum of the joint distribution is 1.
- The marginal distributions describes the distribution of the X (row) or Y (column) variable alone. The row column totals of the contingency table divided by the total provides the joint distribution. The sum of the joint distribution is 1.
- The conditional distributions describe the distribution of one variable given the levels of the other variable. The cells of the contingency table divided by the row or column totals provide the conditional distributions. The sum of a conditional distribution is 1.

<br>

**Interpretation:**
- 10 people drink little alcohol and smoke.
- 80 people drink little alcohol and don’t smoke.
- 50 people drink a lot and smoke.
- 40 people drink a lot and don’t smoke.

<br>

So the table summarizes the joint distribution of the two variables. <br>

If you want to quickly see the pattern (e.g., “Do heavy drinkers smoke more often?”), scanning row by row is painful.
A contingency table condenses raw data into a simple grid so patterns & relationships are visible. <br>

**When is it used?**
- Exploratory Data Analysis (EDA): When you’re trying to understand relationships between two categorical variables.
  e.g. Do smokers tend to drink more? Do males/females prefer different products?
- Feature Engineering in ML:
  - Sometimes categorical relationships matter when building models (like Naive Bayes, Decision Trees).
  - ontingency tables help you understand which categories are related.
- Hypothesis Testing (Chi-square test):
  - Used to check if two variables are independent or related.
  - Example: Is smoking related to alcohol consumption?
- Business/Health decisions:
  - Hospitals: Does a treatment’s success depend on gender?
  - E-commerce: Are product preferences related to age group?

In [45]:
import pandas as pd
import numpy as np
import itertools

df = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/survey_cross_tab.xls")
df

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima   Bangadesh  Female   31       Left
5    Kadir   Bangadesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

## Create a contingency table using ```.crosstab()``` function

### Create a contingency table between Nationality vs Handedness

In [46]:
pd.crosstab(df["Nationality"], df["Handedness"])

Handedness   Left  Right
Nationality
Bangadesh       2      0
China           2      1
India           2      1
USA             1      3

### Created contingency table between Sex vs Handedness

In [47]:
pd.crosstab(df["Sex"],df["Handedness"])

Handedness  Left  Right
Sex
Female         2      3
Male           5      2

### Create a contingency table between Nationality vs Age

In [48]:
pd.crosstab(df["Nationality"],df["Age"])

Age          18  19  22  23  25  31  35  37  43  52  58
Nationality
Bangadesh     0   0   0   0   1   1   0   0   0   0   0
China         0   0   0   0   0   0   0   0   1   1   1
India         0   0   0   0   0   1   1   1   0   0   0
USA           1   1   1   1   0   0   0   0   0   0   0

### Create a contingency table between Nationality vs Sex

In [49]:
pd.crosstab(df["Nationality"],df["Sex"])

Sex          Female  Male
Nationality
Bangadesh         1     1
China             2     1
India             0     3
USA               2     2

### Use ```margins``` and set it to ```True``` if you want to show the total in the contingency table 
When you set ```margins=True``` then adding totals (sum rows and columns) are also shown in the contigency table.
#### Why use margins?
- To quicky see totals across rows/columns.
- Good for summary reporting (like in Excel pivot tables).
- Useful in EDA when you want both detailed counts + overall totals.
#### When not to use it?
- If you only care about relationships and not totals.
- If you are normalizing percentages (```normalize```) -> margins can be confusing because totals also get normalized.
#### Options for ```margins```
- ```margins=False``` (default) -> no totals.
- ```margins=True``` -> adds an "All" row and columns. where total is shown row and columnwise
- ```margins_name=CustomName``` -> change the label of the total row/col.

#### Create a contigency table between Nationality vs Handedness also show total

In [50]:
pd.crosstab(df["Nationality"],df["Handedness"],margins=True)

Handedness   Left  Right  All
Nationality
Bangadesh       2      0    2
China           2      1    3
India           2      1    3
USA             1      3    4
All             7      5   12

#### Create a contingency table between Nationality vs Sex also show total

In [51]:
pd.crosstab(df["Nationality"],df["Sex"],margins=True)

Sex          Female  Male  All
Nationality
Bangadesh         1     1    2
China             2     1    3
India             0     3    3
USA               2     2    4
All               5     7   12

#### Create a contigency table between Nationality vs Age also show total

In [52]:
pd.crosstab(df["Nationality"],df["Age"],margins=True)

Age          18  19  22  23  25  31  35  37  43  52  58  All
Nationality
Bangadesh     0   0   0   0   1   1   0   0   0   0   0    2
China         0   0   0   0   0   0   0   0   1   1   1    3
India         0   0   0   0   0   1   1   1   0   0   0    3
USA           1   1   1   1   0   0   0   0   0   0   0    4
All           1   1   1   1   1   2   1   1   1   1   1   12

#### Create a contigency table between Sex vs Handedness also show total

In [68]:
pd.crosstab(df["Sex"],df["Handedness"],margins=True,margins_name="Total")

Handedness  Left  Right  Total
Sex
Female         2      3      5
Male           5      2      7
Total          7      5     12

### Passing multiple variables at the column level when generating a contigency table using the ```.crosstab()``` function.

#### Nationality vs [Sex,Handedness] contigency table

In [69]:
pd.crosstab(df["Nationality"],[df["Sex"],df["Handedness"]],margins=True,margins_name="Total")

Sex         Female       Male       Total
Handedness    Left Right Left Right
Nationality
Bangadesh        1     0    1     0     2
China            1     1    1     0     3
India            0     0    2     1     3
USA              0     2    1     1     4
Total            2     3    5     2    12

#### Nationality vs [Age,Handedness] contigency table

In [62]:
pd.crosstab(df["Nationality"],[df["Age"],df["Handedness"]],margins=True)

Age            18    19   22    23   25   31   35    37   43    52   58 All
Handedness  Right Right Left Right Left Left Left Right Left Right Left
Nationality
Bangadesh       0     0    0     0    1    1    0     0    0     0    0   2
China           0     0    0     0    0    0    0     0    1     1    1   3
India           0     0    0     0    0    1    1     1    0     0    0   3
USA             1     1    1     1    0    0    0     0    0     0    0   4
All             1     1    1     1    1    2    1     1    1     1    1  12

### Use ```normalize="index"``` to calculate and show percentage in the generated contigency table in Pandas
By default ```pd.crosstab``` function shows the counts. ```normalize``` lets you see proportions (fractions/percentages) instead.
#### Why use ```normalize```?
- To compare **proportions** instead of raw counts.
- Useful when groups are uneven in size (example, if you have 10000 males but only 50 females, raw counts mislead, but percentages make sense)
- Crucial in ML feature exploration -> helps check if categories are biased toward certain outcomes.
#### When not to use it?
- When absolute counts are important (example: "How many customers bought product X?")
- In very small datasets (percentages can exaggerate differences).
#### Options for ```normalize```
- ```normalize=False``` (default) raw counts
- ```normalize=True``` normalize over the whole table (fractions of grand total)
- ```normalize="all"``` same as when ```normalize``` was set to ```True```
- ```normalize="index"``` normalize row-wise (each row sums to 1)
- ```normalize="columns"``` normalize column-wise (each column sums to 1)

#### Generate a contingency table between Nationality vs Handedness, calculate the percentage and show it in the generate dataFrame.

In [64]:
pd.crosstab(df["Nationality"],df["Handedness"],margins=False,normalize="index")

Handedness       Left     Right
Nationality
Bangadesh    1.000000  0.000000
China        0.666667  0.333333
India        0.666667  0.333333
USA          0.250000  0.750000

#### Generate a contingency table between Nationality vs Sex, calculate the percentage and show it in the generate dataFrame.

In [65]:
pd.crosstab(df["Nationality"],df["Sex"],margins=False,normalize="index")

Sex            Female      Male
Nationality
Bangadesh    0.500000  0.500000
China        0.666667  0.333333
India        0.000000  1.000000
USA          0.500000  0.500000

#### Generate a contingency table between Sex vs Handedness, calculate the percentage and show it in the generate dataFrame

In [66]:
pd.crosstab(df["Sex"],df["Handedness"],margins=False,normalize="index")

Handedness      Left     Right
Sex
Female      0.400000  0.600000
Male        0.714286  0.285714

## NOTICE : In AI/ML context
- **Margin:** helps you understand dataset balance (example: total positives vs negatives).
- **Normalize:** helps you see probabilities -> essential in ML when checking for class imbalance for feature distribution.