# Stacking and Unstacking in pandas

In [33]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import itertools
import seaborn

df = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/stocks_to_demo_stacking.xlsx",header=[0,1])
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

## Stacking

Let's say you want to analyze a stock market data, where you have two level of column headers.
- The first level is the metric that you are analyzing ```[price and (P/E)]```
- The second level is the company itself.

<br>

Now there is a way to make the second level header of the dataFrame in this case ```company``` can be transposed and make it a row using ```.stack()``` function. <br>
Similarly you can also make the first level header of the dataFrame in this case ```metrics``` can be transposed and make it a row using ```.stack()``` function. <br>
To stack the innermost level of column headers use ```.stack()``` method on the dataFrame.

In [34]:
df.stack()

/tmp/ipykernel_19420/3977694045.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack()

            Unnamed: 0_level_0   Price  Price to earnings ratio (P/E)
0 Company           2017-06-05     NaN                            NaN
  Facebook                 NaT   155.0                          37.10
  Google                   NaT   955.0                          32.00
  Microsoft                NaT    66.0                          30.31
1 Company           2017-06-06     NaN                            NaN
  Facebook                 NaT   150.0                          36.98
  Google                   NaT   987.0                          31.30
  Microsoft                NaT    69.0                          30.56
2 Company           2017-06-07     NaN                            NaN
  Facebook                 NaT   153.0                          36.78
  Google                   NaT   963.0                          31.70
  Microsoft                NaT    62.0                          30.46
3 Company           2017-06-08     NaN                            NaN
  Facebook                 NaT   155.0                          36.11
  Google                   NaT  1000.0                          31.20
  Microsoft                NaT    61.0                          30.11
4 Company           2017-06-09     NaN                            NaN
  Facebook                 NaT   156.0                          37.07
  Google                   NaT  1012.0                          30.00
  Microsoft                NaT    66.0                          31.00

### Analysis: 
```
/tmp/ipykernel_19420/3977694045.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack()
```
### What does this warning mean? <br>
- Pandas is warning you that the current implementation of .stack() will change (or be removed) in a future version.
- They’ve introduced a new implementation of .stack(), and you can start using it today by adding future_stack=True.

In [35]:
df_stacked_level_1 = df.stack(future_stack=True)
df_stacked_level_1

            Unnamed: 0_level_0   Price  Price to earnings ratio (P/E)
0 Company           2017-06-05     NaN                            NaN
  Facebook                 NaT   155.0                          37.10
  Google                   NaT   955.0                          32.00
  Microsoft                NaT    66.0                          30.31
1 Company           2017-06-06     NaN                            NaN
  Facebook                 NaT   150.0                          36.98
  Google                   NaT   987.0                          31.30
  Microsoft                NaT    69.0                          30.56
2 Company           2017-06-07     NaN                            NaN
  Facebook                 NaT   153.0                          36.78
  Google                   NaT   963.0                          31.70
  Microsoft                NaT    62.0                          30.46
3 Company           2017-06-08     NaN                            NaN
  Facebook                 NaT   155.0                          36.11
  Google                   NaT  1000.0                          31.20
  Microsoft                NaT    61.0                          30.11
4 Company           2017-06-09     NaN                            NaN
  Facebook                 NaT   156.0                          37.07
  Google                   NaT  1012.0                          30.00
  Microsoft                NaT    66.0                          31.00

If you want to stack the first level of column headers instead then all you need to do is this ```.stack(level=0)```<br>
There is another argument in this function ```.stack()``` and that is ```dropna``` where it can be used to drop all the NaN values from the dataFrame if required when transposing the header in the dataFrame.

In [36]:
df_stacked_level_zero = df.stack(level=0,future_stack=True)
df_stacked_level_zero

                                   Company  Facebook  Google  Microsoft
0 Unnamed: 0_level_0            2017-06-05       NaN     NaN        NaN
  Price                                NaT    155.00   955.0      66.00
  Price to earnings ratio (P/E)        NaT     37.10    32.0      30.31
1 Unnamed: 0_level_0            2017-06-06       NaN     NaN        NaN
  Price                                NaT    150.00   987.0      69.00
  Price to earnings ratio (P/E)        NaT     36.98    31.3      30.56
2 Unnamed: 0_level_0            2017-06-07       NaN     NaN        NaN
  Price                                NaT    153.00   963.0      62.00
  Price to earnings ratio (P/E)        NaT     36.78    31.7      30.46
3 Unnamed: 0_level_0            2017-06-08       NaN     NaN        NaN
  Price                                NaT    155.00  1000.0      61.00
  Price to earnings ratio (P/E)        NaT     36.11    31.2      30.11
4 Unnamed: 0_level_0            2017-06-09       NaN     NaN        NaN
  Price                                NaT    156.00  1012.0      66.00
  Price to earnings ratio (P/E)        NaT     37.07    30.0      31.00

## Unstacking

We can use unstack to perform reverse transformation and restore the dataFrame into it's original form.

### Unstack dataFrame where level=1 header was tranposed i.e the ```company``` header was transposed from columns to rows.
Restore dataFrame to it's original form.

In [67]:
df_stacked_level_1.unstack()

  Unnamed: 0_level_0                             Price                   \
             Company Facebook Google Microsoft Company Facebook  Google
0         2017-06-05      NaT    NaT       NaT     NaN    155.0   955.0
1         2017-06-06      NaT    NaT       NaT     NaN    150.0   987.0
2         2017-06-07      NaT    NaT       NaT     NaN    153.0   963.0
3         2017-06-08      NaT    NaT       NaT     NaN    155.0  1000.0
4         2017-06-09      NaT    NaT       NaT     NaN    156.0  1012.0

            Price to earnings ratio (P/E)
  Microsoft                       Company Facebook Google Microsoft
0      66.0                           NaN    37.10   32.0     30.31
1      69.0                           NaN    36.98   31.3     30.56
2      62.0                           NaN    36.78   31.7     30.46
3      61.0                           NaN    36.11   31.2     30.11
4      66.0                           NaN    37.07   30.0     31.00

#### Original dataFrame looks something like this.

In [66]:
df = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/stocks_to_demo_stacking.xlsx",header=[0,1])
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

#### Analysis:
As you can see that the dataFrame that we got is not the same as what the original dataFrame actually is

#### Let's try to drop the multi-level column headers called ```Unnamed: 0_level_0	```

In [84]:
restored = df_stacked_level_1.unstack()
droped_restored_df=restored.drop(columns="Unnamed: 0_level_0",level=0)
droped_restored_df

    Price                            Price to earnings ratio (P/E)           \
  Company Facebook  Google Microsoft                       Company Facebook
0     NaN    155.0   955.0      66.0                           NaN    37.10
1     NaN    150.0   987.0      69.0                           NaN    36.98
2     NaN    153.0   963.0      62.0                           NaN    36.78
3     NaN    155.0  1000.0      61.0                           NaN    36.11
4     NaN    156.0  1012.0      66.0                           NaN    37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

#### Huh? It seems that the Company column that had dates in it was under the ```Unnamed: 0_level_0``` header I need to some how switch places with the company that has dates and the company that has NaN values in them in the dataFrame.

#### Ok so instead of trying to drop ```Unnamed: 0_level_0```, let's try to drop the columns that have NaT and NaN values in it.

In [85]:
restored = restored.dropna(axis=1, how="all")
restored

  Unnamed: 0_level_0    Price                   Price to earnings ratio (P/E)  \
             Company Facebook  Google Microsoft                      Facebook
0         2017-06-05    155.0   955.0      66.0                         37.10
1         2017-06-06    150.0   987.0      69.0                         36.98
2         2017-06-07    153.0   963.0      62.0                         36.78
3         2017-06-08    155.0  1000.0      61.0                         36.11
4         2017-06-09    156.0  1012.0      66.0                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

#### Now this dataFrame looks like how the original dataFrame looks like

### Unstack dataFrame where level=0 header was tranposed i.e the ```metrics (price and P/E)``` header was transposed from columns to rows.
Restore dataFrame to it's original form.

In [97]:
df_restored = df_stacked_level_zero.unstack(level=1)
df_restored

             Company                                               Facebook  \
  Unnamed: 0_level_0 Price Price to earnings ratio (P/E) Unnamed: 0_level_0
0         2017-06-05   NaT                           NaT                NaN
1         2017-06-06   NaT                           NaT                NaN
2         2017-06-07   NaT                           NaT                NaN
3         2017-06-08   NaT                           NaT                NaN
4         2017-06-09   NaT                           NaT                NaN

                                                   Google          \
   Price Price to earnings ratio (P/E) Unnamed: 0_level_0   Price
0  155.0                         37.10                NaN   955.0
1  150.0                         36.98                NaN   987.0
2  153.0                         36.78                NaN   963.0
3  155.0                         36.11                NaN  1000.0
4  156.0                         37.07                NaN  1012.0

                                         Microsoft        \
  Price to earnings ratio (P/E) Unnamed: 0_level_0 Price
0                          32.0                NaN  66.0
1                          31.3                NaN  69.0
2                          31.7                NaN  62.0
3                          31.2                NaN  61.0
4                          30.0                NaN  66.0


  Price to earnings ratio (P/E)
0                         30.31
1                         30.56
2                         30.46
3                         30.11
4                         31.00

#### Drop the columns that have ```NaT``` or ```NaN``` values in them.

In [90]:
dropped_restored_df = df_restored.dropna(axis=1,how="all")
dropped_restored_df

             Company Facebook                                Google  \
  Unnamed: 0_level_0    Price Price to earnings ratio (P/E)   Price
0         2017-06-05    155.0                         37.10   955.0
1         2017-06-06    150.0                         36.98   987.0
2         2017-06-07    153.0                         36.78   963.0
3         2017-06-08    155.0                         36.11  1000.0
4         2017-06-09    156.0                         37.07  1012.0

                                Microsoft
  Price to earnings ratio (P/E)     Price Price to earnings ratio (P/E)
0                          32.0      66.0                         30.31
1                          31.3      69.0                         30.56
2                          31.7      62.0                         30.46
3                          31.2      61.0                         30.11
4                          30.0      66.0                         31.00

#### swap the multi-level header move the ```company``` header to level 1 and ```matrics``` to level 0

In [92]:
dropped_restored_df.columns = dropped_restored_df.columns.swaplevel(0,1)
dropped_restored_df

,Unnamed: 0_level_0,Price,Price to earnings ratio (P/E),Price,Price to earnings ratio (P/E),Price,Price to earnings ratio (P/E)
,Company,Facebook,Facebook,Google,Google,Microsoft,Microsoft
0,2017-06-05,155.0,37.10,955.0,32.0,66.0,30.31
1,2017-06-06,150.0,36.98,987.0,31.3,69.0,30.56
2,2017-06-07,153.0,36.78,963.0,31.7,62.0,30.46
3,2017-06-08,155.0,36.11,1000.0,31.2,61.0,30.11
4,2017-06-09,156.0,37.07,1012.0,30.0,66.0,31.00

#### Original dataFrame

In [94]:
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

In [95]:
df_melted = dropped_restored_df.melt(
    id_vars=['Unnamed: 0_level_0'],
    var_name='Company',
    value_name='Value',
    col_level=1
)
df_melted

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Unnamed: 0_level_0']"