# Introduction to Big data and Hadoop
## Business Data Processing Beginning and Evolution
- **COBOL** was the first serious attempt towards data processing and It was designed in 1959.
- The **ORACLE database** achieved the subsequent major success enabling data processing and oracle was founded in 1977.
- Data processing has always been at the center of the software industry. Data processing is an evergreen field in software engineers. Software may evolve but the requirement of processing larger and larger data at faster speed will become more and more critical.
## How do we create data processing applications?
- We have used **RDBMS** technology for many decades.
- Some popular RDBMS systems are ORACLE, SqlServer, PostgreSql, MySql, Teradata and Exadata. They all come with different capabilities but the core technology is the same.
- These RDBMS systems offered us three main features to help us develope data processing applications:
  - SQL : An easy data query language.
    - We use sql for querying data.
  - Scripting languages such as PL/SQL and transact SQL.
    - We use scripting languages to do things that we couldn't do using sql.
  - Interface for other programming languages like JDBC and ODBC
    - They provided JDBC and ODBC so that we could interact with data using the programing languages.
- Things were perfect we could create data processing applications using the above technologies but then the data itself started to evolve.
- In the begining we saw data in rows and columns.
  - **COBOL** stored and accessed this data in plain text files example : CSV files.
  - RDBMS like ORACLE stored this data in a more advanced file format like dbf files. We do not care about the file format used by RDBMS but we see data in the format of rows and columns.
  - With time we developed some new data formats such as JSON and XML. RDBMS was not ready to store and process these JSON and XML files. They needed us to define a row column structure and then store it in the database.
  - However many RDBMS added this capability over some time and started to allow storing and processing JSON and XML files but by that time we developed some new formats example : TEXT, DOC, IMAGE, VIDEO (unstructured data)
  - RDMS was designed to handle such exansion of file formats.
  - So basically we developed three categories of data.
    - Structured
      - The structured data comes in a row column table format.
    - Semi-Structured
      - The semi-structured data does not follow the tabular structure. However it has another well defined key value structure such as JSON or XML. These types of data are called semi-structured data because they don't have a tabular structure but they do have some structure as a key value pair.
    - Un-Structured
      - These types of data don't have any definite pattern or structure.
      - The un-structured data comes in a text files, pdfs and other documents, images and video files.
- With the growth of the internet, social media and mobile apps businesses are collecting more semi-structure or un-structure data.
- Structured data is now a small portion of the overall available data within an organization.
- However RDBMs failed to bring the support for the un-structured data
## Big Data Problems:
Modern data processing applications must also be able to handle these problems : 
- Variety
  - Modern data processing applications must be able to handle all types varieties of data 
  - We need methods to store and process structured , semi-structured and un-structured data.
- Volume
  - The overall data volumen is relatively high these days.
  - Companies collect terabytes and petabytes of data in short periods of time and they don't have weeks and months to process such a large amount of data. They want to process such large volumes of data in a matter of hours and minutes.
  - So we need capabilities to handle large volumes of data.
- Velocity
  - The velocity of collecting data is very high.
  - The requirement of processing velocity is also very high
- These three problems combine are also called **Big Data Problem**.
- We had RDBMS systems developed and metured over many decades. However RDBMS was not designed to handle the big data problem.
- So the industry needed a Big Data platform to do the following:
  - Store high volumes of data arriving at a higher velocity.
  - Accomodate structured, semi-structured and un-structured data variety
  - Process high volumes of a variety of data at a higher velocity.

## Approaches to solve Big Data Solution
There are two approaches to solve the big data problem.
- Monolithic Approach :
  - This approach designes one large and robust system that handles all the requirements. TeraData and ExaData are the examples.
  - These two systems only support structured and semi-structured data. So we cannot call them big data systems but they are designed using a monolithic approach.
- Distributed Approach
  - In a distributed approach we take many smaller systems and bring them togeather to solve a bigger problem.
  - This system uses a cluster of computers to work as a single system. The combined capacity of this system can be equal to or even higher than a single monolithic system.
## Comparisions between Monolithic and Distributed approaches:
These two approaches are compared on the following criteria.
- Scalability :
  - Scalability is the ability of a system to increase or decrease the performance in response to the demand.
  - Lets take a look at both the approaches when it comes to scalability : 
    - Lets say we have a 10 terabytes of data stored in both the systems
    - We have 100 concurrent users reading and writing data to the systems.
    - Assume both the systems are working perfectly fine but over time the number of concurrent users and data volumne increased significantly.
    - Here both the systems have limited capacity i.e the CPU, MEMORY and the DISK_SIZE are fixed.
    - As the number of concurrent users and data volume increases these systems will eventually reach their maximum capacity.
    - If we are able to increase the capacity then the system is deemed to be scalable. If we are not able to increase the capacity then the system is deemed to be not scalable.
    - **Monolithic approach** : 
      - Both the approaches are scalable but scaling a monolithic approach is complex.
      - You will have to call the vendor to increase the capacity. It requires coordination with the system vendors.
      - They will bring in more processors increase the tower size and then install them in it.
      - This approach is known as vertical scalability
      - In a vertical scalability you will have to increase the hight of a single system adding more resources to one single system.
      - Hence a monolithic system is vertically scalable.
    - **Distributed systems** : 
      - On the other side the distributed system is also scalable.
      - Scaling a distributed system is as simple as adding new computers to the network.
      - This approach is called horizontal scaling.
      - In horizontal scaling we add new members to the cluster and increase the length of the network.
      - Horizontal scalability takes less time because you can easily bur some new systems.
      - A distributed system is horizontaly scalable.
- Fault Tolerance and High availability
  - Lets look at both the systems.
  - What happens if a cpu burns out?, a network card fails? or the system's motherboard fails?
  - **Monolithic system:**
    - In an event of hardware failure the monolithic system will stop working.
    - It may not tolorate the hardware failure.
    - The duration of time the system is down due to hardware failure the application will not be available to the users.
  - **Distributed system:**
     - If a computer fails in a cluster the other computers remains working.
     - A distributed system can tolerate many failures.
     - A system failure in a cluster will only reduce the capacity but the overall system remains working.
- Cost-Effectiveness :
  - **Monolithic systems:**
    - Monolithic systems are expensive.
    - Scaling them takes a lot of time. So you may have to start with a large machine even though you may need a smaller one.
  - **Distributed systems:**
    - The initial costing of a distributed system is low because initially you can keep the size of the cluster small and the size can be increased later as needed making it more economical.
    - You can also use an average quality machine that you can get at a reasonable price.
    - You can get cloud environment to get machines at rental prices and create your cluster
    - These options make distributed systems more economical and cost effective.
## Analysis : 
- Engineers evaluated both the **Monolithic** and **Distributed** approaches to design a new data processing system and handle Big Data Requirement.
- The evaluation indicate that the distributed systems could be a better choice.
- This is where a new system called **Hadoop** came into existance.
- **Hadoop** was a revolutionary big data processing platform.
- The **Hadoop** platform was designed and developed in layers.
- The core platform layer offered three capabilities.
  - Distributed cluster formation or Cluster Operation System (**YARN**)
  - Data storage and retrieval on the distributed cluster or Distributed storage (**HDFS**)
  - Distributed data processing using Java programming language. (**Map**/**Reduce**) framework
- (**YARN**) Cluster OS : **Hadoop** was developed as an OS for the distributed cluster.
  - We can create a data processing software, install it on one computer and run it there. The computer comes with an operating system.
  - The OS allows you to use computer resources like CPU, MEMORY and DISKS to run your application.
  - If you don't have an OS you cannot run your application on your system.
  - Similarly when you create a cluster of computers you need a cluster OS.
  - The Cluster OS will allow you to use the cluster resources such as CPU, MEMORY and DISK.
  - A cluster OS has more complex work to do, because a CPU, MEMORY and DISK are spread across the computers that are in the cluster. We are not using a single computer where everything is available on a single machine.
  - A cluster is a group of computers and the cluster OS makes it work like a single large computer.
  - And this was the first capability of the hadoop platform.
- (**HDFS**) Distributed storage : **Hadoop** also allowed us to store data and retrieve it back.
  - The data is internally distributed on the hard disk on the cluster. However **Hadoop** offered us a distributed storage system and allowed us to save and read the data file as we do it on a single machine.
- (**Map**/**Reduce**) Distributed computing : The next feature of **Hadoop** is that it allows us to write a data processing application in Java and run it on the cluster.
  - **Hadoop** offered is a new distributed data processing framework known as map reduced framework for processing large volumes of data.
  - **Hadoop** platform was designed to use a cluster of computers as a single large machine.
  - You can read/write and program data processing applications and run them on a **Hadoop** cluster without realising that you are working on a cluster.
  - **Hadoop** simplified the distributed computing for developers.
  - We develope a data processing application on **Hadoop** the same way we develope the applications for a monolithic systems but the program runs on a distributed computing platform and uses parallel processing.
  - **Hadoop** platform was designed and developed in layers. The core layer offered a cluster OS, Distributed storage and Map/Reduce framework.
  - The **Hadoop** community developed many other tools over and above the **Hadoop** core platform.
    - **HIVE** database : We can run SQL queries just like we do in a relational database. We can configure HIVE on the hadoop platform and run SQL queries on the data just like any other RDBMS system.
    - **HBASE** database
    - **PIG** scripting language : HADOOP also offered some scripting languages like apachae pig scripting
    - **SCOOP** data injection tool
    - **OOZIE** workflow tool.

## What is Hadoop and how it works?
**Hadoop** is a data processing platform that offers the following core capabilities.
- **YARN** stands for (**Y**et **A**nother **R**esource Ma**n**ager) it is the **Hadoop**'s cluster resource manager. We also call it **Hadoop** cluster operating system.
  - An operating systems allows multiple programs to be in memory and run simultaneously and this is acheived by sharing resources like CPU, MEMORY and DISK I/O.
  - The **YARN** does the same it allows multiple applications to run on hadoop cluster and share resources amongs the applications.
  - **Hadoop YARN** has three main components:
    - **RM** Resouce Manager
    - **NM** Node Manager
    - **AM** Application Master
  - Let's assume we have 5 computers and we want to make **Hadoop** cluster using these 5 computers
    - We will have to install **Hadoop** on each computer and configure them to make a **Hadoop** cluster.
    - Installing and configuring a **Hadoop** cluster is as simple as installing software on a computer.
    - Assume we have installed and configured **Hadoop** on these 5 computers and these 5 computers form a **Hadoop** cluster.
    - **Hadoop** uses a master slave architecture, so one of the 5 machines will become a master and the remaining will act as a worker node.
    - Configuring **Hadoop** will also install a **YARN Resource Manager** service on the master node. It also installs the **Node Manager** service on all the worker nodes.
    - ![YARN Config](images/yarn_config_on_a_hadoop_cluster.png)
    - The diagram on the above shows the **YARN** configuration on a **Hadoop** cluster.
    - One node acts as a master and runs a **YARN** **Resource Manager** server. The other 4 nodes acts as a worker and runs a **Node Manager** service.
    - The **Node Manager** will send the node status report regularly to the **Resource Manager**.
    - Now we want to run a data processing application on this cluster.
    - For running an application on **Hadoop** you will have to submit the application to the  **YARN Resource Manager**.
    - We have many ways to submit the application to **YARN**
    - Lets suppose you have submitted a JAVA application to **YARN** using a command line submit tool.
    - Now the **Resource Manager** should run this application on the cluster.
    - The **Resource Manager** will request one of the **Node Managers** to start a resource container and run an **Application Master** container.
    - The application that you submitted runs inside the **Application Master** container.
    - And that's all your application starts running inside the **Application Master** container.
    - ![YARN application startup execution](images/YARN_app_startup_process.png)
    - **What is a container?** : It is a set of resources that includes memory and cpu.
    - For example : A **YARN CONTAINER** may be a set of 2 CPU cores and 4 GB of memory. So whenever we think of a **YARN CONTAINER** we should think of a box of some cpu or memory.
    - Now lets assume we submit another application.
    - The **Resouce Manager** will again ask another **Node Manager** to start another **Application Master** container in one of the worker node and this new application will now start running inside that **Application Master** container.
    - Each application in **YARN** runs on different **Application Master** container.
    - If you have 10 applications running in parallel then you will see 10 **Application Master** container on your **Hadoop** cluster.
- **HDFS** (**H**adoop **D**istributed **F**ile **S**ystem) and it allows you to save and retrieve data files in the hadoop cluster.
  - The **HDFS** has two main components.
    - **NN** - Name Node
    - **DN** - Data Node
  - ![HDFS](images/HDFS.png)
  - Lets assume we have 5 computers shown here (we have already installed hadoop on these computers and created a hadoop cluster)
  - We already know that hadoop works on master slave architecture. Where one node will be designated as a master and the rest of the node will be designated as slaves by hadoop.
  - ![HDFS_NN](images/HDFS_nn.png)
  - **Hadoop** will install a **NN** Name Node service in the Master Node and each worker node runs a **DN** Data Node service. The **NN** Name Node with the **DN** Data Node service forms the **HDFS** (**H**adoop **D**istributed **F**ile **S**ystem).
  - The primary purpose of **HDFS** is to allow us to save our data (Files) in this **Hadoop** cluster and then read it whenever required.
  - **How does it work?**
    - Let's assume we want to copy a large data file onto a **Hadoop** cluster.
    - ![HDFS_save_file](images/HDFS_save_file.png)
    - So you will initiate the file copy command.
    - This file copy request will go to the **NN** Name Node.
    - The **NN** Name Node will re-direct the file copy command to one or more **DN** Data Nodes. Lets assume you get redirection for three **DN** Data Nodes
    - The file copy command will split the file into smaller parts and write those parts in the three **DN** Data Nodes.
    - The file copy command will split the file into smaller parts and each part is known as a block the typical size is 128 MB. 
    - The file copy command will write some files to **DN** Data Node 1 , some will be written in **DN** Data Node 2 and the remaining of them will go to **DN** Data Node 3. The main node facilitates this process and keeps track of all the file's metadata.
    - **What is the File metadata?**
      - File name
      - File size
      - File block, block ID, clodk sequence, block location
    - The file is broken and spread on the **DN** Data Nodes and all the information required to re-assemble the files are kept in the **NN** Name Node.
    - **Now lets talk about the read operation. You will initiate the read operation when you want to read a data file.**
    - The read operation request goes to the **NN** Name Node. The Name Node owns all the information that is required for re-assembling the file from the blocks stored at the data node.
    - So the **NN** Name Node will redirect the read operation to the target **DN** Data Nodes.
    - The read api will recieve data blocks from the **DN** Data Node and re-assemble the file. Using the metadata provided by the **NN** Name Node.
- Map/Reduce - Distributed Computing : 
  - Map/Reduce is a programming model and a Programming Framework.
  - Programming model : It is a technique or a way of solving problem.
  - The Map/Reduce framework is a set of apis and services that allow you to apply the Map/Reduce programming model.
  - **NOTICE :** **Hadoop** Map/Reduce framework is outdated and is not used anywhere.
  - **Let's understand the Map/Reduce programming model.** (CRITICAL : very very important)
    - Problem : You have a csv file, this file is 20 terabytes. I asked you to count the number of lines in the file. 
    - Soution 1: 
      - Sudo code 
        - ```python
              open file as f_hd
                for each t_line in f_hd.get_line():
                  n_count = n_count +1
              close f_hd
              print n_count
          ```
        - The file size is 20 terabytes. It is hard to find such machines that has the capability of storing 20 terabytes of data and run a script like as shown above to count the lines.
        - Even if you managed to find a server that has the high-end specs your program will take hours or days to count the lines.
        - It takes 3 to 4 hours just to read 1 terabyte of data from the disk
        - So we have two problems here 
          - Storage camapcity problem
          - Processing time problem
        - This problem grows even more if we increase the size to several Petabytes.
    - Lets assume you have 21 node Hadoop cluster.
      - One node become the Master and the other nodes become the worker.
      - **HDFS** run the **NN** Name Node in the master node and **DN** Data Node in the worker nodes. 
      - **YARN** runs the **RM** Resource Manager in the master node and **NM** Node Manager in the worker nodes.
      - Now lets talk about the resources : 
        - Each Node comes with a 4 X 2 TB of HDD = Single node of 8 TB HDD
        - Each None comes with a 4 X Dual code cpus = 8 Cpu cores 
        - Each Nonde comes with a 4 X 16 DB RAM = 64GB Ram
        - Total **Hadoop** cluster HDD capacity is 160 TB
        - Total **Hadoop** cluster Cpu core numbers is 160 cpu cores
        - Total **Hadoop** cluster ram capacity is 1280 gb ram
      - You can use **HDFS** to copy your 20TB file onto this **Hadoop** cluster.
      - **HDFS** will break the file into small 128 MB blocks and spread them across the cluster.
      - ![Map_Reduce](images/Map_Reduce.png)
      - Your storage problem is taken care of the **Hadoop** cluster.
      - What about the processing time problem? That's where the Map/Reduce programming model comes into play
    - Solution 2:
      - This time I have broken my logic into 2 parts.
      - ```python
            def map(file_block):
              open file_block as fb_hd
              for each t_line in fb_hd.get_line():
                n_count = n_count + 1
              close fb_hd
              return n_count
            def reduce(list_counts):
              for each cnt in list_counts
                total_count = total_count + cnt
            print(total_count)
        ```
      - Focus on the ```map``` function:
        - ```python
            def map(file_block):
              open file_block as fb_hd
              for each t_line in fb_hd.get_line():
                n_count = n_count + 1
              close fb_hd
              return n_count
          ```
        - The map function here has almost the same code as in Solution 1 but instead of opening the file its now opening a ```file_block```
        - Now in the old logic the counting was happening on the file but here its happening on a file block
        - ![Map_Reduce](images/Map_fucntion.png)
        - I can run the ```map``` function on all the Data Nodes in parallel.
        - This ```map``` function will opean the file block on each node and count the lines
        - At the end of the execution I will have the number of lines count of each file blocks at the given Data Node.
        - See the magic I am counting lines on 14 Data Nodes in parallel. Evenrything runs at the same timea and I will get the line counts at the 1/14th of the time compared to doing it on a single machine.
        - However I will have 14 line counts. Each count represents the number of lines in their respective Data Nodes.
      - Now I will start a reduce function on one Data Node.
        - ```python
              def reduce(list_counts):
                for each cnt in list_counts
                  total_count = total_count + cnt
              print(total_count)
          ```
        - ![Reduce_fun](images/Reduce_fun.png)
        - All the data nodes will send their counts to that Data Node where the reduce function is running.
        - This reduce function will recieve 14 line counts in an array. So I will loop through the array and sum up all the line counts.
    - So the Map/Reduce is a programming model to break your application logic into two parts.
      - Map part where you will write the logic for your parallel calculations.
      - Reduce part where you will do the summissions or other types of aggregations and consolidations.
    - **Hadoop** offered a **HIVE** database as an additional component. **HIVE** allowed you to write sql expressions but the **HIVE** sql engine translate all your sql expressions into a Map/Reduce program.
    - However today we do not use raw Map/Reduce in **Hadoop** we use high level solutions like **HIVE** sql, **Spark sql** and **Spark scripting** and develop data processing application.
    - We do not go down to the Map/Reduce functions at a lower level but understanding the idea is critical for your learning.
- Google was the first company to realise the big data problem.
  - They were creating a seach engine and they wanted to discover and crawl the web pages over the internet and capture the content and metadata.
  - At a high level google has 4 main problems to solve
    - Data collection and ingestion
    - Data storage and management
    - Data processing and transformation
    - Data access and retrieval
  - Google solved all the above problems and they were generous enough to share their solution with the world.
    - Google File system
      - Here it talked about the data storage and management problems.
    - Map Reduce 
      - Data processing and transformation problem.
  - The open source community well appreciated these white papers and they form the basis of similiar open source implementation.
    - The open source community implemented Google File System **GFS** as Hadoop Distributed File System **HDFS**
    - Hey implemented Google's **Map/Reduce** as Hadoop's **Map/Reduce** programming framework

- Apache **HIVE** was one of the most popular component of **Hadoop**. **HIVE** offered the following core capabilities 
  - Create 
    - Databases
    - Tables
    - Views
  - Run SQL queries
  - **HIVE** simplified using **Hadoop**
    - Map/Reduce programming model was complex to use. Application developers struggled to solve the data processing problems using the Map/Reduce.
    - This is where **HIVE** came to the rescue it allowed us to create databases and tables using DDL statements.
    - Then they also allowed us to use the sql queries on the table. The majority of the work force were familiar with RDBMS and they alreay knew sql so using sql was easy to adopt.
    - **HIVE** sql engine internally translated the sql queries into Map/Reduce programs and as a result of this the developers were saved from writing the Map/Reduce code in Java.

- Some problems with **Hadoop**:
  - Performance : 
    - Map/Reduce was slow. 
    - Map/Reduce implemented parallel processing so it was faster and more efficient than a single computer.
    - However the **HIVE** sql query performed slower than the RDBMs sql queries.
  - Ease of development
    - **Hadoop** offered only map reduce model but writing a Map/Reduce program was a black art.
  - Language support
    - **Hadoop** Map/Reduce was only available in JAVA
  - Storage
    - Setting up storage for the **Hadoop** cluster required adding computers. So if you want more storage then add more computers to the **Hadoop** cluster.
    - It was a cheaper option in the begining but when cloud platforms started offering cheaper storage alternatives.
    - Adding computers to the **Hadoop** cluster to increase the storage started to look expensive.
  - Resouce Management
    - **YARN** worked as a resource manager for **Hadoop** and it offered a **YARN** container for managing resources.
    - But sometime later the industry developed some other container management solutions such as Mesos, docker and kubernetes.
    - **YARN** forced us to install and create a **Hadoop** cluster and then manage containers over and above the **Hadoop** cluster.
    - Experts wanted to try other light weight container management options.
- As you can see **Hadoop** left a lot of room for improvements and that's where Apache Spark comes into the picture.
- Apache spark was developed to simplify and improve the ideas of the Map/Reduce framework.
  - Spark program tends to run 10 to 100 times faster than Hadoop Map/Reduce program
  - Just like **HIVE** Spark also offered sql but Spark's sql was also 10 to 100 times faster than **HIVE** sql.
  - Spark offered an idea of composable functional apis instead of complex Map/Reduce model.
  - Composable apis were much simpler to adopt for designing the data processing solutions.
  - Spark supported Java, Scala, Python and R programming languages.
  - Spark also decoupled the **HDFS** and started using the cloud storage example Amazon S3 amd azure blob storage.
  - Spark also removed the dependency on **Hadoop YARN**. Now devs can use other container management systems like docker , mesos etc..
  - Spark started as an improvement over **Hadoop** Map/Reduce but over time it became independent system.
  - Now you can use spark in two kinds of setups 
    - Spark with **Hadoop** (Data Lake) : 
      - We use the **Hadoop** platform as the datalake platform. 
      - The primary developer technology on **Hadoop** datalake is Apache spark
      - Map/Reduce framework is gone away for ever.
      - **HIVE** is also loosing its place for **Spark sql**.
    - Spark without **Hadoop** (LakeHouse)
      - The cloud platform are more popular these days.
      - The idea of **Hadoop** DataLake is now advanced and mordernized with a new name as LakeHouse in the cloud platform.
      - The driving force behind the cloud LakeHouse is the databricks spark paltform.

## What was there before Map/Reduce and HDFS:
Before the Map/Reduce and HDFS came into existance datawarehouses existed 
    - Teradata
    - Exadata
- How do we use these datawarehouses?
    - ![datawarehouse](images/datawarehouse.png)
    - We create pipelines to collect data from many OLTP systems and bring them to the data warehouse.
        - **OLTP** systems (**O**nline **T**ransaction **P**rocessing systems) are the source systems from which data is collected, transformed, and loaded into the data warehouse.
    - Then we processed all that data to get business insights and used it to make the correct business decisions. This is precisely the same as what **Hadoop** promised to offer.
- So the advent of **HDFS** and Map/Reduce started challeging these data warehouses in thre critical respect.
    - Hadoop : 
        - Horizontal scaling
        - Low capital investment
        - Exabytes to Petabytes 
        - Structured , Semi Structured and un Structured data
    - Datawarehouse : 
        - Vertical scaling
        - Large capital 
        - Terabytes to Exabytes of data
        - Only structured Data
- The datawarehouse was challenged and we needed to give a name for this new hadoop approach to solving the problem and eventually its called the DataLake
- **How did dataLake work?**
    - Here is how the dataLakes were initially imagined.
    - ![datalake](images/datalake.png)
    - Here same as datawarehouses we collected data from different sources and stored them in **HDFS**
    - The we used Map/Reduce and Spark to process this data and prepare new data models for generating reports and business insigts.
    - Spark took over the MAp/Reduce and other tools over a period of time. So now we are using Spark to process and prepare data for reporting. 
    - This processed data was also stored in DataLake storage for business intelligance and reporting.
    - Most  of the popular BI and reporting tools offered a connector to access data from the DataLake.
    - DataLake also allowed us to collect and process huge volumes of semi-structure and un-structured data. This is what we needed for machine learning and AI
    - Hence it also empowered the AI and ML workloads.
    - This is how a DataLake was imagined and applied during the initial days of evolution.
    - However the DataLake technology missed two super-critical technologies that data warehousing offered.
        - Transaction and Consistency
        - Reporitng Performance
    - There were a few other things that DataLake could not support properly.
    - So we started adopting different architectures for implementing DataLakes.
    - ![DataLake_Architecture](images/DataLake_Architecture.png)
        - We started integrating relational database and datawarehouses for reporting and BI purposes.
            - So we basically collected data in the DataLake storage.
            - Processed it using Apache Spark.
            - And then stored their result in datawarehouse.
            - Finally we connected the reporting and BI with the datawarehouse.
            - Machine learning and AI still worked on the DataLake but BI and reporting again shifted to datawarehouses.
            - So DataLake married DataWarehouse. This is the current architecture for many organizations.
        - Hoever over some timess a lot of things evolved.
            - Hadoop as a platform lost its excitement and hype.
            - Cloud infrastructure have become more economical and have seen wider adoption.
            - With these development the motion of DataLake also matured as a platform with 4 key capabilities.
                - ![DataLakeLayers](images/DataLakeLayers.png)
                - Data Collection and Ingestion :
                    - The notion of the DataLake recommends that you bring data into the lake in a raw format, that means you should ingest the data into the DataLake and preserve an unmodified immutable copy of data.
                    - This ingest block of the dataLake is all about identifying , implementing and managing the right tools to bring data from the source systems to the dataLake.
                    - We do not have one ingestion tool that solves the purpose in all use cases and hence many vendors are comepeting in this space
                - Data Storage and Management : 
                    - The core of the DataLake platform is the storage infrastructure.
                    - In todays DataLake this could be an on premise HDFS or Cloud object stores examples Amazon S3 , Azure blob, Azure DataLake storage, Google Cloud Storage
                    - Cloud storage is leading because they provide high availability and scalability at an extremely low cost in almost no time to procure.
                - Data Processing and Transformation :
                    - This is the place where all the colputation is going to happen.
                    - When I say computation that means the following kind of work.
                        - Initial data quality check
                        - Transforming and preparing data.
                        - Correlating, Aggregating , Analyzing and extracting business insights.
                        - Applying machine learning model.
                        - The apache spark falls in this space.
                - Data Access and Retrieval.
                    - This part is what allows you to consume the data from the DataLake.
                    - You can think of the DataLake as a respository of raw and processed data.
                    - Now the consumption is all about putting that data for real life usage.
                    - The consumption requirments will be coming in all the possible formats.
                        - You might have DataScientists and DataAnalyst looking to access data from the DataLake.
                        - Experimenting data scientists will be intrested in accessing files.
                        - You might have some application and dashboards those guys are also intrested in aggregated results and insights
                        - Some of them ask you to even allow JDBC and ODBC connections
                        - Others may ask you to REST interface
                    - Every dataLake consumer comes with a different requirements and expectations, complicating the consumption layer.
                    - Hence we have many products competing to find a place in this space as well
                    - DataWarehouses and Relational Databases are the most prominant in this layer.
- This is what a DataLake is at a high level. However the DataLake platform is much more complicated as a whole
- ![DataLake_implementation_overview](images/DataLake_implementation_overview.png)
- However the dataLake platform is much more complicated as a whole.
- You will need a bunch of capabilities to complete your dataLake implementation.
    - Security and Access control
    - Scheduling and Workflow Management
    - Data Catalog and Meta Data
    - Data Lifecycle and Governance
    - Operations and Monitoring

## Spark as a unified data analytics and processing platform.
- Apache spark is a distributed data processing framework.
- ![Spark_ecosystem](images/Spark_ecosystem.png)
- This diagram represents the Spark ecosystem. 
- This figure will help us understand how the whole ecosystem is stiched togeather.
- The spark ecosystem is designed in two layers :
    - The bottom layer is the Spark's core layer (**Spark Engine**):
        - ![Pyspark_architecture](images/Pyspark_architecture.png)
        - The spark's core layer itself has got two parts:
            - A distributed computing engine
            - A set of core apis
            - These two things togeather makes the spark ecosystem.
        - ![spark_architecture2](images/spark_architecture2.png)
        - This whole thing runs on a cluster of computers to offer you distributed data processing
        - However Spark does not manage the cluster. It only gives you a data processing framework.
        - ![cluster_manager_spark](images/cluster_manager_spark.png)
        - So you are going to need a cluster manager. People use different names for this cluster manager , it is also called as resource manager or container orchistrator.
        - However they offer similar services to spark and spark is designed to work with both.
        - Spark was initially based on Hadoop's Map/Reduce and it was adopted in the hadoop platform. So the hadoop's **YARN** resource manager is the most commonly used cluster manager for Spark.
        - However you have other options. 
            - Mesos and Spark's stand alone cluster manager
            - Kubernetes : The newer versions of spark is also compatible with kubernetes as a cluster orchistrator.
        - Spark doesn't comes with an inbuilt storage system. It allows you to process the data which is stored in a variety of storage systems. The most popular and cpmmonly used storage systems are : 
            - **HDFS**
            - Amazon S3 
            - Asure DataLake storage
            - Google Cloud Storage
            - Casandra file system
        - So one thing is clear apache spark does not offer cluster management and storage management. All you can do with apache spark is to run your data processing workloads and that part is managed by the spark's compute engine.
        - The Compute engine is responsible for the bunch of things.
            - Breaking your data processing work into smaller tasks.
            - Scheduling those tasks on the cluster for parallel execution
            - Providing data to these tasks.
            - Managing and Monitoring those tasks.
            - Provide you fault tolerance when a job fails.
            - And to do all these the core engine is also responsible for interacting with the cluster manager and the data storage manager.
            - The spark compute engine is the core that runs and manages your data processing work and provides you with the seemless experience.
            - All you need to do is submit your data processing work to Spark and the Spark core will take care of everything else.
    - Then we have the top layer as a DSLs , Libraries and apis (**Spark Core**):
        - ![spark_core_layer](images/spark_core_layer.png)
        - This layer is the programming interface layer that offers you the apis in 4 major languages.
            - Scala
            - Java
            - Python
            - R
        - These are the apis that we use to write the data processing logic during the initial days of apache spark.
        - However these apis were built on resilient distributed data service **RDD**s and people found them a little tricky to learn and use them for their day to day data processing work. Some people still use them today.
        - However these apis are the most complicated way to work with apache spark. They also lack some performance optimization features. The spark creators are recommending to avoid them as much as possible.
        - However these apis can offer you the highest level of flexibility to solve some complex data processing problems.
    - Top mosy layer (Spark SQL, Streaming, Ml lib [Machine learning], GraphX Graph Computation)
        - The top most layer is the prime area of intrest for most Spark developers and data scientist
        - This layer is again a set of libraries, packages, apis and DSL. These are developed by the Spark community over and above the core api.
        - So you will be using these top level apis and DSLs but internally all of those will be using the Spark core apis and unltimately things will go to the spark compute engine.
        - The top most layer is grouped into 4 categories to support 4 different data processing requirements.
        - However this is just a logical grouping and there is no rigid boundary. Things are going to overlap in most of the real life projects.
        - The first group is a set of two things. 
            - Spark Sql :
                - Spark sql allows you to use sql queries to process your data
            - Spark dataFrames or DataSet apis :
                - Spark DataFrame will allow you to use functional programming techniques to solve your data crunching problems.
            - These apis are available in Java, Scala and Python. These two combined will enable you to solve most of the structured and semi-structured data crunching problems.
        - The second group is Spark Streaming Libraries.
            - These libraries allow you to process a continuous and unbounded stream of data.
        - The thrid group is Ml lib.
            - It is a set of libraries specifically designed to meet your machine learning, deep learning libraries and  AI requirements.
        - The fourth group is the graphX 
            - This is the last group which are the set of graph processing libraries.
            - They allow you write the graph processing algorithems using apache spark. 
        - This top most layer helps you solve your data crunching problems and all these are available in multiple languages such as Java, Python, Scala and R.
## What is so great about spark ecosystem? Why is it so popular?
- **Abstraction**
    - Spark will abstract away that your coding will execute the program on a cluster of computers. 
    - In the best case senario you will work with tables and use SQL queries. You will feel like working with a database
    - In the worst case senario you will work with RDDs and DataFrames. You will feel like you are working with Java or Scala collections or Python DataFrame
    - All the complexities of a distributed storage, computation , parallel programming is abstracted away by the spark core.
- **Unified Platform**
    - Spark combine the capability of sql queries, bash processing , stream processing, structured and semi-structure data handling, graph processing, machine learning and deep learning all of this in a single framework using your favourite programming language.
    - You can mix and match them to solve many sophisticated requirements.
- **Ease of Use**
    - Spark code when compared to **Hadoop** is much shorter, simpler to read and understand.
    - You also have a growing and evolving ecosystem to offer ready to use libraries, algorithems and integrations with a wide variety of other systems.
- These three things make spark a super popular distributed computing platform for data processing.

## Databricks
- The original creators of Apache spark donated it to Apache foundation and made it an open source project. 
- However that same team formed a company and a commercial product around the apache spark. The company and the product are both named Databricks
- **So what do they offer over and above the apache spark?**
    - Spark on cloud platform : 
        - Databricks bring the apache spark to the cloud platform.
        - Databricks product is called Databricks Cloud.
        - Databricks cloud is only available in the cloud platforms.
        - Databricks are available on Azure, Google cloud and AWS
    - Spark Cluster Management.
        - Databricks allows you to launch a cluster for running spark applications automatically.
        - You don't need to configure and launch a cluster manually for running your spark applications. 
        - Databricks allows you to start, configure and install all the dependencies and runtime libraries on all the nodes to your spark application.
        - Databricks gives you an easy way to configure, start and shutdown the clusters in the cloud environment. 
    - Notebooks and Workspace
        - Databricks cloud also offer you notebooks and workspace for spark development.
        - These workspace and notebooks are as good as  IDEs for spark development.
        - You can use the notebook to develope, share and collaborate with your colligues for spark development.
        - You can also integrate databricks notebook with configuration management tools example git.
    - Administration Controls
        - Databricks cloud provide you Adminitration controls so you can manage access for your workspace, clusters and storage, and implement security controls
    - Optimized Spark
        - Databricks offers you an optimized and tuned version of spark over and above the apache spark.
        - Databricks spark runtime is 5 times faster than the apache spark runtime.
    - Databases/Tables and Catalog
        - Databricks offer you an integrated HIVE meta store, to store meta data.
        - It allows you to create databases, table, views using spark sql
    - Databricks SQL Analytics
        - Databricks also offers advanced sql query engine called photon
            - It allows you to gain datawarehouse grade performance of your sql queries and dashboard on top of the datalake infrastructure
    - Delta Lake Integration
        - Databricks cloud offers seemless delta lake integrations that offers async transactions and data consistency features to your application workload and spark sql.
    - ML Flow
        - Databricks also offer ML flow, it allows us to manage the ML lifecycle:
            - ML experimentation
            - ML deployment
            - Model registry
    - Industry vertical accelerators
        - It also offers some industry specific solution accelerators for rapid adoption and solving common industry specific problems.
    - Databricks make spark implementation a lot easier on all three cloud platform.

## Spark Development Environments
- Spark projects are developed and deployed in two kinds of environments.
    - Cloud platforms
    - On-premise platforms
- There are two standard methods to setup your spark development environments.
    - Notebook env
        - If your project is going in cloud then notebooks are preferred
        - This is not mandatory even cloud platforms allow you to develope in your local machines and deploy it later in the cloud.
        - Databricks cloud is the standard approach for designing and developing spark applications in a cloud environment.
        - We use the databrick's notebook environment for cloud based spark development projects
    - Python IDE
        - An on premise project python IDEs are preferred.
        - This setup will have a cloudera hadoop setup

## How to setup Local Spark Development Environment on ubuntu (linux)
Spark is a JVM application it runs on a Java Virtual Machine. You might write code in python but sprak runs most things in JVM so you need Java Development Kit on your local machine for installing and running your spark application.
- In my case the most recent version of spark is 4.0.1 as of 16th October 2025
- This version of spark supports java 21
    - Install java 
        - sudo apt update
        - sudo apt upgrade   
        - sudo apt install openjdk-21-jdk   
        - Verify the java version
            - java -version
            - javac -version
    - Install Spark 4.0.1
        - Download Spark 4.0.1 (make sure that the spark that you are downloading has support for hadoop) Notice that the suffix ```-hadoop3``` is present this is a pre-built spark package that includes hadoop client binaries. Spark will have the necessary Hadoop client JARs to interact with HDFS or YARN
            - wget https://dlcdn.apache.org/spark/spark-4.0.1/spark-4.0.1-bin-hadoop3.tgz
        - Extract the downloaded tgz file
            - tar -xvzf spark-4.0.1-bin-hadoop3.tgz
        - Move Spark to a stable location example : /opt/spark
            - sudo mv spark-4.0.1-bin-hadoop3 /opt/spark
        - Link Java, Spark and Python with the OS Since I use zsh as my default shell I am going to save my configs realted to them in ~/.zshrc if you use bash as your default shell then you have to save those configs in ~/.bashrc
            - nvim ~/.zshrc
            - ```shell 
                    # Apache Spark 4.0.1 configuration
                    export SPARK_HOME=/opt/spark
                    export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

                    # Java 21 (adjust path if needed)
                    export JAVA_HOME=/usr/lib/jvm/jdk-21

                    # Python for PySpark
                    export PYSPARK_PYTHON=python3
                    export PYSPARK_DRIVER_PYTHON=python3
             ```
            - Reload your shell ```source ~/.zshrc```
    - Install pyspark
        - pip3 install pyspark==4.0.1
        - python3 -c "import pyspark; print(pyspark.__version__)"
    - Make the requirements.txt file 
        - pip list freeze > requirements.txt

### Lets test a small pyspark program and see if its working
#### NOTICE : 
Before we start I just want to provide you the link to the pyspark's documentation https://spark.apache.org/docs/latest/api/python/getting_started/index.html

#### Here we are just read a csv file and printing the dataFrame on the screen

In [8]:
from pyspark.sql import SparkSession

# create a spark session
spark = SparkSession.builder\
        .appName("ReadCsvFile")\
        .getOrCreate()

csv_file_path = "/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_data_missing_values.csv"

df = spark.read.csv(
    path=csv_file_path,
    header=True,
    inferSchema=True
)

df.show()

+----------+-------------------+----------------+---------------+-----------------+
|      date|temperature_celsius|humidity_percent|wind_speed_kmph|weather_condition|
+----------+-------------------+----------------+---------------+-----------------+
|2023-01-01|               -2.9|            87.4|           11.9|             Snow|
|2023-01-02|               15.9|            56.8|            5.4|             Snow|
|2023-01-03|               22.8|            48.7|           11.3|             NULL|
|2023-01-04|               39.4|            56.4|           12.2|             Rain|
|2023-01-05|                7.8|            82.9|            7.1|             Rain|
|2023-01-06|               -1.5|            12.9|           Rain|             NULL|
|2023-01-07|               20.4|            67.0|            7.0|              Fog|
|2023-01-08|               36.8|            83.6|            5.7|           Cloudy|
|2023-01-09|                7.5|            79.0|            9.4|            Sunny|
|2023-01-10|               65.2|             6.5|          Sunny|             NULL|
|2023-01-11|               31.5|            56.6|            9.2|           Cloudy|
|2023-01-12|               16.6|            46.6|            9.2|            Sunny|
|2023-01-13|               21.6|            40.6|           10.1|             Rain|
|2023-01-14|               16.4|            42.9|           13.5|             Rain|
|2023-01-15|               NULL|            74.3|            8.9|             Snow|
|2023-01-16|               25.8|            72.3|            7.2|              Fog|
|2023-01-17|               13.7|            29.1|            7.1|            Sunny|
|2023-01-18|               32.8|            70.1|            9.9|              Fog|
|2023-01-19|                5.8|            73.5|           12.8|             Rain|
|2023-01-20|               17.0|            52.1|           15.7|             Rain|
+----------+-------------------+----------------+---------------+-----------------+
only showing top 20 rows

In [9]:
df.printSchema()

root
 |-- date: date (nullable = true)
 |-- temperature_celsius: double (nullable = true)
 |-- humidity_percent: string (nullable = true)
 |-- wind_speed_kmph: string (nullable = true)
 |-- weather_condition: string (nullable = true)

In [10]:
spark.stop()

#### Here I am creating a dataFrame usig a list of tuples

In [14]:
spark = SparkSession.builder \
        .appName("CreateDf") \
        .master("local[2]") \
        .getOrCreate()

data_list = [
    ("Rollex", "R997"),
    ("Ballistic", "B1000"),

    ("Barbatos", "B117"),
    ("Barricade", "B247"),
    ("Assault","A201"),
    ("Kombat","K365"),

    ("Bullet", "B762"),
    ("Artillery", "A150"),
    ("Dynamite", "D911"),
    ("Shotgun","S12"),

    ("Shockwave","S360"),
    ("Ignition","I6000"),
    ("GroundZero","G101"),
    ("Venom","V204"),

    ("Ghost","G404"),
    ("Phantom","P404"),
    ("Shadow","S404"),
    ("Recon","R200")
]

df = spark.createDataFrame(data_list).toDF("Name","Assigned_ID")
df.show()

+----------+-----------+
|      Name|Assigned_ID|
+----------+-----------+
|    Rollex|       R997|
| Ballistic|      B1000|
|  Barbatos|       B117|
| Barricade|       B247|
|   Assault|       A201|
|    Kombat|       K365|
|    Bullet|       B762|
| Artillery|       A150|
|  Dynamite|       D911|
|   Shotgun|        S12|
| Shockwave|       S360|
|  Ignition|      I6000|
|GroundZero|       G101|
|     Venom|       V204|
|     Ghost|       G404|
|   Phantom|       P404|
|    Shadow|       S404|
|     Recon|       R200|
+----------+-----------+

In [15]:
spark.stop()

## Micro project 1 
### Problem statement : 
- Load the given data file and create a spark data frame.
- Use the spark data frame to answer the following questions.
    - How many distinct types of calls were made to the fire department?
    - How are distinct types of calls made to the fire department?
    - Find out all responses or delayed times greater than 5 minutes?
    - What were the most common call types?
    - What zip codes amounted for the most common calls?
    - What San Francisco neighborhoods are in the zip codes 94102 and 94103
    - What was the sum of all calls, average, min and max of the call response times?
    - How many distinct years of data are in the csv file?
    - What week of year in 2018 had the most fire calls?
    - What neighborhoods in San Francisco had the worst response time in 2018.

Use this link to download the csv file of the data used here in this project : ```https://github.com/databricks/LearningSparkV2/blob/master/databricks-datasets/learning-spark-v2/sf-fire/sf-fire-calls.csv```

In [26]:
from pyspark.sql import SparkSession

# create a pyspark session
spark = SparkSession.builder.appName("ReadCsvGenerateDf").getOrCreate()

# define a csv file path
csv_file_path = "/home/aditya/github/Deep-learning-prerequisite/pyspark/Introduction/dataset"

# read csv and generate a dataFrame out of it
fire_df = spark.read.csv(
    path = csv_file_path,
    header=True,
    inferSchema=True
)

fire_df.show()
spark.stop()

+----------+------+--------------+----------------+----------+----------+--------------------+--------------------+--------------------+----+-------+---------+-----------+----+----------------+--------+-------------+-------+-------------+---------+--------------+--------------------------+----------------------+------------------+--------------------+--------------------+-------------+---------+
|CallNumber|UnitID|IncidentNumber|        CallType|  CallDate| WatchDate|CallFinalDisposition|       AvailableDtTm|             Address|City|Zipcode|Battalion|StationArea| Box|OriginalPriority|Priority|FinalPriority|ALSUnit|CallTypeGroup|NumAlarms|      UnitType|UnitSequenceInCallDispatch|FirePreventionDistrict|SupervisorDistrict|        Neighborhood|            Location|        RowID|    Delay|
+----------+------+--------------+----------------+----------+----------+--------------------+--------------------+--------------------+----+-------+---------+-----------+----+----------------+--------+-------------+-------+-------------+---------+--------------+--------------------------+----------------------+------------------+--------------------+--------------------+-------------+---------+
|  20110016|   T13|       2003235|  Structure Fire|01/11/2002|01/10/2002|               Other|01/11/2002 01:51:...|2000 Block of CAL...|  SF|  94109|      B04|         38|3362|               3|       3|            3|  false|         NULL|        1|         TRUCK|                         2|                     4|                 5|     Pacific Heights|(37.7895840679362...|020110016-T13|     2.95|
|  20110022|   M17|       2003241|Medical Incident|01/11/2002|01/10/2002|               Other|01/11/2002 03:01:...|0 Block of SILVER...|  SF|  94124|      B10|         42|6495|               3|       3|            3|   true|         NULL|        1|         MEDIC|                         1|                    10|                10|Bayview Hunters P...|(37.7337623673897...|020110022-M17|      4.7|
|  20110023|   M41|       2003242|Medical Incident|01/11/2002|01/10/2002|               Other|01/11/2002 02:39:...|MARKET ST/MCALLIS...|  SF|  94102|      B03|         01|1455|               3|       3|            3|   true|         NULL|        1|         MEDIC|                         2|                     3|                 6|          Tenderloin|(37.7811772186856...|020110023-M41|2.4333334|
|  20110032|   E11|       2003250|    Vehicle Fire|01/11/2002|01/10/2002|               Other|01/11/2002 04:16:...|APPLETON AV/MISSI...|  SF|  94110|      B06|         32|5626|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     6|                 9|      Bernal Heights|(37.7388432849018...|020110032-E11|      1.5|
|  20110043|   B04|       2003259|          Alarms|01/11/2002|01/10/2002|               Other|01/11/2002 06:01:...|1400 Block of SUT...|  SF|  94109|      B04|         03|3223|               3|       3|            3|  false|         NULL|        1|         CHIEF|                         2|                     4|                 2|    Western Addition|(37.7872890372638...|020110043-B04|3.4833333|
|  20110072|   T08|       2003279|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 08:03:...|  BEALE ST/FOLSOM ST|  SF|  94105|      B03|         35|2122|               3|       3|            3|  false|         NULL|        1|         TRUCK|                         2|                     3|                 6|Financial Distric...|(37.7886866619654...|020110072-T08|     1.75|
|  20110125|   E33|       2003301|          Alarms|01/11/2002|01/11/2002|               Other|01/11/2002 09:46:...|0 Block of FARALL...|  SF|  94112|      B09|         33|8324|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         2|                     9|                11|Oceanview/Merced/...|(37.7140353531157...|020110125-E33|2.7166667|
|  20110130|   E36|       2003304|          Alarms|01/11/2002|01/11/2002|               Other|01/11/2002 09:58:...|600 Block of POLK ST|  SF|  94102|      B02|         03|3114|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     2|                 6|          Tenderloin|(37.7826266328595...|020110130-E36|1.7833333|
|  20110197|   E05|       2003343|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 12:06:...|1500 Block of WEB...|  SF|  94115|      B04|         05|3513|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     4|                 5|           Japantown|(37.784958590666,...|020110197-E05|1.5166667|
|  20110215|   E06|       2003348|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 01:08:...|DIAMOND ST/MARKET ST|  SF|  94114|      B05|         06|5415|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     5|                 8| Castro/Upper Market|(37.7618954753708...|020110215-E06|2.7666667|
|  20110274|   M07|       2003381|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 03:31:...|2700 Block of MIS...|  SF|  94110|      B06|         11|5525|               1|       1|            2|   true|         NULL|        1|         MEDIC|                         1|                     6|                 9|             Mission|(37.7530339738059...|020110274-M07|2.1833334|
|  20110275|   T15|       2003382|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 02:59:...|BRUNSWICK ST/GUTT...|  SF|  94112|      B09|         43|6218|               3|       3|            3|  false|         NULL|        1|         TRUCK|                         1|                     9|                11|           Excelsior|(37.7105545807996...|020110275-T15|      2.5|
|  20110304|   E03|       2003399|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:22:...|1000 Block of SUT...|  SF|  94109|      B04|         03|1557|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     4|                 3|            Nob Hill|(37.7881263034393...|020110304-E03|2.4166667|
|  20110308|   E14|       2003403|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:18:...|100 Block of 21ST...|  SF|  94121|      B07|         14|7173|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     7|                 1|      Outer Richmond|(37.7850084431077...|020110308-E14|     4.95|
|  20110313|   B10|       2003408|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 04:09:...|700 Block of CAPP ST|  SF|  94110|      B06|         07|5472|               3|       3|            3|  false|         NULL|        1|         CHIEF|                         6|                     6|                 9|             Mission|(37.7547064357942...|020110313-B10|1.4166666|
|  20110313|    D3|       2003408|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 04:09:...|700 Block of CAPP ST|  SF|  94110|      B06|         07|5472|               3|       3|            3|  false|         NULL|        1|         CHIEF|                         4|                     6|                 9|             Mission|(37.7547064357942...| 020110313-D3|2.5333333|
|  20110313|   E32|       2003408|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 04:09:...|700 Block of CAPP ST|  SF|  94110|      B06|         07|5472|               3|       3|            3|   true|         NULL|        1|        ENGINE|                         8|                     6|                 9|             Mission|(37.7547064357942...|020110313-E32|1.8833333|
|  20110315|   RC2|       2003409|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:34:...|200 Block of LAGU...|  SF|  94116|      B08|         20|8635|               3|       3|            3|   true|         NULL|        1|RESCUE CAPTAIN|                         2|                     8|                 7|  West of Twin Peaks|(37.7501117393668...|020110315-RC2|     5.35|
|  20110330|   E14|       2003417|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:51:...|BALBOA ST/PARK PR...|  SF|  94118|      B07|         31|7145|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     7|                 1|      Inner Richmond|(37.7768682293368...|020110330-E14|      2.0|
|  20110330|   M12|       2003417|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:51:...|BALBOA ST/PARK PR...|  SF|  94118|      B07|         31|7145|               3|       3|            3|   true|         NULL|        1|         MEDIC|                         2|                     7|                 1|      Inner Richmond|(37.7768682293368...|020110330-M12|1.8166667|
+----------+------+--------------+----------------+----------+----------+--------------------+--------------------+--------------------+----+-------+---------+-----------+----+----------------+--------+-------------+-------+-------------+---------+--------------+--------------------------+----------------------+------------------+--------------------+--------------------+-------------+---------+
only showing top 20 rows

### Explaination:
- ```inferSchema=True```
    - **Meaning:** Spark will automatically detect data types (like integer, double, string, etc.) for each column by reading a sample of the data.
    - If you leave it False (default): Spark treats all columns as strings (StringType).
- ```header=True```
    - **Meaning:** The first line of your CSV file contains column names, not data.
    - If you set it to False (default): Spark treats the first line as a normal data row.
    - **Effect:** The DataFrame’s column names come from the header row.
- **pyspark** is the Python API for Apache Spark.
It lets you write Spark programs in Python instead of Scala or Java.
- **pyspark.sql** is a module inside PySpark that provides tools for working with structured data — that is, data organized in tables (rows and columns), similar to SQL tables or pandas DataFrames.
- **SparkSession** is the entry point to Spark SQL functionality.
    - It’s an object that lets you:
        - Create DataFrames (distributed datasets similar to pandas DataFrames).
        - Run SQL queries on data.
        - Read data from various sources (CSV, JSON, Parquet, Hive, etc.).
        - Manage Spark configurations and contexts.
- ```spark``` is the SparkSession object.

In [40]:
# ****  USE THIS METHOD ALWAYS TO LOAD DATA IN SPARK ****
# import pandas and numpy
import pandas as pd
import numpy as np

# import SparkSession
from pyspark.sql import SparkSession

# import pandas apis implemented on spark 
import pyspark.pandas as pd

# create a pyspark session
spark = SparkSession.builder.appName("ReadCsvGenerateDf").getOrCreate()


first_df = spark.read.format("csv")\
    .option("header","true")\
    .option("inferSchema","true")\
    .load("/home/aditya/github/Deep-learning-prerequisite/pyspark/Introduction/dataset")

first_df.show()

25/10/16 17:22:16 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

+----------+------+--------------+----------------+----------+----------+--------------------+--------------------+--------------------+----+-------+---------+-----------+----+----------------+--------+-------------+-------+-------------+---------+--------------+--------------------------+----------------------+------------------+--------------------+--------------------+-------------+---------+
|CallNumber|UnitID|IncidentNumber|        CallType|  CallDate| WatchDate|CallFinalDisposition|       AvailableDtTm|             Address|City|Zipcode|Battalion|StationArea| Box|OriginalPriority|Priority|FinalPriority|ALSUnit|CallTypeGroup|NumAlarms|      UnitType|UnitSequenceInCallDispatch|FirePreventionDistrict|SupervisorDistrict|        Neighborhood|            Location|        RowID|    Delay|
+----------+------+--------------+----------------+----------+----------+--------------------+--------------------+--------------------+----+-------+---------+-----------+----+----------------+--------+-------------+-------+-------------+---------+--------------+--------------------------+----------------------+------------------+--------------------+--------------------+-------------+---------+
|  20110016|   T13|       2003235|  Structure Fire|01/11/2002|01/10/2002|               Other|01/11/2002 01:51:...|2000 Block of CAL...|  SF|  94109|      B04|         38|3362|               3|       3|            3|  false|         NULL|        1|         TRUCK|                         2|                     4|                 5|     Pacific Heights|(37.7895840679362...|020110016-T13|     2.95|
|  20110022|   M17|       2003241|Medical Incident|01/11/2002|01/10/2002|               Other|01/11/2002 03:01:...|0 Block of SILVER...|  SF|  94124|      B10|         42|6495|               3|       3|            3|   true|         NULL|        1|         MEDIC|                         1|                    10|                10|Bayview Hunters P...|(37.7337623673897...|020110022-M17|      4.7|
|  20110023|   M41|       2003242|Medical Incident|01/11/2002|01/10/2002|               Other|01/11/2002 02:39:...|MARKET ST/MCALLIS...|  SF|  94102|      B03|         01|1455|               3|       3|            3|   true|         NULL|        1|         MEDIC|                         2|                     3|                 6|          Tenderloin|(37.7811772186856...|020110023-M41|2.4333334|
|  20110032|   E11|       2003250|    Vehicle Fire|01/11/2002|01/10/2002|               Other|01/11/2002 04:16:...|APPLETON AV/MISSI...|  SF|  94110|      B06|         32|5626|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     6|                 9|      Bernal Heights|(37.7388432849018...|020110032-E11|      1.5|
|  20110043|   B04|       2003259|          Alarms|01/11/2002|01/10/2002|               Other|01/11/2002 06:01:...|1400 Block of SUT...|  SF|  94109|      B04|         03|3223|               3|       3|            3|  false|         NULL|        1|         CHIEF|                         2|                     4|                 2|    Western Addition|(37.7872890372638...|020110043-B04|3.4833333|
|  20110072|   T08|       2003279|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 08:03:...|  BEALE ST/FOLSOM ST|  SF|  94105|      B03|         35|2122|               3|       3|            3|  false|         NULL|        1|         TRUCK|                         2|                     3|                 6|Financial Distric...|(37.7886866619654...|020110072-T08|     1.75|
|  20110125|   E33|       2003301|          Alarms|01/11/2002|01/11/2002|               Other|01/11/2002 09:46:...|0 Block of FARALL...|  SF|  94112|      B09|         33|8324|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         2|                     9|                11|Oceanview/Merced/...|(37.7140353531157...|020110125-E33|2.7166667|
|  20110130|   E36|       2003304|          Alarms|01/11/2002|01/11/2002|               Other|01/11/2002 09:58:...|600 Block of POLK ST|  SF|  94102|      B02|         03|3114|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     2|                 6|          Tenderloin|(37.7826266328595...|020110130-E36|1.7833333|
|  20110197|   E05|       2003343|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 12:06:...|1500 Block of WEB...|  SF|  94115|      B04|         05|3513|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     4|                 5|           Japantown|(37.784958590666,...|020110197-E05|1.5166667|
|  20110215|   E06|       2003348|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 01:08:...|DIAMOND ST/MARKET ST|  SF|  94114|      B05|         06|5415|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     5|                 8| Castro/Upper Market|(37.7618954753708...|020110215-E06|2.7666667|
|  20110274|   M07|       2003381|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 03:31:...|2700 Block of MIS...|  SF|  94110|      B06|         11|5525|               1|       1|            2|   true|         NULL|        1|         MEDIC|                         1|                     6|                 9|             Mission|(37.7530339738059...|020110274-M07|2.1833334|
|  20110275|   T15|       2003382|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 02:59:...|BRUNSWICK ST/GUTT...|  SF|  94112|      B09|         43|6218|               3|       3|            3|  false|         NULL|        1|         TRUCK|                         1|                     9|                11|           Excelsior|(37.7105545807996...|020110275-T15|      2.5|
|  20110304|   E03|       2003399|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:22:...|1000 Block of SUT...|  SF|  94109|      B04|         03|1557|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     4|                 3|            Nob Hill|(37.7881263034393...|020110304-E03|2.4166667|
|  20110308|   E14|       2003403|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:18:...|100 Block of 21ST...|  SF|  94121|      B07|         14|7173|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     7|                 1|      Outer Richmond|(37.7850084431077...|020110308-E14|     4.95|
|  20110313|   B10|       2003408|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 04:09:...|700 Block of CAPP ST|  SF|  94110|      B06|         07|5472|               3|       3|            3|  false|         NULL|        1|         CHIEF|                         6|                     6|                 9|             Mission|(37.7547064357942...|020110313-B10|1.4166666|
|  20110313|    D3|       2003408|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 04:09:...|700 Block of CAPP ST|  SF|  94110|      B06|         07|5472|               3|       3|            3|  false|         NULL|        1|         CHIEF|                         4|                     6|                 9|             Mission|(37.7547064357942...| 020110313-D3|2.5333333|
|  20110313|   E32|       2003408|  Structure Fire|01/11/2002|01/11/2002|               Other|01/11/2002 04:09:...|700 Block of CAPP ST|  SF|  94110|      B06|         07|5472|               3|       3|            3|   true|         NULL|        1|        ENGINE|                         8|                     6|                 9|             Mission|(37.7547064357942...|020110313-E32|1.8833333|
|  20110315|   RC2|       2003409|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:34:...|200 Block of LAGU...|  SF|  94116|      B08|         20|8635|               3|       3|            3|   true|         NULL|        1|RESCUE CAPTAIN|                         2|                     8|                 7|  West of Twin Peaks|(37.7501117393668...|020110315-RC2|     5.35|
|  20110330|   E14|       2003417|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:51:...|BALBOA ST/PARK PR...|  SF|  94118|      B07|         31|7145|               3|       3|            3|  false|         NULL|        1|        ENGINE|                         1|                     7|                 1|      Inner Richmond|(37.7768682293368...|020110330-E14|      2.0|
|  20110330|   M12|       2003417|Medical Incident|01/11/2002|01/11/2002|               Other|01/11/2002 04:51:...|BALBOA ST/PARK PR...|  SF|  94118|      B07|         31|7145|               3|       3|            3|   true|         NULL|        1|         MEDIC|                         2|                     7|                 1|      Inner Richmond|(37.7768682293368...|020110330-M12|1.8166667|
+----------+------+--------------+----------------+----------+----------+--------------------+--------------------+--------------------+----+-------+---------+-----------+----+----------------+--------+-------------+-------+-------------+---------+--------------+--------------------------+----------------------+------------------+--------------------+--------------------+-------------+---------+
only showing top 20 rows

### Explaination
- ```spark.read```
    - This creates a DataFrameReader object from your SparkSession.
It’s the entry point for reading external data into Spark.
    - Spark can read from:
        - CSV, JSON, Parquet, ORC, AVRO
    - Databases (via JDBC)
        - HDFS, S3, local filesystem, etc.
- ```.format("csv")```
    - This tells Spark what kind of file it’s about to read — in this case, a CSV file.
You could also specify "json", "parquet", etc.
    - Internally, Spark uses a built-in CSV data source that can read large CSVs in parallel.
- ```.option("header", "true")```
    - This tells Spark that the first line of the CSV file contains column names (headers).
    - Without this, Spark would name the columns automatically as _c0, _c1, _c2, etc.
- ```.option("inferSchema", "true")```
    - By default, Spark treats all data as strings.
Setting inferSchema=True makes Spark scan the data and automatically detect the right data types — like Integer, Double, Date, etc.
- ```.load("/home/aditya/github/Deep-learning-prerequisite/pyspark/Introduction/dataset")```
    - This is the path to your CSV file(s).
    - You can point to:
        - A single CSV file: /path/to/file.csv
        - A folder containing multiple CSVs: /path/to/folder/

Spark will read all CSV files inside that folder and combine them into one DataFrame automatically (as long as they have the same structure).

### There are two methods of creating a dataFrame after reading a csv file
This is a shorcut method : 
```python
    fire_df = spark.read.csv(
        path = csv_file_path,
        header=True,
        inferSchema=True
    )
```
This is a Long form method : 
```python
    first_df = spark.read.format("csv").option("header","true").option("inferSchema","true").load("/home/aditya/github/Deep-learning-prerequisite/pyspark/Introduction/dataset")
```

The Long form method should always be used instead of using a shortcut methods because we can use the Long form methods to read all the file types without making any changes in the code only the input parameters will be changed as per the file type example ("csv", "xlxs", "json", etc...).
This Long form method is standardized.

In [64]:
# Turn off spark's ANSI mode
spark.conf.set("spark.sql.ansi.enabled", "false")

first_pandas_df = first_df.pandas_api()
first_pandas_df.head(20)

   CallNumber UnitID  IncidentNumber          CallType    CallDate   WatchDate CallFinalDisposition           AvailableDtTm                         Address City  Zipcode Battalion StationArea   Box OriginalPriority Priority  FinalPriority  ALSUnit CallTypeGroup  NumAlarms        UnitType  UnitSequenceInCallDispatch FirePreventionDistrict SupervisorDistrict                    Neighborhood                               Location          RowID     Delay
0    20110016    T13         2003235    Structure Fire  01/11/2002  01/10/2002                Other  01/11/2002 01:51:44 AM     2000 Block of CALIFORNIA ST   SF    94109       B04          38  3362                3        3              3    False          None          1           TRUCK                           2                      4                  5                 Pacific Heights  (37.7895840679362, -122.428071912459)  020110016-T13  2.950000
1    20110022    M17         2003241  Medical Incident  01/11/2002  01/10/2002                Other  01/11/2002 03:01:18 AM        0 Block of SILVERVIEW DR   SF    94124       B10          42  6495                3        3              3     True          None          1           MEDIC                           1                     10                 10           Bayview Hunters Point  (37.7337623673897, -122.396113802632)  020110022-M17  4.700000
2    20110023    M41         2003242  Medical Incident  01/11/2002  01/10/2002                Other  01/11/2002 02:39:50 AM         MARKET ST/MCALLISTER ST   SF    94102       B03          01  1455                3        3              3     True          None          1           MEDIC                           2                      3                  6                      Tenderloin  (37.7811772186856, -122.411699931232)  020110023-M41  2.433333
3    20110032    E11         2003250      Vehicle Fire  01/11/2002  01/10/2002                Other  01/11/2002 04:16:46 AM          APPLETON AV/MISSION ST   SF    94110       B06          32  5626                3        3              3    False          None          1          ENGINE                           1                      6                  9                  Bernal Heights  (37.7388432849018, -122.423948785199)  020110032-E11  1.500000
4    20110043    B04         2003259            Alarms  01/11/2002  01/10/2002                Other  01/11/2002 06:01:58 AM         1400 Block of SUTTER ST   SF    94109       B04          03  3223                3        3              3    False          None          1           CHIEF                           2                      4                  2                Western Addition  (37.7872890372638, -122.424236212664)  020110043-B04  3.483333
5    20110072    T08         2003279    Structure Fire  01/11/2002  01/11/2002                Other  01/11/2002 08:03:26 AM              BEALE ST/FOLSOM ST   SF    94105       B03          35  2122                3        3              3    False          None          1           TRUCK                           2                      3                  6  Financial District/South Beach  (37.7886866619654, -122.392722833778)  020110072-T08  1.750000
6    20110125    E33         2003301            Alarms  01/11/2002  01/11/2002                Other  01/11/2002 09:46:44 AM        0 Block of FARALLONES ST   SF    94112       B09          33  8324                3        3              3    False          None          1          ENGINE                           2                      9                 11      Oceanview/Merced/Ingleside  (37.7140353531157, -122.454117149916)  020110125-E33  2.716667
7    20110130    E36         2003304            Alarms  01/11/2002  01/11/2002                Other  01/11/2002 09:58:53 AM            600 Block of POLK ST   SF    94102       B02          03  3114                3        3              3    False          None          1          ENGINE                           1                      2                  6                      Tenderloin   (37.7826266328595, -122.41915582123)  020110130-E36  1.783333
8    20110197    E05         2003343  Medical Incident  01/11/2002  01/11/2002                Other  01/11/2002 12:06:57 PM        1500 Block of WEBSTER ST   SF    94115       B04          05  3513                3        3              3    False          None          1          ENGINE                           1                      4                  5                       Japantown   (37.784958590666, -122.431435274503)  020110197-E05  1.516667
9    20110215    E06         2003348  Medical Incident  01/11/2002  01/11/2002                Other  01/11/2002 01:08:40 PM            DIAMOND ST/MARKET ST   SF    94114       B05          06  5415                3        3              3    False          None          1          ENGINE                           1                      5                  8             Castro/Upper Market  (37.7618954753708, -122.437298717721)  020110215-E06  2.766667
10   20110274    M07         2003381  Medical Incident  01/11/2002  01/11/2002                Other  01/11/2002 03:31:02 PM        2700 Block of MISSION ST   SF    94110       B06          11  5525                1        1              2     True          None          1           MEDIC                           1                      6                  9                         Mission  (37.7530339738059, -122.418588598473)  020110274-M07  2.183333
11   20110275    T15         2003382    Structure Fire  01/11/2002  01/11/2002                Other  01/11/2002 02:59:04 PM      BRUNSWICK ST/GUTTENBERG ST   SF    94112       B09          43  6218                3        3              3    False          None          1           TRUCK                           1                      9                 11                       Excelsior  (37.7105545807996, -122.443335369545)  020110275-T15  2.500000
12   20110304    E03         2003399  Medical Incident  01/11/2002  01/11/2002                Other  01/11/2002 04:22:49 PM         1000 Block of SUTTER ST   SF    94109       B04          03  1557                3        3              3    False          None          1          ENGINE                           1                      4                  3                        Nob Hill  (37.7881263034393, -122.417657214041)  020110304-E03  2.416667
13   20110308    E14         2003403  Medical Incident  01/11/2002  01/11/2002                Other  01/11/2002 04:18:33 PM           100 Block of 21ST AVE   SF    94121       B07          14  7173                3        3              3    False          None          1          ENGINE                           1                      7                  1                  Outer Richmond  (37.7850084431077, -122.480723607753)  020110308-E14  4.950000
14   20110313    B10         2003408    Structure Fire  01/11/2002  01/11/2002                Other  01/11/2002 04:09:08 PM            700 Block of CAPP ST   SF    94110       B06          07  5472                3        3              3    False          None          1           CHIEF                           6                      6                  9                         Mission  (37.7547064357942, -122.417513465479)  020110313-B10  1.416667
15   20110313     D3         2003408    Structure Fire  01/11/2002  01/11/2002                Other  01/11/2002 04:09:08 PM            700 Block of CAPP ST   SF    94110       B06          07  5472                3        3              3    False          None          1           CHIEF                           4                      6                  9                         Mission  (37.7547064357942, -122.417513465479)   020110313-D3  2.533333
16   20110313    E32         2003408    Structure Fire  01/11/2002  01/11/2002                Other  01/11/2002 04:09:08 PM            700 Block of CAPP ST   SF    94110       B06          07  5472                3        3              3     True          None          1          ENGINE                           8                      6                  9                         Mission  (37.7547064357942, -122.417513465479)  020110313-E32  1.883333
17   20110315    RC2         2003409  Medical Incident  01/11/2002  01/11/2002                Other  01/11/2002 04:34:23 PM  200 Block of LAGUNA HONDA BLVD   SF    94116       B08          20  8635                3        3              3     True          None          1  RESCUE CAPTAIN                           2                      8                  7              West of Twin Peaks  (37.7501117393668, -122.460819155469)  020110315-RC2  5.350000
18   20110330    E14         2003417  Medical Incident  01/11/2002  01/11/2002                Other  01/11/2002 04:51:31 PM      BALBOA ST/PARK PRESIDIO BL   SF    94118       B07          31  7145                3        3              3    False          None          1          ENGINE                           1                      7                  1                  Inner Richmond  (37.7768682293368, -122.472039541478)  020110330-E14  2.000000
19   20110330    M12         2003417  Medical Incident  01/11/2002  01/11/2002                Other  01/11/2002 04:51:12 PM      BALBOA ST/PARK PRESIDIO BL   SF    94118       B07          31  7145                3        3              3     True          None          1           MEDIC                           2                      7                  1                  Inner Richmond  (37.7768682293368, -122.472039541478)  020110330-M12  1.816667

### Error Handling:
#### ERROR : **[PACKAGE_NOT_INSTALLED] PyArrow >= 11.0.0 must be installed; however, it was not found.**
```
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    File ~/miniconda3/envs/pyspark/lib/python3.13/site-packages/pyspark/sql/pandas/utils.py:69, in require_minimum_pyarrow_version()
        68 try:
    ---> 69     import pyarrow
        71     have_arrow = True

    ModuleNotFoundError: No module named 'pyarrow'

    The above exception was the direct cause of the following exception:

    PySparkImportError                        Traceback (most recent call last)
    Cell In[38], line 1
    ----> 1 first_pandas_df = first_df.pandas_api()
        2 first_pandas_df

    File ~/miniconda3/envs/pyspark/lib/python3.13/site-packages/pyspark/sql/classic/dataframe.py:1758, in DataFrame.pandas_api(self, index_col)
    1755 def pandas_api(
    1756     self, index_col: Optional[Union[str, List[str]]] = None
    1757 ) -> "PandasOnSparkDataFrame":
    -> 1758     from pyspark.pandas.namespace import _get_index_map
    1759     from pyspark.pandas.frame import DataFrame as PandasOnSparkDataFrame
    1760     from pyspark.pandas.internal import InternalFrame

    File ~/miniconda3/envs/pyspark/lib/python3.13/site-packages/pyspark/pandas/__init__.py:34
    ...
        86         messageParameters={
    (...)     90         },
        91     )

    PySparkImportError: [PACKAGE_NOT_INSTALLED] PyArrow >= 11.0.0 must be installed; however, it was not found.
```
You may face this error when trying to convert the dataFrame into a pandas dataframe. This error means that pyarrow module is not installed
#### Solution:
Install 

<br>

#### ERROR : **PANDAS_API_ON_SPARK_FAIL_ON_ANSI_MODE**
You may also encounter the error below: 
```
    ---------------------------------------------------------------------------
    UnsupportedOperationException             Traceback (most recent call last)
    Cell In[39], line 1
    ----> 1 first_pandas_df = first_df.pandas_api()
        2 first_pandas_df

    File ~/miniconda3/envs/pyspark/lib/python3.13/site-packages/pyspark/sql/classic/dataframe.py:1763, in DataFrame.pandas_api(self, index_col)
    1760 from pyspark.pandas.internal import InternalFrame
    1762 index_spark_columns, index_names = _get_index_map(self, index_col)
    -> 1763 internal = InternalFrame(
    1764     spark_frame=self,
    1765     index_spark_columns=index_spark_columns,
    1766     index_names=index_names,  # type: ignore[arg-type]
    1767 )
    1768 return PandasOnSparkDataFrame(internal)

    File ~/miniconda3/envs/pyspark/lib/python3.13/site-packages/pyspark/pandas/internal.py:645, in InternalFrame.__init__(self, spark_frame, index_spark_columns, index_names, index_fields, column_labels, data_spark_columns, data_fields, column_label_names)
        641 spark_frame = InternalFrame.attach_default_index(spark_frame)
        642 index_spark_columns = [scol_for(spark_frame, SPARK_DEFAULT_INDEX_NAME)]
        644 index_fields = [
    --> 645     InternalField.from_struct_field(
        646         StructField(SPARK_DEFAULT_INDEX_NAME, LongType(), nullable=False)
        647     )
        648 ]
        650 if data_spark_columns is not None:
    ...
        502         )

    UnsupportedOperationException: [PANDAS_API_ON_SPARK_FAIL_ON_ANSI_MODE] Pandas API on Spark does not properly work on ANSI mode.
    Please set a Spark config 'spark.sql.ansi.enabled' to `false`.
    Alternatively set a pandas-on-spark option 'compute.fail_on_ansi_mode' to `False` to force it to work, although it can cause unexpected behavior.
```
#### Solution : 
If you try to convert spark's dataFrame into a pandas dataFrame without turning off spark's ANSI mode then you will get this error ```PANDAS_API_ON_SPARK_FAIL_ON_ANSI_MODE```

```python
    first_pandas_df = first_df.pandas_api()
    first_pandas_df
```

You need to turn off the spark's ANSI mode before you try to convert the dataFrame

```python
    # Turn off spark's ANSI mode
    spark.conf.set("spark.sql.ansi.enabled", "false")

    first_pandas_df = first_df.pandas_api()
    first_pandas_df

```

### What is ANSI mode in Spark:
- Spark has a configuration spark.sql.ansi.enabled which, when true, enforces strict SQL behavior for operations like division by zero, invalid type casts, and overflows. This is called ANSI SQL mode.
- Pandas API on Spark conflict: 
    - The pandas_api() function (or pyspark.pandas) does not fully support ANSI mode. That’s because Pandas-on-Spark expects some operations to behave like regular Pandas, which is more lenient than ANSI SQL.

### What is pyspark.pandas?
- We use this library when we want pandas like functionality on top of Spark.

In [65]:
first_pandas_df["Delay"].max()

25/10/16 17:54:56 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header:
 Schema: Delay
Expected: Delay but found:
CSV file: file:///home/aditya/github/Deep-learning-prerequisite/pyspark/Introduction/dataset/=

1844.55

### ```first_pandas_df["Delay"].max()``` won't give you output like what you are used to in a normal pandas.
The reason this is happening is because

In [67]:
first_pandas_df = first_df.toPandas()
first_pandas_df.head(10)

25/10/16 17:55:27 WARN CSVHeaderChecker: Number of column in CSV header is not equal to number of fields in the schema:
 Header length: 1, schema size: 28
CSV file: file:///home/aditya/github/Deep-learning-prerequisite/pyspark/Introduction/dataset/=

,CallNumber,UnitID,IncidentNumber,CallType,CallDate,WatchDate,CallFinalDisposition,AvailableDtTm,Address,City,...,CallTypeGroup,NumAlarms,UnitType,UnitSequenceInCallDispatch,FirePreventionDistrict,SupervisorDistrict,Neighborhood,Location,RowID,Delay
0,20110016,T13,2003235.0,Structure Fire,01/11/2002,01/10/2002,Other,01/11/2002 01:51:44 AM,2000 Block of CALIFORNIA ST,SF,...,None,1.0,TRUCK,2.0,4,5,Pacific Heights,"(37.7895840679362, -122.428071912459)",020110016-T13,2.950000
1,20110022,M17,2003241.0,Medical Incident,01/11/2002,01/10/2002,Other,01/11/2002 03:01:18 AM,0 Block of SILVERVIEW DR,SF,...,None,1.0,MEDIC,1.0,10,10,Bayview Hunters Point,"(37.7337623673897, -122.396113802632)",020110022-M17,4.700000
2,20110023,M41,2003242.0,Medical Incident,01/11/2002,01/10/2002,Other,01/11/2002 02:39:50 AM,MARKET ST/MCALLISTER ST,SF,...,None,1.0,MEDIC,2.0,3,6,Tenderloin,"(37.7811772186856, -122.411699931232)",020110023-M41,2.433333
3,20110032,E11,2003250.0,Vehicle Fire,01/11/2002,01/10/2002,Other,01/11/2002 04:16:46 AM,APPLETON AV/MISSION ST,SF,...,None,1.0,ENGINE,1.0,6,9,Bernal Heights,"(37.7388432849018, -122.423948785199)",020110032-E11,1.500000
4,20110043,B04,2003259.0,Alarms,01/11/2002,01/10/2002,Other,01/11/2002 06:01:58 AM,1400 Block of SUTTER ST,SF,...,None,1.0,CHIEF,2.0,4,2,Western Addition,"(37.7872890372638, -122.424236212664)",020110043-B04,3.483333
5,20110072,T08,2003279.0,Structure Fire,01/11/2002,01/11/2002,Other,01/11/2002 08:03:26 AM,BEALE ST/FOLSOM ST,SF,...,None,1.0,TRUCK,2.0,3,6,Financial District/South Beach,"(37.7886866619654, -122.392722833778)",020110072-T08,1.750000
6,20110125,E33,2003301.0,Alarms,01/11/2002,01/11/2002,Other,01/11/2002 09:46:44 AM,0 Block of FARALLONES ST,SF,...,None,1.0,ENGINE,2.0,9,11,Oceanview/Merced/Ingleside,"(37.7140353531157, -122.454117149916)",020110125-E33,2.716667
7,20110130,E36,2003304.0,Alarms,01/11/2002,01/11/2002,Other,01/11/2002 09:58:53 AM,600 Block of POLK ST,SF,...,None,1.0,ENGINE,1.0,2,6,Tenderloin,"(37.7826266328595, -122.41915582123)",020110130-E36,1.783333
8,20110197,E05,2003343.0,Medical Incident,01/11/2002,01/11/2002,Other,01/11/2002 12:06:57 PM,1500 Block of WEBSTER ST,SF,...,None,1.0,ENGINE,1.0,4,5,Japantown,"(37.784958590666, -122.431435274503)",020110197-E05,1.516667
9,20110215,E06,2003348.0,Medical Incident,01/11/2002,01/11/2002,Other,01/11/2002 01:08:40 PM,DIAMOND ST/MARKET ST,SF,...,None,1.0,ENGINE,1.0,5,8,Castro/Upper Market,"(37.7618954753708, -122.437298717721)",020110215-E06,2.766667

In [68]:
first_pandas_df["Delay"].max()

np.float64(1844.55)