# Pandas

In [1]:
import pandas as pd
# df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv") # for office pc path 
df = pd.read_csv("/home/machine_learning/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv") # for macbook home pc
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

## What is the maximum temperature?

In [2]:
df["Temperature"].max()

50

## On what dates the it rained in the city?

In [3]:
df["EST"][df['Events']=="Rain"]

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

## On what dates it Fog-Snow in the city?

In [4]:
df["EST"][df["Events"]=="Fog-Snow"]

16    1/17/2016
22    1/23/2016
Name: EST, dtype: object

## On what dates it Snowed in the city?

In [5]:
df["EST"][df["Events"]=="Snow"]

17    1/18/2016
21    1/22/2016
23    1/24/2016
Name: EST, dtype: object

## What is my average wind speed?

In [6]:
df["WindSpeedMPH"].mean(axis=0)

6.892857142857143

### Explanation: df["WindSpeedMPH"].mean(axis=0)
- df is a Pandas DataFrame.
- df["WindSpeedMPH"] selects a single column — so you get a Pandas Series.
- .mean(axis=0) computes the mean (average) of the values in that Series.
- axis=0 is optional here and doesn’t affect the result because a Series is 1-dimensional.
### You can read this post in stackoverflow 
https://stackoverflow.com/questions/31037298/pandas-get-column-average-mean

In [7]:
# prove that axis = 0 is not required here
df["WindSpeedMPH"].mean()

6.892857142857143

#### Huh? intresting both the results are the same in case where axis=0 and where axis is not provided in the mean function.

## Operations in dataFrame
- Here is the link to the documentation where all the operations are being mentioned.
- https://pandas.pydata.org/docs/reference/index.html

## Calculating average of Temperature, DewPoint, Humidity, Sea Level PressureIn, VisibilityMiles columns in the data frame.

In [8]:
df[["Temperature", "DewPoint", "Humidity", "Sea Level PressureIn", "VisibilityMiles"]].mean()

Temperature             34.677419
DewPoint                17.838710
Humidity                51.677419
Sea Level PressureIn    29.992903
VisibilityMiles          9.193548
dtype: float64

## Calculate the count of data present in a column in the data frame

In [9]:
df[["Temperature"]].count()

Temperature    31
dtype: int64

## Calculate the count of data in the selected table

In [10]:
df[["Temperature","DewPoint","Humidity"]].mean()

Temperature    34.677419
DewPoint       17.838710
Humidity       51.677419
dtype: float64

## Calculate standard deviation
- Standard Deviation (σ) is a statistical measure that tells you how spread out the values in a dataset are from the mean (average)
- If the values are close to the mean, the standard deviation is small.
- If the values are spread out, the standard deviation is large..
## Why standard deviation is important
- Detecting anomalies and outliers:
  - If a data point is several standard deviation away from the mean, it's likely and outlier.
  - It is used for Fraud detection, quality control, sensor anomalies.
- Comparing performance consistency:
  - Let's say I have to analyze the test score of two students over several exams:
  - Student A has more consistent performance.
  - Student B has higher variability.
  - Useful for: HR appraisals, academic evaluations, product quality
- Risk assesment in Finance:
  - Standar deviation is often used as a measure of risk in investment returns.
  - Higher standard deviation means more unpredictable returns and higher risks.
  - Useful for portfolio management, stock analysis.
- Understanding spread in distributions:
  - You can visualize it using histogram + standard ranges to understand how data clusters around the mean

In [11]:
df["Temperature"].std()

7.639315400279416

## Calculate standard deviation of multiple selected columns

In [12]:
df[["Temperature","DewPoint","Humidity"]].std()

Temperature     7.639315
DewPoint       11.378626
Humidity       11.634395
dtype: float64

## Calculate min

In [13]:
df["Temperature"].min()

20

## Calculate min of multiple selected columns

In [14]:
df[["Temperature","DewPoint","Humidity"]].min()

Temperature    20
DewPoint       -3
Humidity       33
dtype: int64

## Calculate the max

In [15]:
df["Temperature"].max()

50

## Calculate the max of multiple selected columns

In [16]:
df[["Temperature", "DewPoint", "Humidity"]].max()

Temperature    50
DewPoint       46
Humidity       78
dtype: int64

## Calculate the max 25%

In [17]:
df["Temperature"].quantile(0.25)

29.0

## Calculate the max 25% for multiple selected columns

In [18]:
df[["Temperature", "DewPoint", "Humidity"]].quantile(0.25)

Temperature    29.0
DewPoint       10.0
Humidity       44.5
Name: 0.25, dtype: float64

### Explanation: 
- .quantile is a function that takes in a value in decimal and then calculates the percentage of the columns selected in df[]

## To get count,mean,std,min and max all at once in data frame you can use .describe() function

In [19]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

## Data Cleaning 
- The process of cleaning messy data is called data munging or data wrangling.

### Result before data cleaning

In [20]:
df["WindSpeedMPH"].mean()

6.892857142857143

### Result after data cleaning

In [21]:
df.fillna(0, inplace=True)
df["WindSpeedMPH"].mean()

6.225806451612903

### Show Nan in df before cleaning

In [22]:
print(df["WindSpeedMPH"].isna().sum())

0

### Show Nan in df after clearning

In [23]:
df.fillna(0, inplace=True)
print(df["WindSpeedMPH"].isna().sum())

0

## Dataframe is a main object in Pandas it is used to represent data with rows and columns (tabular or excel spreadsheet like data)

In [24]:
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,0,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,0,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,0,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,0,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,0,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,0,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,0,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,0.0,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,0.0,0,1,0,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,0,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,0,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,0,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,0,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,0,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,0,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,0,312
21,1/22/2016,26,6,41,30.21,9,0.0,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,0,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,0,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,0,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,0,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,0,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,0,241

## Create a dataframe using python dictionary

In [25]:
weather_data = {
    "day":["1/1/2017","1/2/2017","1/3/2017","1/4/2017","1/5/2017","1/6/2017"],
    "temperature":[32,35,28,24,32,31],
    "windspeed":[6,7,2,7,4,2],
    "event":["Rain","Sunny","Snow","Snow","Rain","Sunny"]
}
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## Get the shape of the dataframe

In [26]:
df.shape

(6, 4)

## Get all the events in dataframe

In [27]:
df["event"]

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

## Get the type of a column in a df

In [28]:
type(df["event"])

pandas.core.series.Series

### Get the type of a cell data in the event column in a df

In [29]:
type(df["event"][0])

str

## Change the index number from integer number generated by the dataframe to the date present in the EST column of the dataframe.

In [30]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [31]:
df.set_index("day",inplace=True)
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

#### df.loc[...]:
- .loc[...] is used to access a group of rows and columns by labels or boolean array.
- It works with labels, not integer positions.

In [32]:
df.loc["1/4/2017"]

temperature      24
windspeed         7
event          Snow
Name: 1/4/2017, dtype: object

#### df.reset_index(inplace=True):
- reset_index() — creates a new DataFrame with the index reset to the default (0, 1, 2, ...).
- inplace=True — applies the change directly to df, instead of returning a new DataFrame.

In [33]:
df.reset_index(inplace=True)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [34]:
df.set_index("event",inplace=True)
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [35]:
df.loc["Snow"]

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

In [36]:
df.reset_index(inplace=True)
df

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2
3   Snow  1/4/2017           24          7
4   Rain  1/5/2017           32          4
5  Sunny  1/6/2017           31          2

#### df[2:5]:
- df[2:5] will select the rows from 2 to (5-1) i.e 4.

In [37]:
df[2:5]

  event       day  temperature  windspeed
2  Snow  1/3/2017           28          2
3  Snow  1/4/2017           24          7
4  Rain  1/5/2017           32          4

#### Print the columns of a dataframe.

In [38]:
df.columns

Index(['event', 'day', 'temperature', 'windspeed'], dtype='object')

In [39]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [40]:
df.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

## Type of dataframe

In [41]:
type(df["event"])

pandas.core.series.Series

### Only print the columns specified in the code.

In [42]:
df[['day','event','temperature']]

        day  event  temperature
0  1/1/2017   Rain           32
1  1/2/2017  Sunny           35
2  1/3/2017   Snow           28
3  1/4/2017   Snow           24
4  1/5/2017   Rain           32
5  1/6/2017  Sunny           31

### Operations in pandas

#### Greater than and Grater than equal to

In [43]:
df[df.temperature>32]

   event       day  temperature  windspeed
1  Sunny  1/2/2017           35          7

In [44]:
df[df.temperature>=32]

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
4   Rain  1/5/2017           32          4

#### Less than and less than equal to

In [45]:
df[df.temperature < 32]

   event       day  temperature  windspeed
2   Snow  1/3/2017           28          2
3   Snow  1/4/2017           24          7
5  Sunny  1/6/2017           31          2

In [46]:
df[df.temperature <= 32]

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
2   Snow  1/3/2017           28          2
3   Snow  1/4/2017           24          7
4   Rain  1/5/2017           32          4
5  Sunny  1/6/2017           31          2

#### If I want to get the row where temperature was maximum

In [47]:
df[df["temperature"] == df["temperature"].max()]

   event       day  temperature  windspeed
1  Sunny  1/2/2017           35          7

#### If I want to get the row where temperature was minimum

In [48]:
df[df["temperature"] == df["temperature"].min()]

  event       day  temperature  windspeed
3  Snow  1/4/2017           24          7

#### If you want to get the row where temperature is minimum and only choose temperature and day column to be shown in the dataframe.

#### I thought that this method is correct but its not the reason being is
- This is trying to index a Python list with a Pandas Series (a boolean mask).
- ["temperature", "day"] is just a normal Python list.
- I am then trying to index that list with:
  - df["temperature"] == df["temperature"].min() This returns a Pandas series of True/False values one per row.
  - ```
    0    False
    1    False
    2    False
    3     True
    4    False
    5    False
    Name: temperature, dtype: bool
    ```
- ["temperature", "day"][<boolean_series>] because list indices must be integers or slices, not a Pandas series. This is the reason why I got this error in the cell below.

In [49]:
 df[["temperature","day"][df["temperature"]==df["temperature"].min()]] # wrong way

TypeError: list indices must be integers or slices, not Series

In [50]:
df[df["temperature"] == df["temperature"].min()][["temperature", "day"]] # correct way

   temperature       day
3           24  1/4/2017

#### Select the row where windspeed is maximum and only show the day and windspeed column.

In [51]:
df[df["windspeed"] == df["windspeed"].max()][["day","windspeed"]] # correct way

        day  windspeed
1  1/2/2017          7
3  1/4/2017          7