# Methods to clean data

In [4]:
import pandas as pd
df_missing_data = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv")
df_missing_data

       tickers    eps  revenue   price             people
0        Apple    NaN   105.55  113.42           Tim Cook
1    Microsoft   1.59   -42.45  410.99      Satya Nadella
2       Google   3.94   118.78   83.55      Sundar Pichai
3       Amazon    NaN    69.97  494.10         Andy Jassy
4     Facebook    1.3    85.42  397.51    Mark Zuckerberg
5        Tesla    1.3   -69.91  139.42          Elon Musk
6      Netflix   6.74   192.61   52.48      Reed Hastings
7        Intel   n.a.    99.33  416.96      Pat Gelsinger
8          IBM   0.59    47.11  368.09               n.a.
9      Samsung   3.63   141.13  378.05       Jong-Hee Han
10      Oracle   0.61    38.96  397.07         Safra Catz
11       Cisco    0.6   110.44   83.32      Chuck Robbins
12          HP   2.73     2.02  211.31      Enrique Lores
13       Adobe  -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia  -3.17   109.84  438.40       Jensen Huang
15    Qualcomm   0.31   136.92  330.48     Cristiano Amon
16  Salesforce  -1.04   108.57  198.90       Marc Benioff
17     Spotify   2.94    94.22   78.60          Daniel Ek
18        Uber  -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft  -2.24    26.07  196.33       David Risher
20        Snap    6.4      NaN  378.32       Evan Spiegel
21     Dropbox   1.32    76.97  336.90       Drew Houston
22        Zoom    2.2   152.86  449.25          Eric Yuan
23     Twitter  -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   n.a.    11.85  103.82        Alex Chriss

### Here in this dataFrame we can see that the data is a bit messy
- In people and eps columns we have a value n.a.
- In revenue column we have 2 values that are in negative
### We need to clean this mess before we start our analysis
- We need to replace the n.a. with NaN
- We need to replace the -ve values in revenue columns as well because any company's revenue cannot be -ve it will either be zero or less than zero.

## Remove n.a. values when creating dataFrame from a csv file

In [5]:
df_cleaned = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv",na_values=["not available","n.a."])
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59   -42.45  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30   -69.91  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09                NaN
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

#### As you can see all the n.a. values have been replaced with NaN values

## Now lets see how we can remove -ve values from the revenue column

In [6]:
import numpy as np
df_cleaned.loc[df_cleaned["revenue"]<0, "revenue"] = np.nan
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59      NaN  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30      NaN  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09                NaN
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation 
#### .loc[]
- It is label-based indexing. It is used to access a group of rows and columns in a DataFrame by their labels (names) --- not by their integer positions.
- syntax : ```df.loc[row_condition, column_label]```
  - row_condition: A condition or label(s) that tells pandas which rows you want.
  - column_label: The column(s) you want from those selected rows.

## How to replace NaN value in a cell in a dataFrame if a value is known manually
#### Now in the people column we can see that IBM has a NAN value. 
I know that the ceo of IBM is Arvind Krishna and I want to replace the NaN with the actual ceo name in the people column of the dataFrame

In [7]:
df_cleaned.loc[8,"people"] = "Arvind Krishna"
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59      NaN  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30      NaN  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09     Arvind Krishna
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation:
- df_cleaned.loc[8,"people"] = "Arvind Krishna" : Here 8 is the row number and "people" is the column name
- using these two we are locating the cell to be updated and assign a new value into it.

### There is another way to achieve the same result 
What if we replace n.a. value in the people column in the IBM row. But this can be dangerous because what I am about to do will take effect on the entire column.

## Handle n.a. values using a Converter function

In [8]:
# import csv and create a dataFrame
# conver that csv file into xcel sheet
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv")
df_cleaned.to_excel(excel_writer = "test_converter.xlsx", header = True, index=True, index_label = 'Index', startrow=0, startcol=0)

In [9]:
def people_col_converter(cell):
    if cell == "n.a.":
        return "Arvind Krishna"
    else:
        return cell
df_excel = pd.read_excel("test_converter.xlsx",converters = {
     "people" : people_col_converter
})
df_excel

    Index     tickers   eps  revenue   price             people
0       0       Apple   NaN   105.55  113.42           Tim Cook
1       1   Microsoft  1.59      NaN  410.99      Satya Nadella
2       2      Google  3.94   118.78   83.55      Sundar Pichai
3       3      Amazon   NaN    69.97  494.10         Andy Jassy
4       4    Facebook  1.30    85.42  397.51    Mark Zuckerberg
5       5       Tesla  1.30      NaN  139.42          Elon Musk
6       6     Netflix  6.74   192.61   52.48      Reed Hastings
7       7       Intel   NaN    99.33  416.96      Pat Gelsinger
8       8         IBM  0.59    47.11  368.09     Arvind Krishna
9       9     Samsung  3.63   141.13  378.05       Jong-Hee Han
10     10      Oracle  0.61    38.96  397.07         Safra Catz
11     11       Cisco  0.60   110.44   83.32      Chuck Robbins
12     12          HP  2.73     2.02  211.31      Enrique Lores
13     13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14     14      Nvidia -3.17   109.84  438.40       Jensen Huang
15     15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16     16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     17     Spotify  2.94    94.22   78.60          Daniel Ek
18     18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19     19        Lyft -2.24    26.07  196.33       David Risher
20     20        Snap  6.40      NaN  378.32       Evan Spiegel
21     21     Dropbox  1.32    76.97  336.90       Drew Houston
22     22        Zoom  2.20   152.86  449.25          Eric Yuan
23     23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24     24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation:
- people_col_converter function will be called for every single cell in the people column.
- This function will called when creating dataFrame from the excel sheet present in the file system.

# How to handle missing data in pandas

In [73]:
df_missing_val = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_data_missing_values.csv")
type(df_missing_val["date"][0])
df_missing_val

,date,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
0,2023-01-01,-2.9,87.4,11.9,Snow
1,2023-01-02,15.9,56.8,5.4,Snow
2,2023-01-03,22.8,48.7,11.3,NaN
3,2023-01-04,39.4,56.4,12.2,Rain
4,2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...,...
95,2023-04-06,33.0,36.3,4.1,Fog
96,2023-04-07,-4.4,58.1,8.0,Fog
97,2023-04-08,11.8,41.2,13.0,Sunny
98,2023-04-09,14.7,44.4,NaN,Sunny
99,2023-04-10,0.3,48.3,7.7,Rain

#### The column date can have date values in form of string so to be safe we are going to make sure that when we create the datqFrame from a csv file we convert those string values in the date column into a datetime timestamps.
- First we need to convert all the dates in the date column from type string to type date

In [70]:
df_missing_val = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_data_missing_values.csv", parse_dates = ["date"])
type(df_missing_val["date"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [71]:
df_missing_val

,date,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
0,2023-01-01,-2.9,87.4,11.9,Snow
1,2023-01-02,15.9,56.8,5.4,Snow
2,2023-01-03,22.8,48.7,11.3,NaN
3,2023-01-04,39.4,56.4,12.2,Rain
4,2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...,...
95,2023-04-06,33.0,36.3,4.1,Fog
96,2023-04-07,-4.4,58.1,8.0,Fog
97,2023-04-08,11.8,41.2,13.0,Sunny
98,2023-04-09,14.7,44.4,NaN,Sunny
99,2023-04-10,0.3,48.3,7.7,Rain

### Set the date column as an index of the dataFrame instead of the default index

In [72]:
df_missing_val.set_index("date",inplace=True)
df_missing_val

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,NaN
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,NaN,Sunny
2023-04-10,0.3,48.3,7.7,Rain

## Find all the rows with the missing values in the dataFrame

In [14]:
df_missing_val[df_missing_val.isna().any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-03,22.8,48.7,11.3,NaN
2023-01-06,-1.5,12.9,Rain,NaN
2023-01-10,65.2,6.5,Sunny,NaN
2023-01-15,NaN,74.3,8.9,Snow
2023-01-21,18.9,5.5,NaN,NaN
2023-01-22,5.3,32.9,NaN,Rain
2023-01-31,58.3,Fog,NaN,NaN
2023-02-02,5.2,64.0,NaN,Fog
2023-02-04,-2.6,55.1,1.7,NaN
2023-02-06,NaN,64.4,8.7,Sunny
2023-02-20,19.4,NaN,13.2,Rain
2023-02-24,15.4,16.7,11.1,NaN
2023-03-04,20.5,70.9,9.8,NaN
2023-03-08,15.6,NaN,16.3,Rain
2023-03-13,12.7,59.3,NaN,NaN
2023-03-15,NaN,46.6,15.6,Snow
2023-03-16,27.6,NaN,14.3,Cloudy
2023-03-23,NaN,NaN,9.5,Fog
2023-03-24,NaN,63.3,5.7,Cloudy
2023-03-26,18.8,43.3,NaN,Fog
2023-03-28,35.5,NaN,5.9,Sunny
2023-03-29,19.9,71.7,11.2,NaN
2023-04-09,14.7,44.4,NaN,Sunny

### Explanation:
df_missing_val.isna()

    Returns a DataFrame of the same shape where:

        True means the value is missing (NaN)

        False means it's not missing
        
.any(axis=1)

    This is a reduction operation that checks if any value in each row is True.

So what is axis=1?

    axis=1 → operate row-wise

    axis=0 → operate column-wise

### Topics covered 
- fillna to fill missing values using differenbt ways
- interpolate to make a guess on missing values using interpolation
- dropna to drop rows with missing values

### Fillna method to replace NaN values with Zeros in the dataFrame with missing values

In [15]:
new_df_fill_na = df_missing_val.fillna(0)
new_df_fill_na

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,0
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,0,Sunny
2023-04-10,0.3,48.3,7.7,Rain

### Find all the rows that have zero in it in the dataFrame

In [16]:
new_df_fill_na[(new_df_fill_na==0).any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-03,22.8,48.7,11.3,0
2023-01-06,-1.5,12.9,Rain,0
2023-01-10,65.2,6.5,Sunny,0
2023-01-15,0.0,74.3,8.9,Snow
2023-01-21,18.9,5.5,0,0
2023-01-22,5.3,32.9,0,Rain
2023-01-31,58.3,Fog,0,0
2023-02-02,5.2,64.0,0,Fog
2023-02-04,-2.6,55.1,1.7,0
2023-02-06,0.0,64.4,8.7,Sunny
2023-02-20,19.4,0,13.2,Rain
2023-02-24,15.4,16.7,11.1,0
2023-03-04,20.5,70.9,9.8,0
2023-03-08,15.6,0,16.3,Rain
2023-03-13,12.7,59.3,0,0
2023-03-15,0.0,46.6,15.6,Snow
2023-03-16,27.6,0,14.3,Cloudy
2023-03-23,0.0,0,9.5,Fog
2023-03-24,0.0,63.3,5.7,Cloudy
2023-03-26,18.8,43.3,0,Fog
2023-03-28,35.5,0,5.9,Sunny
2023-03-29,19.9,71.7,11.2,0
2023-04-09,14.7,44.4,0,Sunny

### Explanation : 
This method will fill the entire dataFrame with 0 where NaN values were present in the dataFrame

### Sometimes we may want to fillna but we don't want to fill the entire dataFrame with 0. May be we want to specify different values for different columns

In [17]:
new_df = df_missing_val.fillna({
    "temperature_celsius":0,
    "humidity_percent":0,
    "wind_speed_kmph":0,
    "weather_condition":"no event"
})
new_df

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,no event
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,0,Sunny
2023-04-10,0.3,48.3,7.7,Rain

#### Get all the rows where it has data that zero in the dataFrame

In [18]:
new_df[(new_df==0).any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-15,0.0,74.3,8.9,Snow
2023-01-21,18.9,5.5,0,no event
2023-01-22,5.3,32.9,0,Rain
2023-01-31,58.3,Fog,0,no event
2023-02-02,5.2,64.0,0,Fog
2023-02-06,0.0,64.4,8.7,Sunny
2023-02-20,19.4,0,13.2,Rain
2023-03-08,15.6,0,16.3,Rain
2023-03-13,12.7,59.3,0,no event
2023-03-15,0.0,46.6,15.6,Snow
2023-03-16,27.6,0,14.3,Cloudy
2023-03-23,0.0,0,9.5,Fog
2023-03-24,0.0,63.3,5.7,Cloudy
2023-03-26,18.8,43.3,0,Fog
2023-03-28,35.5,0,5.9,Sunny
2023-04-09,14.7,44.4,0,Sunny

#### Get all the rows where it has data "no event"

In [19]:
new_df[(new_df=="no event").any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-03,22.8,48.7,11.3,no event
2023-01-06,-1.5,12.9,Rain,no event
2023-01-10,65.2,6.5,Sunny,no event
2023-01-21,18.9,5.5,0,no event
2023-01-31,58.3,Fog,0,no event
2023-02-04,-2.6,55.1,1.7,no event
2023-02-24,15.4,16.7,11.1,no event
2023-03-04,20.5,70.9,9.8,no event
2023-03-13,12.7,59.3,0,no event
2023-03-29,19.9,71.7,11.2,no event

#### We should avoid replacing zero with NaN
- Reason : If we replace all the NaN values with 0 in columns temperature_celsius, humidity_percent and wind_speed_kmph. Then it will cause issues when we calculate mean in those columns.

#### Another way of getting between estimate is to carry forward the temperature of one row previous of the row where 0 is present.

In [20]:
previous_fill_val_df = df_missing_val.fillna(method="ffill")
previous_fill_val_df

/tmp/ipykernel_685325/3941097953.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  previous_fill_val_df = df_missing_val.fillna(method="ffill")

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,Snow
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,13.0,Sunny
2023-04-10,0.3,48.3,7.7,Rain

### Explanation : 
/tmp/ipykernel_2951661/3941097953.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  previous_fill_val_df = df_missing_val.fillna(method="ffill")  
<br>
Means that using the method="ffill" or method="bfill" inside .fillna() is going to be removed in future versions of pandas.

In [21]:
df_missing_val

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,NaN
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,NaN,Sunny
2023-04-10,0.3,48.3,7.7,Rain

In [22]:
previous_fill_val_df = df_missing_val.ffill()
previous_fill_val_df

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,Snow
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,13.0,Sunny
2023-04-10,0.3,48.3,7.7,Rain

#### Check if there exist any NaN values in any of the rows in the dataFrame

In [23]:
previous_fill_val_df[previous_fill_val_df.isna().any(axis=1)]

Empty DataFrame
Columns: [temperature_celsius, humidity_percent, wind_speed_kmph, weather_condition]
Index: []

#### This confirms that our dataFrame infact has no NaN values in it

#### Another way of getting bettween estimate is to carry forward the temperature of one row next of the row where 0 is present.

In [24]:
df_missing_val

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,NaN
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,NaN,Sunny
2023-04-10,0.3,48.3,7.7,Rain

In [25]:
next_fill_val_df = df_missing_val.bfill()
next_fill_val_df

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,Rain
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,7.7,Sunny
2023-04-10,0.3,48.3,7.7,Rain

#### Lets confirm if there exist any NaN values in the dataFrame

In [26]:
next_fill_val_df[next_fill_val_df.isna().any(axis=1)]

Empty DataFrame
Columns: [temperature_celsius, humidity_percent, wind_speed_kmph, weather_condition]
Index: []

#### Again this confirms that there exists no NaN values in the dataFrame

#### How to limit the number of times a value is allowed to be copied in these two methods 
- Another way of getting between estimate is to carry forward the temperature of one row previous of the row where 0 is present.
- Another way of getting between estimate is to carry forward the temperature of one row next of the row where 0 is present.

In [74]:
df_missing_data.head(10)

     tickers   eps  revenue   price           people
0      Apple   NaN   105.55  113.42         Tim Cook
1  Microsoft  1.59   -42.45  410.99    Satya Nadella
2     Google  3.94   118.78   83.55    Sundar Pichai
3     Amazon   NaN    69.97  494.10       Andy Jassy
4   Facebook   1.3    85.42  397.51  Mark Zuckerberg
5      Tesla   1.3   -69.91  139.42        Elon Musk
6    Netflix  6.74   192.61   52.48    Reed Hastings
7      Intel  n.a.    99.33  416.96    Pat Gelsinger
8        IBM  0.59    47.11  368.09             n.a.
9    Samsung  3.63   141.13  378.05     Jong-Hee Han

#### Setting the limit to 1 
- Here in this case the value will only be allowed to be copied once

In [75]:
copy_once_df = df_missing_val.ffill(limit=1)
copy_once_df.head(10)

,date,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
0,2023-01-01,-2.9,87.4,11.9,Snow
1,2023-01-02,15.9,56.8,5.4,Snow
2,2023-01-03,22.8,48.7,11.3,Snow
3,2023-01-04,39.4,56.4,12.2,Rain
4,2023-01-05,7.8,82.9,7.1,Rain
5,2023-01-06,-1.5,12.9,Rain,Rain
6,2023-01-07,20.4,67.0,7.0,Fog
7,2023-01-08,36.8,83.6,5.7,Cloudy
8,2023-01-09,7.5,79.0,9.4,Sunny
9,2023-01-10,65.2,6.5,Sunny,Sunny

#### Lets check if this ddataFrame has any NaN values in it

In [76]:
copy_once_df[copy_once_df.isna().any(axis=1)]

,date,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
21,2023-01-22,5.3,32.9,NaN,Rain
82,2023-03-24,NaN,63.3,5.7,Cloudy

## Clean data using Interpolation

#### Explanation as to why these methods are a bit restrictive in cases when you are dealing with the values such as temperature
Methods in question
- Another way of getting bettwe estimate is to carry forward the temperature of one row previous of the row where 0 is present.
- Another way of getting bettwe estimate is to carry forward the temperature of one row next of the row where 0 is present.
<br>
Suppose there on the day 1 we have a temperature -2.9 degrees then on day 2 the df has a NaN value and on day 3 the df has 14 degree temperature
<br>
Case 1 : Another way of getting bettwe estimate is to carry forward the temperature of one row previous of the row where 0 is present. <br>
day 1 --> -2.9 <br>
day 2 --> -2.9 <br>
day 3 --> 14 <br>
<br>
Case 2 : Another way of getting bettwe estimate is to carry forward the temperature of one row next of the row where 0 is present. <br>
day 1 --> -2.9 <br>
day 2 --> 14 <br>
day 3 --> 14 <br>

In both the cases the temperature between days 1 to 3 doesn't rise gradually it raises abruptly and then the two consecutive days have the same temperature in real life that's not how it works the temperature rises normally and gradually. So how can we deal with the NaN values in the temperature column or in the dataFrame as a whole?

### What is interpolation ? 
```DataFrame.interpolation()``` is a pandas method used to fill in missing values NaN by estimating or guessing what the values should be, based on surrounding data. <br>
Here is the link to the docs related to this topic : https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.interpolate.html <br>
```DataFrame.interpolate(method='linear', *, axis=0, limit=None, inplace=False, limit_direction=None, limit_area=None, **kwargs)```

In [84]:
interpolated_val_df = df_missing_val.interpolate()
interpolated_val_df.head(10)

/tmp/ipykernel_685325/1733039495.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  interpolated_val_df = df_missing_val.interpolate()

,date,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
0,2023-01-01,-2.9,87.4,11.90,Snow
1,2023-01-02,15.9,56.8,5.40,Snow
2,2023-01-03,22.8,48.7,11.30,NaN
3,2023-01-04,39.4,56.4,12.20,Rain
4,2023-01-05,7.8,82.9,7.10,Rain
5,2023-01-06,-1.5,12.9,7.05,NaN
6,2023-01-07,20.4,67.0,7.00,Fog
7,2023-01-08,36.8,83.6,5.70,Cloudy
8,2023-01-09,7.5,79.0,9.40,Sunny
9,2023-01-10,65.2,6.5,9.30,NaN

### Explanation:
- DataFrame df_missing_val has columns with object dtype (e.g. strings or mixed types).
- interpolate() is meant for numeric columns, and using it on object-type columns is being deprecated.

In [85]:
interpolated_val_df = df_missing_val.select_dtypes(include=["number"]).interpolate()
interpolated_val_df.head(10)

   temperature_celsius  humidity_percent  wind_speed_kmph
0                 -2.9              87.4            11.90
1                 15.9              56.8             5.40
2                 22.8              48.7            11.30
3                 39.4              56.4            12.20
4                  7.8              82.9             7.10
5                 -1.5              12.9             7.05
6                 20.4              67.0             7.00
7                 36.8              83.6             5.70
8                  7.5              79.0             9.40
9                 65.2               6.5             9.30

#### Why its giving me only temperature_celsius column as a result ? 
- Because only temperature is currently recognized as a numeric column (int or float) in the dataFrame
- Hence before I interpolate the dataFrame. I need to change these columns humidity_percent, wind_speed_kmph to numbers type columns so that interpolation can actually work

In [86]:
df_missing_val.head(10)

,date,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
0,2023-01-01,-2.9,87.4,11.9,Snow
1,2023-01-02,15.9,56.8,5.4,Snow
2,2023-01-03,22.8,48.7,11.3,NaN
3,2023-01-04,39.4,56.4,12.2,Rain
4,2023-01-05,7.8,82.9,7.1,Rain
5,2023-01-06,-1.5,12.9,NaN,NaN
6,2023-01-07,20.4,67.0,7.0,Fog
7,2023-01-08,36.8,83.6,5.7,Cloudy
8,2023-01-09,7.5,79.0,9.4,Sunny
9,2023-01-10,65.2,6.5,NaN,NaN

In [87]:
columns_to_convert = ["temperature_celsius", "humidity_percent", "wind_speed_kmph"]
df_missing_val[columns_to_convert] = df_missing_val[columns_to_convert].apply(pd.to_numeric, errors="coerce")
interpolated_val_df = df_missing_val.select_dtypes(include=["number"]).interpolate()
interpolated_val_df.head(10)

   temperature_celsius  humidity_percent  wind_speed_kmph
0                 -2.9              87.4            11.90
1                 15.9              56.8             5.40
2                 22.8              48.7            11.30
3                 39.4              56.4            12.20
4                  7.8              82.9             7.10
5                 -1.5              12.9             7.05
6                 20.4              67.0             7.00
7                 36.8              83.6             5.70
8                  7.5              79.0             9.40
9                 65.2               6.5             9.30

### Explanation:
- ```.apply(pd.to_numeric, errors="coerce")``` 
  - apply(pd.to_numeric) applies the pd.to_numeric() function to each column in the list.

### Lets take another example of interpolation

In [88]:
df_missing_weather_data = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_missing_data_demo.xlsx")
df_missing_weather_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Lets check how many ros has NaN values in them

In [89]:
df_missing_weather_data[df_missing_weather_data.isna().any(axis=1)]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Lets run interpolate function on this dataFrame

In [90]:
# df before interpolation
df_missing_weather_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

In [91]:
inter_polated_df = df_missing_weather_data.interpolate()
inter_polated_df

/tmp/ipykernel_685325/1511323091.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  inter_polated_df = df_missing_weather_data.interpolate()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.00,23,52,30.03,10,8.000000,0,5,NaN,281.0
1,1/2/2016,36.00,18,46,30.02,10,7.000000,0,3,NaN,275.0
2,1/3/2016,40.00,21,47,29.86,10,8.000000,0,1,NaN,277.0
3,1/4/2016,25.00,9,44,30.05,10,9.000000,0,3,NaN,345.0
4,1/5/2016,29.00,-3,41,30.57,10,5.000000,0,0,NaN,333.0
5,1/6/2016,33.00,4,35,30.50,10,4.000000,0,0,NaN,313.0
6,1/7/2016,39.00,11,33,30.28,10,2.000000,0,3,NaN,293.0
7,1/8/2016,39.00,29,64,30.20,10,4.000000,0,8,NaN,79.0
8,1/9/2016,44.00,38,77,30.16,9,8.000000,T,8,Rain,76.0
9,1/10/2016,50.00,46,71,29.59,4,7.333333,1.8,7,Rain,109.0
10,1/11/2016,33.00,8,37,29.92,10,6.666667,0,1,NaN,289.0
11,1/12/2016,35.00,15,53,29.85,10,6.000000,T,4,NaN,235.0
12,1/13/2016,26.00,4,42,29.94,10,10.000000,0,0,NaN,284.0
13,1/14/2016,34.50,12,47,29.95,10,5.000000,T,7,NaN,192.5
14,1/15/2016,43.00,31,62,29.82,9,5.000000,T,2,NaN,101.0
15,1/16/2016,47.00,37,70,29.52,8,7.000000,0.24,7,Rain,340.0
16,1/17/2016,36.00,23,66,29.78,8,6.000000,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.00,6,53,29.83,9,12.000000,T,2,Snow,293.0
18,1/19/2016,22.00,3,42,30.03,10,11.000000,0,1,NaN,297.5
19,1/20/2016,32.00,15,49,30.13,10,6.000000,0,2,NaN,302.0
20,1/21/2016,31.00,11,45,30.15,10,6.000000,0,1,NaN,312.0
21,1/22/2016,26.00,6,41,30.21,9,11.000000,0.01,3,Snow,34.0
22,1/23/2016,30.25,21,78,29.77,1,16.000000,2.31,8,Fog-Snow,42.0
23,1/24/2016,34.50,11,53,29.92,8,6.000000,T,3,Snow,327.0
24,1/25/2016,38.75,18,54,30.25,10,3.000000,0,2,NaN,286.0
25,1/26/2016,43.00,29,56,30.03,10,7.000000,0,2,NaN,280.2
26,1/27/2016,41.00,22,45,30.03,10,7.000000,T,3,Rain,274.4
27,1/28/2016,37.00,20,51,29.90,10,5.000000,0,1,NaN,268.6
28,1/29/2016,36.00,21,50,29.58,10,8.000000,0,4,NaN,262.8
29,1/30/2016,34.00,16,46,30.01,10,7.000000,0,0,NaN,257.0
30,1/31/2016,46.00,28,52,29.90,10,5.000000,0,0,NaN,257.0

#### This warning means that there are some colums contain object-type columns like string, or numbers stored as string
/tmp/ipykernel_2443388/1511323091.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  inter_polated_df = df_missing_weather_data.interpolate()

#### Convert the numbers stored as strings into numbers

In [92]:
# convert the columns into numbers
df_missing_weather_data.infer_objects(copy=False)
# only select those columns whose data-type is of type number and then interpolate it accordingly
interpolated_df = df_missing_weather_data.select_dtypes(include=["number"]).interpolate()
interpolated_df

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
0,38.00,23,52,30.03,10,8.000000,5,281.0
1,36.00,18,46,30.02,10,7.000000,3,275.0
2,40.00,21,47,29.86,10,8.000000,1,277.0
3,25.00,9,44,30.05,10,9.000000,3,345.0
4,29.00,-3,41,30.57,10,5.000000,0,333.0
5,33.00,4,35,30.50,10,4.000000,0,313.0
6,39.00,11,33,30.28,10,2.000000,3,293.0
7,39.00,29,64,30.20,10,4.000000,8,79.0
8,44.00,38,77,30.16,9,8.000000,8,76.0
9,50.00,46,71,29.59,4,7.333333,7,109.0
10,33.00,8,37,29.92,10,6.666667,1,289.0
11,35.00,15,53,29.85,10,6.000000,4,235.0
12,26.00,4,42,29.94,10,10.000000,0,284.0
13,34.50,12,47,29.95,10,5.000000,7,192.5
14,43.00,31,62,29.82,9,5.000000,2,101.0
15,47.00,37,70,29.52,8,7.000000,7,340.0
16,36.00,23,66,29.78,8,6.000000,6,345.0
17,25.00,6,53,29.83,9,12.000000,2,293.0
18,22.00,3,42,30.03,10,11.000000,1,297.5
19,32.00,15,49,30.13,10,6.000000,2,302.0
20,31.00,11,45,30.15,10,6.000000,1,312.0
21,26.00,6,41,30.21,9,11.000000,3,34.0
22,30.25,21,78,29.77,1,16.000000,8,42.0
23,34.50,11,53,29.92,8,6.000000,3,327.0
24,38.75,18,54,30.25,10,3.000000,2,286.0
25,43.00,29,56,30.03,10,7.000000,2,280.2
26,41.00,22,45,30.03,10,7.000000,3,274.4
27,37.00,20,51,29.90,10,5.000000,1,268.6
28,36.00,21,50,29.58,10,8.000000,4,262.8
29,34.00,16,46,30.01,10,7.000000,0,257.0
30,46.00,28,52,29.90,10,5.000000,0,257.0

#### Let's handle dataFrame interpolation using time method
The reason I want to use time method is because our data is dependent on time and time i.e dates. Since we have date column I wanted to use time method. <br>

In [94]:
df_missing_weather_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

In [95]:
time_interpolated_df = df_missing_weather_data.select_dtypes(include=["number"]).interpolate(method="time")
time_interpolated_df

ValueError: time-weighted interpolation only works on Series or DataFrames with a DatetimeIndex

#### Explanation : 
- As you can see here this error occured because our dataFrame doesn't have date column set as its index so inorder to solve this error and for us to use time method for interpolation we will have to set the date column as the index of this dataFrame

#### Setting the date column as an index of the dataFrame

In [40]:
df_missing_weather_data.set_index(df_missing_weather_data["EST"],inplace=True)
df_missing_weather_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,,
1/1/2016,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1/2/2016,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
1/3/2016,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
1/4/2016,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
1/5/2016,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
1/6/2016,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
1/7/2016,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
1/8/2016,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
1/9/2016,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
1/10/2016,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
1/11/2016,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
1/12/2016,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
1/13/2016,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
1/14/2016,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
1/15/2016,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
1/16/2016,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
1/17/2016,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
1/18/2016,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
1/19/2016,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
1/20/2016,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
1/21/2016,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
1/22/2016,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
1/23/2016,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
1/24/2016,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
1/25/2016,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
1/26/2016,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
1/27/2016,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
1/28/2016,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
1/29/2016,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
1/30/2016,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
1/31/2016,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### As you can see that now our date column named EST has been set as the index of this dataFrame now we can move forward with our interpolation operation to remove NaN from the dataFrame

In [41]:
# convert the columns that have numbers in string format into data-types of type number
df_missing_weather_data.infer_objects(copy=False)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,,
1/1/2016,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1/2/2016,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
1/3/2016,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
1/4/2016,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
1/5/2016,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
1/6/2016,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
1/7/2016,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
1/8/2016,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
1/9/2016,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
1/10/2016,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
1/11/2016,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
1/12/2016,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
1/13/2016,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
1/14/2016,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
1/15/2016,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
1/16/2016,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
1/17/2016,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
1/18/2016,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
1/19/2016,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
1/20/2016,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
1/21/2016,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
1/22/2016,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
1/23/2016,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
1/24/2016,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
1/25/2016,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
1/26/2016,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
1/27/2016,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
1/28/2016,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
1/29/2016,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
1/30/2016,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
1/31/2016,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Why are we setting copy = False here ? 
The copy parameter controls whether the method returns a new DataFrame or modifies the original DataFrame in-place. <br>
| `copy` value | What it does                    |
| ------------ | ------------------------------- |
| `True`       | Returns a new DataFrame (copy)  |
| `False`      | Modifies the original DataFrame | 

<br>

You are telling pandas:

    “Please try to convert any object columns to a more specific dtype in-place — do not create a new DataFrame.”

In [42]:
df_missing_weather_data.select_dtypes(include=["number"]).interpolate(method="time")

ValueError: time-weighted interpolation only works on Series or DataFrames with a DatetimeIndex

#### Again I am getting this error ? 
hmmm... Lets check what is the data-type of the EST column in the dataFrame

In [43]:
df_missing_weather_data["EST"].dtype

dtype('O')

#### Explanation : 
In pandas:

    O stands for "object" type.

    This means the column may contain:

        strings

        mixed types (e.g., strings + numbers)

        Python objects (like datetime strings not yet converted)

So, "EST" is currently treated as a general object column — likely string data representing dates/times.

In [44]:
df_missing_weather_data["EST"].apply(lambda x: isinstance(x,str)).all()

True

#### Since it returned True that means all the values present in the EST column is of string datatype.
This means I need to convert all the values in this column into date type before assigning it as an index to this dataFrame

In [45]:
df_missing_weather_data["EST"] = pd.to_datetime(df_missing_weather_data["EST"],format="%m%d%Y",errors="coerce")
df_missing_weather_data["EST"].dtype

dtype('<M8[ns]')

In [46]:
df_missing_weather_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,,
1/1/2016,NaT,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1/2/2016,NaT,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
1/3/2016,NaT,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
1/4/2016,NaT,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
1/5/2016,NaT,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
1/6/2016,NaT,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
1/7/2016,NaT,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
1/8/2016,NaT,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
1/9/2016,NaT,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
1/10/2016,NaT,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
1/11/2016,NaT,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
1/12/2016,NaT,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
1/13/2016,NaT,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
1/14/2016,NaT,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
1/15/2016,NaT,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
1/16/2016,NaT,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
1/17/2016,NaT,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
1/18/2016,NaT,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
1/19/2016,NaT,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
1/20/2016,NaT,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
1/21/2016,NaT,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
1/22/2016,NaT,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
1/23/2016,NaT,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
1/24/2016,NaT,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
1/25/2016,NaT,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
1/26/2016,NaT,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
1/27/2016,NaT,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
1/28/2016,NaT,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
1/29/2016,NaT,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
1/30/2016,NaT,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
1/31/2016,NaT,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

### Why did my string type dates got converted to NaT values in the EST column ?
Explanation : <br>
- Dates in the column ```EST``` is this string format ```1/3/2016```.
- This format corresponds to this ```%m/%d/%Y``` format
- But in my code I accidently did this ```%m%d%Y```
- Which is why I got NaT values in my ESt column of my dataFrame

#### Now I have to fix this

In [47]:
# Lets create a new dataFrame from the excel sheet again 
df_missing_weather_data = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_missing_data_demo.xlsx")
df_missing_weather_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### convert the EST column string type dates into date type dates. This time using this format ```%m/%d/%Y```

In [48]:
df_missing_weather_data["EST"] = pd.to_datetime(df_missing_weather_data["EST"],format = "%m/%d/%Y", errors="coerce")
df_missing_weather_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2016-01-01,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,2016-01-02,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,2016-01-03,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,2016-01-04,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,2016-01-05,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,2016-01-06,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,2016-01-07,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,2016-01-08,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,2016-01-09,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,2016-01-10,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,2016-01-11,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,2016-01-12,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,2016-01-13,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,2016-01-14,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,2016-01-15,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,2016-01-16,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,2016-01-17,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,2016-01-18,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,2016-01-19,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,2016-01-20,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,2016-01-21,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,2016-01-22,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,2016-01-23,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,2016-01-24,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,2016-01-25,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,2016-01-26,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,2016-01-27,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,2016-01-28,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,2016-01-29,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,2016-01-30,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,2016-01-31,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

In [49]:
df_missing_weather_data["EST"].dtype

dtype('<M8[ns]')

#### Now our EST column values have been successfully converted without any issue
#### Explanation
- ```M8``` stands for ```datetime64``` (M is for "datetime" in NumPy's dtype notation).
- ```<``` means little-endian byte order
- ```[ns]``` means the precision in nanoseconds

#### Let's verify if the values in this EST column is of type string or not

In [50]:
df_missing_weather_data["EST"].apply(lambda x: isinstance(x,str)).all()

False

#### Since we are getting the result to be False that means the values stored in EST column is not of type string

#### Since earlier I have created a new dataFrame from the excel sheet I don't have to reset the index in the dataFrame

In [51]:
df_missing_weather_data.set_index(df_missing_weather_data["EST"],inplace=True)
df_missing_weather_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,,
2016-01-01,2016-01-01,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
2016-01-02,2016-01-02,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2016-01-03,2016-01-03,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
2016-01-04,2016-01-04,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
2016-01-05,2016-01-05,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
2016-01-06,2016-01-06,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
2016-01-07,2016-01-07,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
2016-01-08,2016-01-08,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
2016-01-09,2016-01-09,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
2016-01-10,2016-01-10,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,2016-01-11,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
2016-01-12,2016-01-12,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
2016-01-13,2016-01-13,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
2016-01-14,2016-01-14,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
2016-01-15,2016-01-15,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
2016-01-16,2016-01-16,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,2016-01-17,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,2016-01-18,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,2016-01-19,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
2016-01-20,2016-01-20,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
2016-01-21,2016-01-21,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
2016-01-22,2016-01-22,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,2016-01-23,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,2016-01-24,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,2016-01-25,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
2016-01-26,2016-01-26,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
2016-01-27,2016-01-27,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
2016-01-28,2016-01-28,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
2016-01-29,2016-01-29,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
2016-01-30,2016-01-30,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
2016-01-31,2016-01-31,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Now lets run interpolation using time method on the dataFrame

In [52]:
# convert the columns that have numbers in string format into data-types of type number
converted_val_in_df = df_missing_weather_data.infer_objects(copy=False)
# select only those columns which have the values as type of numbers
new_processed_df = converted_val_in_df.select_dtypes(include=["number"]).interpolate(method="time")
new_processed_df

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
EST,,,,,,,,
2016-01-01,38.00,23,52,30.03,10,8.000000,5,281.0
2016-01-02,36.00,18,46,30.02,10,7.000000,3,275.0
2016-01-03,40.00,21,47,29.86,10,8.000000,1,277.0
2016-01-04,25.00,9,44,30.05,10,9.000000,3,345.0
2016-01-05,29.00,-3,41,30.57,10,5.000000,0,333.0
2016-01-06,33.00,4,35,30.50,10,4.000000,0,313.0
2016-01-07,39.00,11,33,30.28,10,2.000000,3,293.0
2016-01-08,39.00,29,64,30.20,10,4.000000,8,79.0
2016-01-09,44.00,38,77,30.16,9,8.000000,8,76.0
2016-01-10,50.00,46,71,29.59,4,7.333333,7,109.0
2016-01-11,33.00,8,37,29.92,10,6.666667,1,289.0
2016-01-12,35.00,15,53,29.85,10,6.000000,4,235.0
2016-01-13,26.00,4,42,29.94,10,10.000000,0,284.0
2016-01-14,34.50,12,47,29.95,10,5.000000,7,192.5
2016-01-15,43.00,31,62,29.82,9,5.000000,2,101.0
2016-01-16,47.00,37,70,29.52,8,7.000000,7,340.0
2016-01-17,36.00,23,66,29.78,8,6.000000,6,345.0
2016-01-18,25.00,6,53,29.83,9,12.000000,2,293.0
2016-01-19,22.00,3,42,30.03,10,11.000000,1,297.5
2016-01-20,32.00,15,49,30.13,10,6.000000,2,302.0
2016-01-21,31.00,11,45,30.15,10,6.000000,1,312.0
2016-01-22,26.00,6,41,30.21,9,11.000000,3,34.0
2016-01-23,30.25,21,78,29.77,1,16.000000,8,42.0
2016-01-24,34.50,11,53,29.92,8,6.000000,3,327.0
2016-01-25,38.75,18,54,30.25,10,3.000000,2,286.0
2016-01-26,43.00,29,56,30.03,10,7.000000,2,280.2
2016-01-27,41.00,22,45,30.03,10,7.000000,3,274.4
2016-01-28,37.00,20,51,29.90,10,5.000000,1,268.6
2016-01-29,36.00,21,50,29.58,10,8.000000,4,262.8
2016-01-30,34.00,16,46,30.01,10,7.000000,0,257.0
2016-01-31,46.00,28,52,29.90,10,5.000000,0,257.0

#### Checking if there are any NaN values present in the dataFrame

In [53]:
new_processed_df[new_processed_df.isna().any(axis=1)]

Empty DataFrame
Columns: [Temperature, DewPoint, Humidity, Sea Level PressureIn, VisibilityMiles, WindSpeedMPH, CloudCover, WindDirDegrees]
Index: []

#### Since there is no NaN values present It is safe to say that the data has been significantly cleaned in this particular dataFrame

## Sometimes there might be situation where I have to drop the rows with n.a. or NaN values

In [54]:
df_missing_values = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_missing_data_demo.xlsx")
df_missing_values

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

In [55]:
df_dropped_NaN = df_missing_values.dropna()
df_dropped_NaN

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0

#### As you can see all the rows containing NaN values have been removed

#### Suppose there is a situation where I have to drop all the rows that have all NaN values.

In [56]:
df_drop_rows_having_all_NaN = df_missing_values.dropna(how="all")
df_drop_rows_having_all_NaN

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### If I want to keep the rows which have atleast one NaN value and drop every other rows.

In [57]:
df_keep_the_row_with_one_NaN_val = df_missing_values.dropna(thresh=1)
df_keep_the_row_with_one_NaN_val

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Now If I change the threshold to 10 then

In [58]:
df_keep_the_row_with_one_NaN_val = df_missing_values.dropna(thresh=10)
df_keep_the_row_with_one_NaN_val

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0

#### Here thresh i.e threshold means the minimum amount of data that a row must have for it to be allowed to be white listed when .dropna() method is ran in pandas. 
- Basically It's saying that :
  - If there are 11 columns in the dataFrame
  - If there is a row where out of 11 columns 10 of them have values in it and 1 of them has a NaN value in it.
  - If ```df.dropna(thresh=10)``` where ```thresh=10``` then what it means is that all the rows that have 1 column with ```NaN``` value and 10 columns with data then It will not be dropped by ```.dropna()``` method. It will be allowed to be remained in the dataFrame after processing
  - All the other rows that do not fit in this rule defined in ```thresh``` will be dropped.

## Insert the missing date in the dataFrame where the date column is set to be the index of the dataFrame
Refer to this docs for more info : https://pandas.pydata.org/docs/reference/api/pandas.date_range.html

#### Set the EST which is essentially a date type column as an index of the dataFrame.
- Convert the EST column from string to date type column
- Then set the EST column as an index to the dataFrame

#### Verify if the EST column has the string type values stored in it

In [59]:
df_missing_values["EST"].apply(lambda x: isinstance (x,str)).all()

True

#### The result of this expression : ```df_missing_values["EST"].apply(lambda x: isinstance (x,str)).all()``` is returning True that means the values in EST column is in string format.

#### Convert the values in the EST column to be from string type to date type

In [60]:
df_missing_values["EST"] = pd.to_datetime(df_missing_values["EST"],format="%m/%d/%Y",errors="coerce")
df_missing_values

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2016-01-01,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,2016-01-02,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,2016-01-03,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,2016-01-04,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,2016-01-05,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,2016-01-06,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,2016-01-07,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,2016-01-08,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,2016-01-09,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,2016-01-10,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,2016-01-11,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,2016-01-12,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,2016-01-13,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,2016-01-14,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,2016-01-15,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,2016-01-16,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,2016-01-17,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,2016-01-18,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,2016-01-19,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,2016-01-20,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,2016-01-21,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,2016-01-22,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,2016-01-23,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,2016-01-24,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,2016-01-25,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,2016-01-26,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,2016-01-27,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,2016-01-28,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,2016-01-29,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,2016-01-30,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,2016-01-31,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Let's check if all the values in the EST column is of type string

In [61]:
df_missing_values["EST"].apply(lambda x: isinstance(x,str)).all()

False

In [62]:
df_missing_values["EST"].dtype

dtype('<M8[ns]')

#### The result is False hence the EST column values are not of type string i.e they have been successfully converted to datetime object in this dataFrame

#### Now we can safely set the EST column as index of this dataFrame

In [63]:
df_missing_values.set_index(df_missing_values["EST"],inplace=True)
df_missing_values

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,,
2016-01-01,2016-01-01,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
2016-01-02,2016-01-02,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2016-01-03,2016-01-03,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
2016-01-04,2016-01-04,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
2016-01-05,2016-01-05,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
2016-01-06,2016-01-06,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
2016-01-07,2016-01-07,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
2016-01-08,2016-01-08,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
2016-01-09,2016-01-09,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
2016-01-10,2016-01-10,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,2016-01-11,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
2016-01-12,2016-01-12,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
2016-01-13,2016-01-13,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
2016-01-14,2016-01-14,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
2016-01-15,2016-01-15,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
2016-01-16,2016-01-16,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,2016-01-17,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,2016-01-18,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,2016-01-19,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
2016-01-20,2016-01-20,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
2016-01-21,2016-01-21,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
2016-01-22,2016-01-22,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,2016-01-23,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,2016-01-24,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,2016-01-25,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
2016-01-26,2016-01-26,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
2016-01-27,2016-01-27,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
2016-01-28,2016-01-28,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
2016-01-29,2016-01-29,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
2016-01-30,2016-01-30,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
2016-01-31,2016-01-31,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Now that the EST column has been set I don't need EST column which makes it redundant

In [64]:
df_EST_index = df_missing_values.drop("EST",axis=1)
df_EST_index

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
2016-01-01,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
2016-01-02,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2016-01-03,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
2016-01-04,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
2016-01-05,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
2016-01-06,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
2016-01-07,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
2016-01-08,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
2016-01-09,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
2016-01-10,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
2016-01-12,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
2016-01-13,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
2016-01-14,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
2016-01-15,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
2016-01-16,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
2016-01-20,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
2016-01-21,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
2016-01-22,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
2016-01-26,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
2016-01-27,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
2016-01-28,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
2016-01-29,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
2016-01-30,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
2016-01-31,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

## Adding missing dates in the dataFrame where EST (date type column) is set as an index in the dataFrame

#### Since I don't have any missing date values in the dataFrame I will manually have to drop the rows from the dataFrame

In [65]:
df_dropped_dates = df_EST_index.drop(df_EST_index.index[["2016-01-03", "2016-01-08"	, "2016-01-09"]])
df_dropped_dates

IndexError: arrays used as indices must be of integer or boolean type

#### Explaination
- ```df_dropped_dates = df_EST_index.drop(df_EST_index.index[["2016-01-03", "2016-01-08", "2016-01-09"]])```
- This causes an error ```because df_EST_index.index[...]``` expects integer or boolean indexing, not string labels like ```"2016-01-03"```.
- ```df_EST_index.index[...]``` is trying to index the index using a list of strings, which is not allowed — it's not integer-based or boolean-based indexing.
- Instead, I was trying to remove rows by label, not by position.
#### solution
- During my search I found out that I can pass those dates strings directly to ```.drop()``` without using ```df_EST_index.index[...].```.
- This works because ```drop``` can take labels (as strings) if the index is of ```datetime64``` type — and Pandas will internally convert your strings to datetimes and match them correctly.

In [66]:
df_dropped_dates = df_EST_index.drop(["2016-01-03", "2016-01-08"	, "2016-01-09"])
df_dropped_dates

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
2016-01-01,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
2016-01-02,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2016-01-04,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
2016-01-05,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
2016-01-06,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
2016-01-07,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
2016-01-10,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
2016-01-12,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
2016-01-13,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
2016-01-14,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
2016-01-15,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
2016-01-16,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
2016-01-20,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
2016-01-21,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
2016-01-22,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
2016-01-26,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
2016-01-27,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
2016-01-28,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
2016-01-29,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
2016-01-30,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
2016-01-31,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Now what I have got the dataFrame that simulates the missing dates that I may get in the real world I can move forward.

#### Adding missing dates in the dataFrame where EST (date type column) is set as an index in the dataFrame

In [67]:
dt = pd.date_range("2016-01-01", "2016-01-31")
idx = pd.DatetimeIndex(dt)
df_dropped_dates.reindex(idx)

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
2016-01-01,38.0,23.0,52.0,30.03,10.0,8.0,0,5.0,NaN,281.0
2016-01-02,36.0,18.0,46.0,30.02,10.0,7.0,0,3.0,NaN,275.0
2016-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-04,25.0,9.0,44.0,30.05,10.0,9.0,0,3.0,NaN,345.0
2016-01-05,NaN,-3.0,41.0,30.57,10.0,5.0,0,0.0,NaN,333.0
2016-01-06,33.0,4.0,35.0,30.50,10.0,4.0,0,0.0,NaN,NaN
2016-01-07,39.0,11.0,33.0,30.28,10.0,2.0,0,3.0,NaN,293.0
2016-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-10,50.0,46.0,71.0,29.59,4.0,NaN,1.8,7.0,Rain,109.0
2016-01-11,33.0,8.0,37.0,29.92,10.0,NaN,0,1.0,NaN,289.0
2016-01-12,35.0,15.0,53.0,29.85,10.0,6.0,T,4.0,NaN,235.0
2016-01-13,26.0,4.0,42.0,29.94,10.0,10.0,0,0.0,NaN,284.0
2016-01-14,NaN,12.0,47.0,29.95,10.0,5.0,T,7.0,NaN,NaN
2016-01-15,43.0,31.0,62.0,29.82,9.0,5.0,T,2.0,NaN,101.0
2016-01-16,47.0,37.0,70.0,29.52,8.0,7.0,0.24,7.0,Rain,340.0
2016-01-17,36.0,23.0,66.0,29.78,8.0,6.0,0.05,6.0,Fog-Snow,345.0
2016-01-18,25.0,6.0,53.0,29.83,9.0,12.0,T,2.0,Snow,293.0
2016-01-19,22.0,3.0,42.0,30.03,10.0,11.0,0,1.0,NaN,NaN
2016-01-20,32.0,15.0,49.0,30.13,10.0,6.0,0,2.0,NaN,302.0
2016-01-21,31.0,11.0,45.0,30.15,10.0,6.0,0,1.0,NaN,312.0
2016-01-22,26.0,6.0,41.0,30.21,9.0,NaN,0.01,3.0,Snow,34.0
2016-01-23,NaN,21.0,78.0,29.77,1.0,16.0,2.31,8.0,Fog-Snow,42.0
2016-01-24,NaN,11.0,53.0,29.92,8.0,6.0,T,3.0,Snow,327.0
2016-01-25,NaN,18.0,54.0,30.25,10.0,3.0,0,2.0,NaN,286.0
2016-01-26,43.0,29.0,56.0,30.03,10.0,7.0,0,2.0,NaN,NaN
2016-01-27,41.0,22.0,45.0,30.03,10.0,7.0,T,3.0,Rain,NaN
2016-01-28,37.0,20.0,51.0,29.90,10.0,5.0,0,1.0,NaN,NaN
2016-01-29,36.0,21.0,50.0,29.58,10.0,8.0,0,4.0,NaN,NaN
2016-01-30,34.0,16.0,46.0,30.01,10.0,7.0,0,0.0,NaN,257.0
2016-01-31,46.0,28.0,52.0,29.90,10.0,5.0,0,0.0,NaN,NaN

#### As you can see that the missing dates have been added in the dataFrame with all the values as NaN

#### Now I will have to use interpolation to fill all the NaN values based on dates using time method

In [68]:
# replace NaN with 0
# convert the string type numbers into integer type numbers 
df_dropped_dates.infer_objects(copy=False)

# only select those columns whose data-type is of type number and then interpolate using time method
df_interpolate_using_time = df_dropped_dates.select_dtypes(include=["number"]).interpolate(method="time",limit_direction="both")
df_interpolate_using_time

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
EST,,,,,,,,
2016-01-01,38.00,23,52,30.03,10,8.0,5,281.0
2016-01-02,36.00,18,46,30.02,10,7.0,3,275.0
2016-01-04,25.00,9,44,30.05,10,9.0,3,345.0
2016-01-05,29.00,-3,41,30.57,10,5.0,0,333.0
2016-01-06,33.00,4,35,30.50,10,4.0,0,313.0
2016-01-07,39.00,11,33,30.28,10,2.0,3,293.0
2016-01-10,50.00,46,71,29.59,4,4.4,7,109.0
2016-01-11,33.00,8,37,29.92,10,5.2,1,289.0
2016-01-12,35.00,15,53,29.85,10,6.0,4,235.0
2016-01-13,26.00,4,42,29.94,10,10.0,0,284.0
2016-01-14,34.50,12,47,29.95,10,5.0,7,192.5
2016-01-15,43.00,31,62,29.82,9,5.0,2,101.0
2016-01-16,47.00,37,70,29.52,8,7.0,7,340.0
2016-01-17,36.00,23,66,29.78,8,6.0,6,345.0
2016-01-18,25.00,6,53,29.83,9,12.0,2,293.0
2016-01-19,22.00,3,42,30.03,10,11.0,1,297.5
2016-01-20,32.00,15,49,30.13,10,6.0,2,302.0
2016-01-21,31.00,11,45,30.15,10,6.0,1,312.0
2016-01-22,26.00,6,41,30.21,9,11.0,3,34.0
2016-01-23,30.25,21,78,29.77,1,16.0,8,42.0
2016-01-24,34.50,11,53,29.92,8,6.0,3,327.0
2016-01-25,38.75,18,54,30.25,10,3.0,2,286.0
2016-01-26,43.00,29,56,30.03,10,7.0,2,280.2
2016-01-27,41.00,22,45,30.03,10,7.0,3,274.4
2016-01-28,37.00,20,51,29.90,10,5.0,1,268.6
2016-01-29,36.00,21,50,29.58,10,8.0,4,262.8
2016-01-30,34.00,16,46,30.01,10,7.0,0,257.0
2016-01-31,46.00,28,52,29.90,10,5.0,0,257.0

### What gives why is interpolation dropping the rows which have NaN values in all of their columns ?
#### Explanation:
- Pandas’ interpolation methods (like "time", "linear", etc.) require at least some non-NaN values to interpolate across.
- If a row has all columns as NaN, pandas has no basis to infer values — so it skips interpolation for that row.

## Handle missing data using Replace function

In [118]:
import numpy as np
import pandas as pd
df_missing_data = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_missing_data_demo.xlsx")
df_missing_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,1/2/2016,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,1/3/2016,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,1/4/2016,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,1/5/2016,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,1/6/2016,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,1/7/2016,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,1/8/2016,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,1/9/2016,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,1/10/2016,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,1/11/2016,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,1/12/2016,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,1/13/2016,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,1/14/2016,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,1/15/2016,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,1/16/2016,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,1/17/2016,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,1/18/2016,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,1/19/2016,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,1/20/2016,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,1/21/2016,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,1/22/2016,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,1/23/2016,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,1/24/2016,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,1/25/2016,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,1/26/2016,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,1/27/2016,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,1/28/2016,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,1/29/2016,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,1/30/2016,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,1/31/2016,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Make EST a date column the index of the dataFrame

#### Lets check if EST is a of string type column

In [119]:
df_missing_data["EST"].apply(lambda x: isinstance(x,str)).all()

True

#### This goes to show that the EST column contains date in string dataType form

#### Convert the EST column values into a datetime type values

In [120]:
df_missing_data["EST"] = pd.to_datetime(df_missing_data["EST"],format="%m/%d/%Y",errors="coerce")
df_missing_data

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2016-01-01,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
1,2016-01-02,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2,2016-01-03,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
3,2016-01-04,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
4,2016-01-05,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
5,2016-01-06,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
6,2016-01-07,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
7,2016-01-08,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
8,2016-01-09,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
9,2016-01-10,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
10,2016-01-11,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
11,2016-01-12,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
12,2016-01-13,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
13,2016-01-14,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
14,2016-01-15,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
15,2016-01-16,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
16,2016-01-17,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
17,2016-01-18,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
18,2016-01-19,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
19,2016-01-20,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
20,2016-01-21,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
21,2016-01-22,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
22,2016-01-23,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
23,2016-01-24,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
24,2016-01-25,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
25,2016-01-26,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
26,2016-01-27,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
27,2016-01-28,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
28,2016-01-29,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
29,2016-01-30,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
30,2016-01-31,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

#### Set the EST as index in the dataFrame

In [121]:
df_missing_data.set_index("EST",inplace=True)
df_missing_data

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
2016-01-01,38.0,23,52,30.03,10,8.0,0,5,NaN,281.0
2016-01-02,36.0,18,46,30.02,10,7.0,0,3,NaN,275.0
2016-01-03,40.0,21,47,29.86,10,8.0,0,1,NaN,277.0
2016-01-04,25.0,9,44,30.05,10,9.0,0,3,NaN,345.0
2016-01-05,NaN,-3,41,30.57,10,5.0,0,0,NaN,333.0
2016-01-06,33.0,4,35,30.50,10,4.0,0,0,NaN,NaN
2016-01-07,39.0,11,33,30.28,10,2.0,0,3,NaN,293.0
2016-01-08,39.0,29,64,30.20,10,4.0,0,8,NaN,79.0
2016-01-09,44.0,38,77,30.16,9,8.0,T,8,Rain,76.0
2016-01-10,50.0,46,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,33.0,8,37,29.92,10,NaN,0,1,NaN,289.0
2016-01-12,35.0,15,53,29.85,10,6.0,T,4,NaN,235.0
2016-01-13,26.0,4,42,29.94,10,10.0,0,0,NaN,284.0
2016-01-14,NaN,12,47,29.95,10,5.0,T,7,NaN,NaN
2016-01-15,43.0,31,62,29.82,9,5.0,T,2,NaN,101.0
2016-01-16,47.0,37,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,36.0,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,25.0,6,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,22.0,3,42,30.03,10,11.0,0,1,NaN,NaN
2016-01-20,32.0,15,49,30.13,10,6.0,0,2,NaN,302.0
2016-01-21,31.0,11,45,30.15,10,6.0,0,1,NaN,312.0
2016-01-22,26.0,6,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,NaN,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,NaN,11,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,NaN,18,54,30.25,10,3.0,0,2,NaN,286.0
2016-01-26,43.0,29,56,30.03,10,7.0,0,2,NaN,NaN
2016-01-27,41.0,22,45,30.03,10,7.0,T,3,Rain,NaN
2016-01-28,37.0,20,51,29.90,10,5.0,0,1,NaN,NaN
2016-01-29,36.0,21,50,29.58,10,8.0,0,4,NaN,NaN
2016-01-30,34.0,16,46,30.01,10,7.0,0,0,NaN,257.0
2016-01-31,46.0,28,52,29.90,10,5.0,0,0,NaN,NaN

## Use replace function to -ve values as NaN in the dataFrame
- This is just to test what replace function does.
- This replace fuction do not make changes in the original dataFrame but It creates a copy of the original dataFrame with changes in it after the operation is complete.

In [122]:
replaced_df=df_missing_data.replace(-3,np.NaN)
replaced_df

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
2016-01-01,38.0,23.0,52,30.03,10,8.0,0,5,NaN,281.0
2016-01-02,36.0,18.0,46,30.02,10,7.0,0,3,NaN,275.0
2016-01-03,40.0,21.0,47,29.86,10,8.0,0,1,NaN,277.0
2016-01-04,25.0,9.0,44,30.05,10,9.0,0,3,NaN,345.0
2016-01-05,NaN,NaN,41,30.57,10,5.0,0,0,NaN,333.0
2016-01-06,33.0,4.0,35,30.50,10,4.0,0,0,NaN,NaN
2016-01-07,39.0,11.0,33,30.28,10,2.0,0,3,NaN,293.0
2016-01-08,39.0,29.0,64,30.20,10,4.0,0,8,NaN,79.0
2016-01-09,44.0,38.0,77,30.16,9,8.0,T,8,Rain,76.0
2016-01-10,50.0,46.0,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,33.0,8.0,37,29.92,10,NaN,0,1,NaN,289.0
2016-01-12,35.0,15.0,53,29.85,10,6.0,T,4,NaN,235.0
2016-01-13,26.0,4.0,42,29.94,10,10.0,0,0,NaN,284.0
2016-01-14,NaN,12.0,47,29.95,10,5.0,T,7,NaN,NaN
2016-01-15,43.0,31.0,62,29.82,9,5.0,T,2,NaN,101.0
2016-01-16,47.0,37.0,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,36.0,23.0,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,25.0,6.0,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,22.0,3.0,42,30.03,10,11.0,0,1,NaN,NaN
2016-01-20,32.0,15.0,49,30.13,10,6.0,0,2,NaN,302.0
2016-01-21,31.0,11.0,45,30.15,10,6.0,0,1,NaN,312.0
2016-01-22,26.0,6.0,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,NaN,21.0,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,NaN,11.0,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,NaN,18.0,54,30.25,10,3.0,0,2,NaN,286.0
2016-01-26,43.0,29.0,56,30.03,10,7.0,0,2,NaN,NaN
2016-01-27,41.0,22.0,45,30.03,10,7.0,T,3,Rain,NaN
2016-01-28,37.0,20.0,51,29.90,10,5.0,0,1,NaN,NaN
2016-01-29,36.0,21.0,50,29.58,10,8.0,0,4,NaN,NaN
2016-01-30,34.0,16.0,46,30.01,10,7.0,0,0,NaN,257.0
2016-01-31,46.0,28.0,52,29.90,10,5.0,0,0,NaN,NaN

#### lets replace NaN values in Events column with 0 using replace function

In [123]:
replaced_df["Events"] = replaced_df["Events"].replace(np.NaN,0)
replaced_df

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
2016-01-01,38.0,23.0,52,30.03,10,8.0,0,5,0,281.0
2016-01-02,36.0,18.0,46,30.02,10,7.0,0,3,0,275.0
2016-01-03,40.0,21.0,47,29.86,10,8.0,0,1,0,277.0
2016-01-04,25.0,9.0,44,30.05,10,9.0,0,3,0,345.0
2016-01-05,NaN,NaN,41,30.57,10,5.0,0,0,0,333.0
2016-01-06,33.0,4.0,35,30.50,10,4.0,0,0,0,NaN
2016-01-07,39.0,11.0,33,30.28,10,2.0,0,3,0,293.0
2016-01-08,39.0,29.0,64,30.20,10,4.0,0,8,0,79.0
2016-01-09,44.0,38.0,77,30.16,9,8.0,T,8,Rain,76.0
2016-01-10,50.0,46.0,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,33.0,8.0,37,29.92,10,NaN,0,1,0,289.0
2016-01-12,35.0,15.0,53,29.85,10,6.0,T,4,0,235.0
2016-01-13,26.0,4.0,42,29.94,10,10.0,0,0,0,284.0
2016-01-14,NaN,12.0,47,29.95,10,5.0,T,7,0,NaN
2016-01-15,43.0,31.0,62,29.82,9,5.0,T,2,0,101.0
2016-01-16,47.0,37.0,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,36.0,23.0,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,25.0,6.0,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,22.0,3.0,42,30.03,10,11.0,0,1,0,NaN
2016-01-20,32.0,15.0,49,30.13,10,6.0,0,2,0,302.0
2016-01-21,31.0,11.0,45,30.15,10,6.0,0,1,0,312.0
2016-01-22,26.0,6.0,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,NaN,21.0,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,NaN,11.0,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,NaN,18.0,54,30.25,10,3.0,0,2,0,286.0
2016-01-26,43.0,29.0,56,30.03,10,7.0,0,2,0,NaN
2016-01-27,41.0,22.0,45,30.03,10,7.0,T,3,Rain,NaN
2016-01-28,37.0,20.0,51,29.90,10,5.0,0,1,0,NaN
2016-01-29,36.0,21.0,50,29.58,10,8.0,0,4,0,NaN
2016-01-30,34.0,16.0,46,30.01,10,7.0,0,0,0,257.0
2016-01-31,46.0,28.0,52,29.90,10,5.0,0,0,0,NaN

#### How to replace values in multiple columns using replace function
- I have chosen ```WindDirDegrees``` column for this demo. Since I have NaN values in it I am going to replace it with negative random number ```-989``` for this demo.

In [124]:
replaced_df["WindDirDegrees"] = replaced_df["WindDirDegrees"].replace(np.NaN,-989)
replaced_df

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
2016-01-01,38.0,23.0,52,30.03,10,8.0,0,5,0,281.0
2016-01-02,36.0,18.0,46,30.02,10,7.0,0,3,0,275.0
2016-01-03,40.0,21.0,47,29.86,10,8.0,0,1,0,277.0
2016-01-04,25.0,9.0,44,30.05,10,9.0,0,3,0,345.0
2016-01-05,NaN,NaN,41,30.57,10,5.0,0,0,0,333.0
2016-01-06,33.0,4.0,35,30.50,10,4.0,0,0,0,-989.0
2016-01-07,39.0,11.0,33,30.28,10,2.0,0,3,0,293.0
2016-01-08,39.0,29.0,64,30.20,10,4.0,0,8,0,79.0
2016-01-09,44.0,38.0,77,30.16,9,8.0,T,8,Rain,76.0
2016-01-10,50.0,46.0,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,33.0,8.0,37,29.92,10,NaN,0,1,0,289.0
2016-01-12,35.0,15.0,53,29.85,10,6.0,T,4,0,235.0
2016-01-13,26.0,4.0,42,29.94,10,10.0,0,0,0,284.0
2016-01-14,NaN,12.0,47,29.95,10,5.0,T,7,0,-989.0
2016-01-15,43.0,31.0,62,29.82,9,5.0,T,2,0,101.0
2016-01-16,47.0,37.0,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,36.0,23.0,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,25.0,6.0,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,22.0,3.0,42,30.03,10,11.0,0,1,0,-989.0
2016-01-20,32.0,15.0,49,30.13,10,6.0,0,2,0,302.0
2016-01-21,31.0,11.0,45,30.15,10,6.0,0,1,0,312.0
2016-01-22,26.0,6.0,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,NaN,21.0,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,NaN,11.0,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,NaN,18.0,54,30.25,10,3.0,0,2,0,286.0
2016-01-26,43.0,29.0,56,30.03,10,7.0,0,2,0,-989.0
2016-01-27,41.0,22.0,45,30.03,10,7.0,T,3,Rain,-989.0
2016-01-28,37.0,20.0,51,29.90,10,5.0,0,1,0,-989.0
2016-01-29,36.0,21.0,50,29.58,10,8.0,0,4,0,-989.0
2016-01-30,34.0,16.0,46,30.01,10,7.0,0,0,0,257.0
2016-01-31,46.0,28.0,52,29.90,10,5.0,0,0,0,-989.0

### Now I can use .replace function with a dictionary to see if I can replace values using this function in multiple columns of the dataFrame

In [125]:
replaced_df = replaced_df.replace({
    "Events" : 0,
    "WindDirDegrees": -989.0
},np.NaN)
replaced_df

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
2016-01-01,38.0,23.0,52,30.03,10,8.0,0,5,NaN,281.0
2016-01-02,36.0,18.0,46,30.02,10,7.0,0,3,NaN,275.0
2016-01-03,40.0,21.0,47,29.86,10,8.0,0,1,NaN,277.0
2016-01-04,25.0,9.0,44,30.05,10,9.0,0,3,NaN,345.0
2016-01-05,NaN,NaN,41,30.57,10,5.0,0,0,NaN,333.0
2016-01-06,33.0,4.0,35,30.50,10,4.0,0,0,NaN,NaN
2016-01-07,39.0,11.0,33,30.28,10,2.0,0,3,NaN,293.0
2016-01-08,39.0,29.0,64,30.20,10,4.0,0,8,NaN,79.0
2016-01-09,44.0,38.0,77,30.16,9,8.0,T,8,Rain,76.0
2016-01-10,50.0,46.0,71,29.59,4,NaN,1.8,7,Rain,109.0
2016-01-11,33.0,8.0,37,29.92,10,NaN,0,1,NaN,289.0
2016-01-12,35.0,15.0,53,29.85,10,6.0,T,4,NaN,235.0
2016-01-13,26.0,4.0,42,29.94,10,10.0,0,0,NaN,284.0
2016-01-14,NaN,12.0,47,29.95,10,5.0,T,7,NaN,NaN
2016-01-15,43.0,31.0,62,29.82,9,5.0,T,2,NaN,101.0
2016-01-16,47.0,37.0,70,29.52,8,7.0,0.24,7,Rain,340.0
2016-01-17,36.0,23.0,66,29.78,8,6.0,0.05,6,Fog-Snow,345.0
2016-01-18,25.0,6.0,53,29.83,9,12.0,T,2,Snow,293.0
2016-01-19,22.0,3.0,42,30.03,10,11.0,0,1,NaN,NaN
2016-01-20,32.0,15.0,49,30.13,10,6.0,0,2,NaN,302.0
2016-01-21,31.0,11.0,45,30.15,10,6.0,0,1,NaN,312.0
2016-01-22,26.0,6.0,41,30.21,9,NaN,0.01,3,Snow,34.0
2016-01-23,NaN,21.0,78,29.77,1,16.0,2.31,8,Fog-Snow,42.0
2016-01-24,NaN,11.0,53,29.92,8,6.0,T,3,Snow,327.0
2016-01-25,NaN,18.0,54,30.25,10,3.0,0,2,NaN,286.0
2016-01-26,43.0,29.0,56,30.03,10,7.0,0,2,NaN,NaN
2016-01-27,41.0,22.0,45,30.03,10,7.0,T,3,Rain,NaN
2016-01-28,37.0,20.0,51,29.90,10,5.0,0,1,NaN,NaN
2016-01-29,36.0,21.0,50,29.58,10,8.0,0,4,NaN,NaN
2016-01-30,34.0,16.0,46,30.01,10,7.0,0,0,NaN,257.0
2016-01-31,46.0,28.0,52,29.90,10,5.0,0,0,NaN,NaN

### Lets perform interpolation using time method just for fun shall we ?

In [131]:
# convert all the values in the columns in numeric type
replaced_df.infer_objects(copy=False)

# perform interpolation using time method on the dataFrame
interpolated_df = replaced_df.select_dtypes(include=["number"]).interpolate(method="time")
interpolated_df

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
EST,,,,,,,,
2016-01-01,38.00,23.0,52,30.03,10,8.000000,5,281.0
2016-01-02,36.00,18.0,46,30.02,10,7.000000,3,275.0
2016-01-03,40.00,21.0,47,29.86,10,8.000000,1,277.0
2016-01-04,25.00,9.0,44,30.05,10,9.000000,3,345.0
2016-01-05,29.00,6.5,41,30.57,10,5.000000,0,333.0
2016-01-06,33.00,4.0,35,30.50,10,4.000000,0,313.0
2016-01-07,39.00,11.0,33,30.28,10,2.000000,3,293.0
2016-01-08,39.00,29.0,64,30.20,10,4.000000,8,79.0
2016-01-09,44.00,38.0,77,30.16,9,8.000000,8,76.0
2016-01-10,50.00,46.0,71,29.59,4,7.333333,7,109.0
2016-01-11,33.00,8.0,37,29.92,10,6.666667,1,289.0
2016-01-12,35.00,15.0,53,29.85,10,6.000000,4,235.0
2016-01-13,26.00,4.0,42,29.94,10,10.000000,0,284.0
2016-01-14,34.50,12.0,47,29.95,10,5.000000,7,192.5
2016-01-15,43.00,31.0,62,29.82,9,5.000000,2,101.0
2016-01-16,47.00,37.0,70,29.52,8,7.000000,7,340.0
2016-01-17,36.00,23.0,66,29.78,8,6.000000,6,345.0
2016-01-18,25.00,6.0,53,29.83,9,12.000000,2,293.0
2016-01-19,22.00,3.0,42,30.03,10,11.000000,1,297.5
2016-01-20,32.00,15.0,49,30.13,10,6.000000,2,302.0
2016-01-21,31.00,11.0,45,30.15,10,6.000000,1,312.0
2016-01-22,26.00,6.0,41,30.21,9,11.000000,3,34.0
2016-01-23,30.25,21.0,78,29.77,1,16.000000,8,42.0
2016-01-24,34.50,11.0,53,29.92,8,6.000000,3,327.0
2016-01-25,38.75,18.0,54,30.25,10,3.000000,2,286.0
2016-01-26,43.00,29.0,56,30.03,10,7.000000,2,280.2
2016-01-27,41.00,22.0,45,30.03,10,7.000000,3,274.4
2016-01-28,37.00,20.0,51,29.90,10,5.000000,1,268.6
2016-01-29,36.00,21.0,50,29.58,10,8.000000,4,262.8
2016-01-30,34.00,16.0,46,30.01,10,7.000000,0,257.0
2016-01-31,46.00,28.0,52,29.90,10,5.000000,0,257.0

In [ ]:
# How to handle data where differnt types of measurement metrics are found in the same column
- Example : 
 Temperature column may have temperature in degree celcius and in Farenhite both

In [ ]:
df_missing_data = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_different_measurement_type_demo.xlsx")
df_missing_data