# Methods to clean data

In [1]:
import pandas as pd
df_missing_data = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv")
df_missing_data

       tickers    eps  revenue   price             people
0        Apple    NaN   105.55  113.42           Tim Cook
1    Microsoft   1.59   -42.45  410.99      Satya Nadella
2       Google   3.94   118.78   83.55      Sundar Pichai
3       Amazon    NaN    69.97  494.10         Andy Jassy
4     Facebook    1.3    85.42  397.51    Mark Zuckerberg
5        Tesla    1.3   -69.91  139.42          Elon Musk
6      Netflix   6.74   192.61   52.48      Reed Hastings
7        Intel   n.a.    99.33  416.96      Pat Gelsinger
8          IBM   0.59    47.11  368.09               n.a.
9      Samsung   3.63   141.13  378.05       Jong-Hee Han
10      Oracle   0.61    38.96  397.07         Safra Catz
11       Cisco    0.6   110.44   83.32      Chuck Robbins
12          HP   2.73     2.02  211.31      Enrique Lores
13       Adobe  -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia  -3.17   109.84  438.40       Jensen Huang
15    Qualcomm   0.31   136.92  330.48     Cristiano Amon
16  Salesforce  -1.04   108.57  198.90       Marc Benioff
17     Spotify   2.94    94.22   78.60          Daniel Ek
18        Uber  -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft  -2.24    26.07  196.33       David Risher
20        Snap    6.4      NaN  378.32       Evan Spiegel
21     Dropbox   1.32    76.97  336.90       Drew Houston
22        Zoom    2.2   152.86  449.25          Eric Yuan
23     Twitter  -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   n.a.    11.85  103.82        Alex Chriss

### Here in this dataFrame we can see that the data is a bit messy
- In people and eps columns we have a value n.a.
- In revenue column we have 2 values that are in negative
### We need to clean this mess before we start our analysis
- We need to replace the n.a. with NaN
- We need to replace the -ve values in revenue columns as well because any company's revenue cannot be -ve it will either be zero or less than zero.

#### First lets see how to remove n.a. from the csv file

In [2]:
df_cleaned = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv",na_values=["not available","n.a."])
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59   -42.45  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30   -69.91  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09                NaN
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

#### As you can see all the n.a. values have been replaced with NaN values

#### Now lets se how we can remove -ve values from the revenue column

In [3]:
import numpy as np
df_cleaned.loc[df_cleaned["revenue"]<0, "revenue"] = np.nan
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59      NaN  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30      NaN  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09                NaN
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation 
#### .loc[]
- It is label-based indexing. It is used to access a group of rows and columns in a DataFrame by their labels (names) --- not by their integer positions.
- syntax : ```df.loc[row_condition, column_label]```
  - row_condition: A condition or label(s) that tells pandas which rows you want.
  - column_label: The column(s) you want from those selected rows.

## Now in the people column we can see that IBM has a NAN value. 
I know that the ceo of IBM is Arvind Krishna and I want to replace the NaN with the actual ceo name in the people column of the dataFrame

In [4]:
df_cleaned.loc[8,"people"] = "Arvind Krishna"
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59      NaN  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30      NaN  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09     Arvind Krishna
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation:
- df_cleaned.loc[8,"people"] = "Arvind Krishna" : Here 8 is the row number and "people" is the column name
- using these two we are locating the cell to be updated and assign a new value into it.

### There is another way to achieve the same result 
What if we replace n.a. value in the people column in the IBM row. But this can be dangerous because what I am about to do will take effect on the entire column.

### Converter demo

In [5]:
# import csv and create a dataFrame
# conver that csv file into xcel sheet
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv")
df_cleaned.to_excel(excel_writer = "test_converter.xlsx", header = True, index=True, index_label = 'Index', startrow=0, startcol=0)

In [6]:
def people_col_converter(cell):
    if cell == "n.a.":
        return "Arvind Krishna"
    else:
        return cell
df_excel = pd.read_excel("test_converter.xlsx",converters = {
     "people" : people_col_converter
})
df_excel

    Index     tickers   eps  revenue   price             people
0       0       Apple   NaN   105.55  113.42           Tim Cook
1       1   Microsoft  1.59      NaN  410.99      Satya Nadella
2       2      Google  3.94   118.78   83.55      Sundar Pichai
3       3      Amazon   NaN    69.97  494.10         Andy Jassy
4       4    Facebook  1.30    85.42  397.51    Mark Zuckerberg
5       5       Tesla  1.30      NaN  139.42          Elon Musk
6       6     Netflix  6.74   192.61   52.48      Reed Hastings
7       7       Intel   NaN    99.33  416.96      Pat Gelsinger
8       8         IBM  0.59    47.11  368.09     Arvind Krishna
9       9     Samsung  3.63   141.13  378.05       Jong-Hee Han
10     10      Oracle  0.61    38.96  397.07         Safra Catz
11     11       Cisco  0.60   110.44   83.32      Chuck Robbins
12     12          HP  2.73     2.02  211.31      Enrique Lores
13     13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14     14      Nvidia -3.17   109.84  438.40       Jensen Huang
15     15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16     16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     17     Spotify  2.94    94.22   78.60          Daniel Ek
18     18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19     19        Lyft -2.24    26.07  196.33       David Risher
20     20        Snap  6.40      NaN  378.32       Evan Spiegel
21     21     Dropbox  1.32    76.97  336.90       Drew Houston
22     22        Zoom  2.20   152.86  449.25          Eric Yuan
23     23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24     24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation:
- people_col_converter function will be called for every single cell in the people column.
- This function will called when creating dataFrame from the excel sheet present in the file system.

# How to handle missing data in pandas

In [28]:
df_missing_val = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_data_missing_values.csv")
type(df_missing_val["date"][0])
df_missing_val

,date,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
0,2023-01-01,-2.9,87.4,11.9,Snow
1,2023-01-02,15.9,56.8,5.4,Snow
2,2023-01-03,22.8,48.7,11.3,NaN
3,2023-01-04,39.4,56.4,12.2,Rain
4,2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...,...
95,2023-04-06,33.0,36.3,4.1,Fog
96,2023-04-07,-4.4,58.1,8.0,Fog
97,2023-04-08,11.8,41.2,13.0,Sunny
98,2023-04-09,14.7,44.4,NaN,Sunny
99,2023-04-10,0.3,48.3,7.7,Rain

#### As you can see that the data in the date column is in string type
- First we need to convert all the dates in the date column from type string to type date

In [29]:
df_missing_val = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather_data_missing_values.csv", parse_dates = ["date"])
type(df_missing_val["date"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [30]:
df_missing_val

,date,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
0,2023-01-01,-2.9,87.4,11.9,Snow
1,2023-01-02,15.9,56.8,5.4,Snow
2,2023-01-03,22.8,48.7,11.3,NaN
3,2023-01-04,39.4,56.4,12.2,Rain
4,2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...,...
95,2023-04-06,33.0,36.3,4.1,Fog
96,2023-04-07,-4.4,58.1,8.0,Fog
97,2023-04-08,11.8,41.2,13.0,Sunny
98,2023-04-09,14.7,44.4,NaN,Sunny
99,2023-04-10,0.3,48.3,7.7,Rain

### Set the date column as an index of the dataFrame instead of the default index

In [10]:
df_missing_val.set_index("date",inplace=True)
df_missing_val

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,NaN
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,NaN,Sunny
2023-04-10,0.3,48.3,7.7,Rain

## Find all the rows with the missing values in the dataFrame

In [11]:
df_missing_val[df_missing_val.isna().any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-03,22.8,48.7,11.3,NaN
2023-01-06,-1.5,12.9,Rain,NaN
2023-01-10,65.2,6.5,Sunny,NaN
2023-01-15,NaN,74.3,8.9,Snow
2023-01-21,18.9,5.5,NaN,NaN
2023-01-22,5.3,32.9,NaN,Rain
2023-01-31,58.3,Fog,NaN,NaN
2023-02-02,5.2,64.0,NaN,Fog
2023-02-04,-2.6,55.1,1.7,NaN
2023-02-06,NaN,64.4,8.7,Sunny
2023-02-20,19.4,NaN,13.2,Rain
2023-02-24,15.4,16.7,11.1,NaN
2023-03-04,20.5,70.9,9.8,NaN
2023-03-08,15.6,NaN,16.3,Rain
2023-03-13,12.7,59.3,NaN,NaN
2023-03-15,NaN,46.6,15.6,Snow
2023-03-16,27.6,NaN,14.3,Cloudy
2023-03-23,NaN,NaN,9.5,Fog
2023-03-24,NaN,63.3,5.7,Cloudy
2023-03-26,18.8,43.3,NaN,Fog
2023-03-28,35.5,NaN,5.9,Sunny
2023-03-29,19.9,71.7,11.2,NaN
2023-04-09,14.7,44.4,NaN,Sunny

### Explanation:
df_missing_val.isna()

    Returns a DataFrame of the same shape where:

        True means the value is missing (NaN)

        False means it's not missing
        
.any(axis=1)

    This is a reduction operation that checks if any value in each row is True.

So what is axis=1?

    axis=1 → operate row-wise

    axis=0 → operate column-wise

### Topics covered 
- fillna to fill missing values using differenbt ways
- interpolate to make a guess on missing values using interpolation
- dropna to drop rows with missing values

### Fillna method to replace NaN values with Zeros in the dataFrame with missing values

In [12]:
new_df_fill_na = df_missing_val.fillna(0)
new_df_fill_na

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,0
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,0,Sunny
2023-04-10,0.3,48.3,7.7,Rain

### Find all the rows that have zero in it in the dataFrame

In [13]:
new_df_fill_na[(new_df_fill_na==0).any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-03,22.8,48.7,11.3,0
2023-01-06,-1.5,12.9,Rain,0
2023-01-10,65.2,6.5,Sunny,0
2023-01-15,0.0,74.3,8.9,Snow
2023-01-21,18.9,5.5,0,0
2023-01-22,5.3,32.9,0,Rain
2023-01-31,58.3,Fog,0,0
2023-02-02,5.2,64.0,0,Fog
2023-02-04,-2.6,55.1,1.7,0
2023-02-06,0.0,64.4,8.7,Sunny
2023-02-20,19.4,0,13.2,Rain
2023-02-24,15.4,16.7,11.1,0
2023-03-04,20.5,70.9,9.8,0
2023-03-08,15.6,0,16.3,Rain
2023-03-13,12.7,59.3,0,0
2023-03-15,0.0,46.6,15.6,Snow
2023-03-16,27.6,0,14.3,Cloudy
2023-03-23,0.0,0,9.5,Fog
2023-03-24,0.0,63.3,5.7,Cloudy
2023-03-26,18.8,43.3,0,Fog
2023-03-28,35.5,0,5.9,Sunny
2023-03-29,19.9,71.7,11.2,0
2023-04-09,14.7,44.4,0,Sunny

### Explanation : 
This method will fill the entire dataFrame with 0 where NaN values were present in the dataFrame

### Sometimes we may want to fillna but we don't want to fill the entire dataFrame with 0. May be we want to specify different values for different columns

In [14]:
new_df = df_missing_val.fillna({
    "temperature_celsius":0,
    "humidity_percent":0,
    "wind_speed_kmph":0,
    "weather_condition":"no event"
})
new_df

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,no event
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,0,Sunny
2023-04-10,0.3,48.3,7.7,Rain

#### Get all the rows where it has data that zero in the dataFrame

In [15]:
new_df[(new_df==0).any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-15,0.0,74.3,8.9,Snow
2023-01-21,18.9,5.5,0,no event
2023-01-22,5.3,32.9,0,Rain
2023-01-31,58.3,Fog,0,no event
2023-02-02,5.2,64.0,0,Fog
2023-02-06,0.0,64.4,8.7,Sunny
2023-02-20,19.4,0,13.2,Rain
2023-03-08,15.6,0,16.3,Rain
2023-03-13,12.7,59.3,0,no event
2023-03-15,0.0,46.6,15.6,Snow
2023-03-16,27.6,0,14.3,Cloudy
2023-03-23,0.0,0,9.5,Fog
2023-03-24,0.0,63.3,5.7,Cloudy
2023-03-26,18.8,43.3,0,Fog
2023-03-28,35.5,0,5.9,Sunny
2023-04-09,14.7,44.4,0,Sunny

#### Get all the rows where it has data "no event"

In [16]:
new_df[(new_df=="no event").any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-03,22.8,48.7,11.3,no event
2023-01-06,-1.5,12.9,Rain,no event
2023-01-10,65.2,6.5,Sunny,no event
2023-01-21,18.9,5.5,0,no event
2023-01-31,58.3,Fog,0,no event
2023-02-04,-2.6,55.1,1.7,no event
2023-02-24,15.4,16.7,11.1,no event
2023-03-04,20.5,70.9,9.8,no event
2023-03-13,12.7,59.3,0,no event
2023-03-29,19.9,71.7,11.2,no event

#### We should avoid replacing zero with NaN
- Reason : If we replace all the NaN values with 0 in columns temperature_celsius, humidity_percent and wind_speed_kmph. Then it will cause issues when we calculate mean in those columns.

#### Another way of getting bettween estimate is to carry forward the temperature of one row previous of the row where 0 is present.

In [17]:
previous_fill_val_df = df_missing_val.fillna(method="ffill")
previous_fill_val_df

/tmp/ipykernel_2443388/3941097953.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  previous_fill_val_df = df_missing_val.fillna(method="ffill")

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,Snow
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,13.0,Sunny
2023-04-10,0.3,48.3,7.7,Rain

### Explanation : 
/tmp/ipykernel_2951661/3941097953.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  previous_fill_val_df = df_missing_val.fillna(method="ffill")  
<br>
Means that using the method="ffill" or method="bfill" inside .fillna() is going to be removed in future versions of pandas.

In [18]:
previous_fill_val_df = df_missing_val.ffill()
previous_fill_val_df

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,Snow
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,13.0,Sunny
2023-04-10,0.3,48.3,7.7,Rain

#### Check if there exist any NaN values in any of the rows in the dataFrame

In [19]:
previous_fill_val_df[previous_fill_val_df.isna().any(axis=1)]

Empty DataFrame
Columns: [temperature_celsius, humidity_percent, wind_speed_kmph, weather_condition]
Index: []

#### This confirms that our dataFrame infact has no NaN values in it

#### Another way of getting bettwe estimate is to carry forward the temperature of one row next of the row where 0 is present.

In [20]:
next_fill_val_df = df_missing_val.bfill()
next_fill_val_df

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,Rain
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
...,...,...,...,...
2023-04-06,33.0,36.3,4.1,Fog
2023-04-07,-4.4,58.1,8.0,Fog
2023-04-08,11.8,41.2,13.0,Sunny
2023-04-09,14.7,44.4,7.7,Sunny
2023-04-10,0.3,48.3,7.7,Rain

#### Lets confirm if there exist any NaN values in the dataFrame

In [21]:
next_fill_val_df[next_fill_val_df.isna().any(axis=1)]

Empty DataFrame
Columns: [temperature_celsius, humidity_percent, wind_speed_kmph, weather_condition]
Index: []

#### Again this confirms that there exists no NaN values in the dataFrame

#### How to limit the number of times a value is allowed to be copied in these two methods 
- Another way of getting bettwe estimate is to carry forward the temperature of one row previous of the row where 0 is present.
- Another way of getting bettwe estimate is to carry forward the temperature of one row next of the row where 0 is present.

In [22]:
df_missing_data.head(10)

     tickers   eps  revenue   price           people
0      Apple   NaN   105.55  113.42         Tim Cook
1  Microsoft  1.59   -42.45  410.99    Satya Nadella
2     Google  3.94   118.78   83.55    Sundar Pichai
3     Amazon   NaN    69.97  494.10       Andy Jassy
4   Facebook   1.3    85.42  397.51  Mark Zuckerberg
5      Tesla   1.3   -69.91  139.42        Elon Musk
6    Netflix  6.74   192.61   52.48    Reed Hastings
7      Intel  n.a.    99.33  416.96    Pat Gelsinger
8        IBM  0.59    47.11  368.09             n.a.
9    Samsung  3.63   141.13  378.05     Jong-Hee Han

#### Setting the limit to 1 
- Here in this case the value will only be allowed to be copied once

In [23]:
copy_once_df = df_missing_val.ffill(limit=1)
copy_once_df.head(10)

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,Snow
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
2023-01-06,-1.5,12.9,Rain,Rain
2023-01-07,20.4,67.0,7.0,Fog
2023-01-08,36.8,83.6,5.7,Cloudy
2023-01-09,7.5,79.0,9.4,Sunny
2023-01-10,65.2,6.5,Sunny,Sunny

#### Lets check if this ddataFrame has any NaN values in it

In [24]:
copy_once_df[copy_once_df.isna().any(axis=1)]

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-22,5.3,32.9,NaN,Rain
2023-03-24,NaN,63.3,5.7,Cloudy

## Interpolate demo

#### Explanation as to why these methods are a bit restrictive in cases when you are dealing with the values such as temperature
Methods in question
- Another way of getting bettwe estimate is to carry forward the temperature of one row previous of the row where 0 is present.
- Another way of getting bettwe estimate is to carry forward the temperature of one row next of the row where 0 is present.
<br>
Suppose there on the day 1 we have a temperature -2.9 degrees then on day 2 the df has a NaN value and on day 3 the df has 14 degree temperature
<br>
Case 1 : Another way of getting bettwe estimate is to carry forward the temperature of one row previous of the row where 0 is present. <br>
day 1 --> -2.9 <br>
day 2 --> -2.9 <br>
day 3 --> 14 <br>
<br>
Case 2 : Another way of getting bettwe estimate is to carry forward the temperature of one row next of the row where 0 is present. <br>
day 1 --> -2.9 <br>
day 2 --> 14 <br>
day 3 --> 14 <br>

In both the cases the temperature between days 1 to 3 doesn't rise gradually it raises abruptly and then the two consecutive days have the same temperature in real life that's not how it works the temperature rises normally and gradually. So how can we deal with the NaN values in the temperature column or in the dataFrame as a whole?

In [25]:
interpolated_val_df = df_missing_val.interpolate()
interpolated_val_df.head(10)

/tmp/ipykernel_2443388/1733039495.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  interpolated_val_df = df_missing_val.interpolate()

,temperature_celsius,humidity_percent,wind_speed_kmph,weather_condition
date,,,,
2023-01-01,-2.9,87.4,11.9,Snow
2023-01-02,15.9,56.8,5.4,Snow
2023-01-03,22.8,48.7,11.3,NaN
2023-01-04,39.4,56.4,12.2,Rain
2023-01-05,7.8,82.9,7.1,Rain
2023-01-06,-1.5,12.9,Rain,NaN
2023-01-07,20.4,67.0,7.0,Fog
2023-01-08,36.8,83.6,5.7,Cloudy
2023-01-09,7.5,79.0,9.4,Sunny
2023-01-10,65.2,6.5,Sunny,NaN

### Explanation:
- DataFrame df_missing_val has columns with object dtype (e.g. strings or mixed types).
- interpolate() is meant for numeric columns, and using it on object-type columns is being deprecated.

In [26]:
interpolated_val_df = df_missing_val.select_dtypes(include=["number"]).interpolate()
interpolated_val_df.head(10)

            temperature_celsius
date
2023-01-01                 -2.9
2023-01-02                 15.9
2023-01-03                 22.8
2023-01-04                 39.4
2023-01-05                  7.8
2023-01-06                 -1.5
2023-01-07                 20.4
2023-01-08                 36.8
2023-01-09                  7.5
2023-01-10                 65.2

#### Why its giving me only temperature_celsius column as a result ? 
- Because only temperature is currently recognized as a numeric column (int or float) in the dataFrame
- Hence before I interpolate the dataFrame. I need to change these columns humidity_percent, wind_speed_kmph to numbers type columns so that interpolation can actually work

In [27]:
columns_to_convert = ["temperature_celsius", "humidity_percent", "wind_speed_kmph"]
df_missing_val[columns_to_convert] = df_missing_val[columns_to_convert].apply(pd.to_numeric, errors="coerce")
interpolated_val_df = df_missing_val.select_dtypes(include=["number"]).interpolate()
interpolated_val_df.head(10)

            temperature_celsius  humidity_percent  wind_speed_kmph
date
2023-01-01                 -2.9              87.4            11.90
2023-01-02                 15.9              56.8             5.40
2023-01-03                 22.8              48.7            11.30
2023-01-04                 39.4              56.4            12.20
2023-01-05                  7.8              82.9             7.10
2023-01-06                 -1.5              12.9             7.05
2023-01-07                 20.4              67.0             7.00
2023-01-08                 36.8              83.6             5.70
2023-01-09                  7.5              79.0             9.40
2023-01-10                 65.2               6.5             9.30

### Explanation:
- ```.apply(pd.to_numeric, errors="coerce")``` 
  - apply(pd.to_numeric) applies the pd.to_numeric() function to each column in the list.