# Methods to clean data

In [15]:
import pandas as pd
df_missing_data = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv")
df_missing_data

       tickers    eps  revenue   price             people
0        Apple    NaN   105.55  113.42           Tim Cook
1    Microsoft   1.59   -42.45  410.99      Satya Nadella
2       Google   3.94   118.78   83.55      Sundar Pichai
3       Amazon    NaN    69.97  494.10         Andy Jassy
4     Facebook    1.3    85.42  397.51    Mark Zuckerberg
5        Tesla    1.3   -69.91  139.42          Elon Musk
6      Netflix   6.74   192.61   52.48      Reed Hastings
7        Intel   n.a.    99.33  416.96      Pat Gelsinger
8          IBM   0.59    47.11  368.09               n.a.
9      Samsung   3.63   141.13  378.05       Jong-Hee Han
10      Oracle   0.61    38.96  397.07         Safra Catz
11       Cisco    0.6   110.44   83.32      Chuck Robbins
12          HP   2.73     2.02  211.31      Enrique Lores
13       Adobe  -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia  -3.17   109.84  438.40       Jensen Huang
15    Qualcomm   0.31   136.92  330.48     Cristiano Amon
16  Salesforce  -1.04   108.57  198.90       Marc Benioff
17     Spotify   2.94    94.22   78.60          Daniel Ek
18        Uber  -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft  -2.24    26.07  196.33       David Risher
20        Snap    6.4      NaN  378.32       Evan Spiegel
21     Dropbox   1.32    76.97  336.90       Drew Houston
22        Zoom    2.2   152.86  449.25          Eric Yuan
23     Twitter  -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   n.a.    11.85  103.82        Alex Chriss

### Here in this dataFrame we can see that the data is a bit messy
- In people and eps columns we have a value n.a.
- In revenue column we have 2 values that are in negative
### We need to clean this mess before we start our analysis
- We need to replace the n.a. with NaN
- We need to replace the -ve values in revenue columns as well because any company's revenue cannot be -ve it will either be zero or less than zero.

#### First lets see how to remove n.a. from the csv file

In [16]:
df_cleaned = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv",na_values=["not available","n.a."])
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59   -42.45  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30   -69.91  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09                NaN
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

#### As you can see all the n.a. values have been replaced with NaN values

#### Now lets se how we can remove -ve values from the revenue column

In [17]:
import numpy as np
df_cleaned.loc[df_cleaned["revenue"]<0, "revenue"] = np.nan
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59      NaN  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30      NaN  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09                NaN
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation 
#### .loc[]
- It is label-based indexing. It is used to access a group of rows and columns in a DataFrame by their labels (names) --- not by their integer positions.
- syntax : ```df.loc[row_condition, column_label]```
  - row_condition: A condition or label(s) that tells pandas which rows you want.
  - column_label: The column(s) you want from those selected rows.

## Now in the people column we can see that IBM has a NAN value. 
I know that the ceo of IBM is Arvind Krishna and I want to replace the NaN with the actual ceo name in the people column of the dataFrame

In [19]:
df_cleaned.loc[8,"people"] = "Arvind Krishna"
df_cleaned

       tickers   eps  revenue   price             people
0        Apple   NaN   105.55  113.42           Tim Cook
1    Microsoft  1.59      NaN  410.99      Satya Nadella
2       Google  3.94   118.78   83.55      Sundar Pichai
3       Amazon   NaN    69.97  494.10         Andy Jassy
4     Facebook  1.30    85.42  397.51    Mark Zuckerberg
5        Tesla  1.30      NaN  139.42          Elon Musk
6      Netflix  6.74   192.61   52.48      Reed Hastings
7        Intel   NaN    99.33  416.96      Pat Gelsinger
8          IBM  0.59    47.11  368.09     Arvind Krishna
9      Samsung  3.63   141.13  378.05       Jong-Hee Han
10      Oracle  0.61    38.96  397.07         Safra Catz
11       Cisco  0.60   110.44   83.32      Chuck Robbins
12          HP  2.73     2.02  211.31      Enrique Lores
13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14      Nvidia -3.17   109.84  438.40       Jensen Huang
15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     Spotify  2.94    94.22   78.60          Daniel Ek
18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19        Lyft -2.24    26.07  196.33       David Risher
20        Snap  6.40      NaN  378.32       Evan Spiegel
21     Dropbox  1.32    76.97  336.90       Drew Houston
22        Zoom  2.20   152.86  449.25          Eric Yuan
23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation:
- df_cleaned.loc[8,"people"] = "Arvind Krishna" : Here 8 is the row number and "people" is the column name
- using these two we are locating the cell to be updated and assign a new value into it.

### There is another way to achieve the same result 
What if we replace n.a. value in the people column in the IBM row. But this can be dangerous because what I am about to do will take effect on the entire column.

### Converter demo

In [20]:
# import csv and create a dataFrame
# conver that csv file into xcel sheet
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/company_financials.csv")
df_cleaned.to_excel(excel_writer = "test_converter.xlsx", header = True, index=True, index_label = 'Index', startrow=0, startcol=0)

In [21]:
def people_col_converter(cell):
    if cell == "n.a.":
        return "Arvind Krishna"
    else:
        return cell
df_excel = pd.read_excel("test_converter.xlsx",converters = {
     "people" : people_col_converter
})
df_excel

    Index     tickers   eps  revenue   price             people
0       0       Apple   NaN   105.55  113.42           Tim Cook
1       1   Microsoft  1.59      NaN  410.99      Satya Nadella
2       2      Google  3.94   118.78   83.55      Sundar Pichai
3       3      Amazon   NaN    69.97  494.10         Andy Jassy
4       4    Facebook  1.30    85.42  397.51    Mark Zuckerberg
5       5       Tesla  1.30      NaN  139.42          Elon Musk
6       6     Netflix  6.74   192.61   52.48      Reed Hastings
7       7       Intel   NaN    99.33  416.96      Pat Gelsinger
8       8         IBM  0.59    47.11  368.09     Arvind Krishna
9       9     Samsung  3.63   141.13  378.05       Jong-Hee Han
10     10      Oracle  0.61    38.96  397.07         Safra Catz
11     11       Cisco  0.60   110.44   83.32      Chuck Robbins
12     12          HP  2.73     2.02  211.31      Enrique Lores
13     13       Adobe -3.74    33.59  102.14   Shantanu Narayen
14     14      Nvidia -3.17   109.84  438.40       Jensen Huang
15     15    Qualcomm  0.31   136.92  330.48     Cristiano Amon
16     16  Salesforce -1.04   108.57  198.90       Marc Benioff
17     17     Spotify  2.94    94.22   78.60          Daniel Ek
18     18        Uber -0.72    84.94  189.94  Dara Khosrowshahi
19     19        Lyft -2.24    26.07  196.33       David Risher
20     20        Snap  6.40      NaN  378.32       Evan Spiegel
21     21     Dropbox  1.32    76.97  336.90       Drew Houston
22     22        Zoom  2.20   152.86  449.25          Eric Yuan
23     23     Twitter -2.27   117.18  262.50    Linda Yaccarino
24     24      PayPal   NaN    11.85  103.82        Alex Chriss

### Explanation:
- people_col_converter function will be called for every single cell in the people column.
- This function will called when creating dataFrame from the excel sheet present in the file system.