# Ways to create dataframe

## There are different ways to create dataframe using data in different form
- Here is the link to the documentation for more info : https://pandas.pydata.org/docs/reference/io.html

## Using csv
- The first way to create a dataframe is to directly read the csv

In [1]:
import pandas as pd
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

## Using Excel

### You may get this error : ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
- In this case you will have to install openpyxl library using pip

In [3]:
df_excel = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.xlsx") 
df_excel

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

## From Python dictionary
 - Create a dataframe using a python dictionary

In [5]:
weather_data = {
    "day":["1/1/2017","1/2/2017","1/3/2017","1/4/2017","1/5/2017","1/6/2017"],
    "temperature":[32,35,28,24,32,31],
    "windspeed":[6,7,2,7,4,2],
    "event":["Rain","Sunny","Snow","Snow","Rain","Sunny"]
}
df_from_dict = pd.DataFrame(weather_data)
df_from_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## From list of tuples

In [6]:
# convert the weather_data into a list of tuples 
list_of_tuples = list(zip(
    weather_data["day"],
    weather_data["temperature"],
    weather_data["windspeed"],
    weather_data["event"]
))
list_of_tuples

[('1/1/2017', 32, 6, 'Rain'),
 ('1/2/2017', 35, 7, 'Sunny'),
 ('1/3/2017', 28, 2, 'Snow'),
 ('1/4/2017', 24, 7, 'Snow'),
 ('1/5/2017', 32, 4, 'Rain'),
 ('1/6/2017', 31, 2, 'Sunny')]

In [8]:
# Generating dataframe from the list of tuples
df_from_list_of_tuples = pd.DataFrame(list_of_tuples, columns = ["day","temperature","windspeed","event"])
df_from_list_of_tuples

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## From the list of dictionaries

In [9]:
# conver the weather data into a list of dictionaries
list_of_dicts = [
    {"day":d,"temperature":t,"windspeed":w,"event":e}
    for d,t,w,e in zip(
        weather_data["day"],
        weather_data["temperature"],
        weather_data["windspeed"],
        weather_data["event"]
    )
]
list_of_dicts

[{'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
 {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
 {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
 {'day': '1/4/2017', 'temperature': 24, 'windspeed': 7, 'event': 'Snow'},
 {'day': '1/5/2017', 'temperature': 32, 'windspeed': 4, 'event': 'Rain'},
 {'day': '1/6/2017', 'temperature': 31, 'windspeed': 2, 'event': 'Sunny'}]

In [10]:
# Generate dataframe from the list of dictioanries
df_from_list_of_dict = pd.DataFrame(list_of_dicts,columns = ["day","temperature","windspeed","event"])
df_from_list_of_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny