# Ways to create dataframe

## There are different ways to create dataframe using data in different form
- Here is the link to the documentation for more info : https://pandas.pydata.org/docs/reference/io.html

## Using csv
- The first way to create a dataframe is to directly read the csv

In [1]:
import pandas as pd
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

## Using Excel

### You may get this error : ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
- In this case you will have to install openpyxl library using pip

In [2]:
df_excel = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.xlsx") 
df_excel

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

## From Python dictionary
 - Create a dataframe using a python dictionary

In [3]:
weather_data = {
    "day":["1/1/2017","1/2/2017","1/3/2017","1/4/2017","1/5/2017","1/6/2017"],
    "temperature":[32,35,28,24,32,31],
    "windspeed":[6,7,2,7,4,2],
    "event":["Rain","Sunny","Snow","Snow","Rain","Sunny"]
}
df_from_dict = pd.DataFrame(weather_data)
df_from_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## From list of tuples

In [4]:
# convert the weather_data into a list of tuples 
list_of_tuples = list(zip(
    weather_data["day"],
    weather_data["temperature"],
    weather_data["windspeed"],
    weather_data["event"]
))
list_of_tuples

[('1/1/2017', 32, 6, 'Rain'),
 ('1/2/2017', 35, 7, 'Sunny'),
 ('1/3/2017', 28, 2, 'Snow'),
 ('1/4/2017', 24, 7, 'Snow'),
 ('1/5/2017', 32, 4, 'Rain'),
 ('1/6/2017', 31, 2, 'Sunny')]

In [5]:
# Generating dataframe from the list of tuples
df_from_list_of_tuples = pd.DataFrame(list_of_tuples, columns = ["day","temperature","windspeed","event"])
df_from_list_of_tuples

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## From the list of dictionaries

In [6]:
# conver the weather data into a list of dictionaries
list_of_dicts = [
    {"day":d,"temperature":t,"windspeed":w,"event":e}
    for d,t,w,e in zip(
        weather_data["day"],
        weather_data["temperature"],
        weather_data["windspeed"],
        weather_data["event"]
    )
]
list_of_dicts

[{'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
 {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
 {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
 {'day': '1/4/2017', 'temperature': 24, 'windspeed': 7, 'event': 'Snow'},
 {'day': '1/5/2017', 'temperature': 32, 'windspeed': 4, 'event': 'Rain'},
 {'day': '1/6/2017', 'temperature': 31, 'windspeed': 2, 'event': 'Sunny'}]

In [7]:
# Generate dataframe from the list of dictioanries
df_from_list_of_dict = pd.DataFrame(list_of_dicts,columns = ["day","temperature","windspeed","event"])
df_from_list_of_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## Using python pickel
- Use python pickel to generate a dataFrame in pandas
- This is the post in stackoverflow what helped me understand : https://stackoverflow.com/questions/64832745/how-can-i-convert-csv-to-pickle

In [8]:
# convert the dataframe to python pickle
df_from_list_of_dict.to_pickle("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.pkl")

# Read pickle file from the file system of linux system.
df_from_pickle = pd.read_pickle("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.pkl")

# print the dataframe read from the pickle file 
df_from_pickle

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## Using JSON data
- Create a dataframe using JSON data from the file system.

In [9]:
df_from_json_data = pd.read_json("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.json")
df_from_json_data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

### json_normalize
- This is used when the data is in nested JSONstructures and we want to convert it into flat pandas DataFrames.
- It can be used when dealing with:
  - JSON from REST api
  - MongoDB documents
  - Complex hierarchial data

In [10]:
# read data from json file named orders.json
df_from_complex_hierarchial_data = pd.read_json("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/orders.json")
df_from_complex_hierarchial_data

,order_id,customer,items,order_date,payment
0,ORD001,"{'id': 'C001', 'name': 'Alice', 'location': {'...","[{'product_id': 'P1001', 'name': 'Laptop', 'pr...",2023-07-01,"{'method': 'Credit Card', 'status': 'Paid'}"
1,ORD002,"{'id': 'C002', 'name': 'Bob', 'location': {'ci...","[{'product_id': 'P1003', 'name': 'Keyboard', '...",2023-07-02,"{'method': 'PayPal', 'status': 'Pending'}"

### Error I encountered : 
- Whe trying to load json I naively tried this way :
- ```
    import json
    data = json.loads("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/orders.json")
  ```
- Error I got : ``` JSONDecodeError: Expecting value: line 1 column 1 (char 0) ```
- When trying to load json I tried to load the json in this way:
- ```
    import json
    with open("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/orders.json", "r") as file:
        data = json.loads(file)
  ```
  - If you do this then you will get the error saying that ``` TypeError: the JSON object must be str, bytes or bytearray, not TextIOWrapper ```

In [11]:
# load json string to a python object
import json
with open("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/orders.json", "r") as file:
    data = json.load(file)
data

[{'order_id': 'ORD001',
  'customer': {'id': 'C001',
   'name': 'Alice',
   'location': {'city': 'New York', 'state': 'NY'}},
  'items': [{'product_id': 'P1001',
    'name': 'Laptop',
    'price': 999.99,
    'quantity': 1},
   {'product_id': 'P1002', 'name': 'Mouse', 'price': 25.5, 'quantity': 2}],
  'order_date': '2023-07-01',
  'payment': {'method': 'Credit Card', 'status': 'Paid'}},
 {'order_id': 'ORD002',
  'customer': {'id': 'C002',
   'name': 'Bob',
   'location': {'city': 'Los Angeles', 'state': 'CA'}},
  'items': [{'product_id': 'P1003',
    'name': 'Keyboard',
    'price': 45.0,
    'quantity': 1}],
  'order_date': '2023-07-02',
  'payment': {'method': 'PayPal', 'status': 'Pending'}}]

In [12]:
# normalize the json data in df_from_complex_hierarchial_data
df_normalized_json_data = pd.json_normalize(data, record_path="items",meta = [
    "order_id",
    "order_date",
    ["customer","name"],
    ["customer","location","city"],
    ["customer","location","state"],
    ["payment","status"]
])
df_normalized_json_data

,product_id,name,price,quantity,order_id,order_date,customer.name,customer.location.city,customer.location.state,payment.status
0,P1001,Laptop,999.99,1,ORD001,2023-07-01,Alice,New York,NY,Paid
1,P1002,Mouse,25.50,2,ORD001,2023-07-01,Alice,New York,NY,Paid
2,P1003,Keyboard,45.00,1,ORD002,2023-07-02,Bob,Los Angeles,CA,Pending

## Using HTML

In [13]:
df = pd.read_html("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/employee.html")[0]
df

      Name   Department  Salary Joining Date
0    Alice  Engineering   85000   2018-07-01
1      Bob           HR   52000   2020-03-15
2  Charlie    Marketing   60000   2019-11-12

## Using xml

In [14]:
df = pd.read_xml("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/employee.xml")
df

      name   department  salary joining_date
0    Alice  Engineering   85000   2018-07-01
1      Bob           HR   52000   2020-03-15
2  Charlie    Marketing   60000   2019-11-12

## Working with HDFStore
- HDF5 is a binary file format designed to store large amounts of data efficiently.
- It can store data in a hierarchical structure (like a file system).
### PyTables
- PyTables is a Python library built on top of HDF5.
- It allows querying and manipulating HDF5 files.
### Use Case:
- Storing large datasets with fast read/write access.
- Splitting datasets into named sections (like "train", "test").
- Efficient storage for time series or multi-indexed data.

In [15]:
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

### Save this dataframe in HDF5 using UDFStore

### Error I faced : PerformanceWarning: your performance may suffer as PyTables will pickle object types ...
- This error means that there are some columns in your dataframe that contains data types that are not effitiently stored using the HDF5 format (which uses pytables under the hood):
  - In particular, object columns like strings datetime or mixed types (e.g, number + strings or Nan + strings) cannot be stored natively and must be pickled, which is slower , larger and not searchablein HDF5.

In [16]:
df.to_hdf("weather.h5",key="newyork_weather_data",mode="w")

/tmp/ipykernel_2963036/662869660.py:1: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['EST', 'PrecipitationIn', 'Events'], dtype='object')]

  df.to_hdf("weather.h5",key="newyork_weather_data",mode="w")

### Read read HDF5 file and create a dataframe out of it

In [17]:
# Convert EST to datetime
df["EST"] = pd.to_datetime(df["EST"], errors="coerce")
# convert precipitation and events to strings or categorical data
df["PrecipitationIn"] = df["PrecipitationIn"].astype("string")
df["Events"] = df["Events"].astype("string") # or use 'category' if repated values

### Error I faced : TypeError: objects of type ``StringArray`` are not supported in this context, sorry; supported objects are: NumPy array, record or scalar; homogeneous list or tuple, integer, float, complex or bytes
- Pandas introduced a proper string dtype (StringArray) to differentiate from older object-based strings. However, PyTables (which is used by to_hdf) doesn't understand this new type yet. It only supports:
  - Primitive NumPy dtypes (int64, float64, bool, object, etc.)
  - Category
  - Arrays of basic types

In [18]:
df.to_hdf("weather.h5", key="newyork_weather_data", mode="w")

TypeError: objects of type ``StringArray`` are not supported in this context, sorry; supported objects are: NumPy array, record or scalar; homogeneous list or tuple, integer, float, complex or bytes

### Tried to resolve this issue by converting string columns to objects in the dataframe

In [ ]:
# Automatically convert all string columns to object
for col in df.select_dtypes(include="string").columns:
    df[col] = df[col].astype("object")

#### Explanation : 
- df.select_dtypes(include="string").columns :
  - This selects all column names in df that are of type "string" (Panda's new nullable StringDtype)
  - select_dtypes is used to filter columns based on their data type.
- df[col] = df[col].astype("object") :
  - It would now be Pandas' StringDtype, and not Python's regular string object.
- for col in ... :
  - It loops through each of those "string" columns.

In [ ]:
df.to_hdf("weather.h5", key="newyork_weather_data", mode="w")

### Earlier I tried to resolve the errors by doing this 
- ``` python
    # Convert EST to datetime
    df["EST"] = pd.to_datetime(df["EST"], errors="coerce")
    # convert precipitation and events to strings or categorical data
    df["PrecipitationIn"] = df["PrecipitationIn"].astype("string")
    df["Events"] = df["Events"].astype("string") # or use 'category' if repated values
    ```
- This time around I am trying this
- ``` python
  # 1. Convert 'EST' to datetime
    df["EST"] = pd.to_datetime(df["EST"], errors="coerce")
    # 2. Convert 'PrecipitationIn' to float (if it contains numeric strings)
    df["PrecipitationIn"] = pd.to_numeric(df["PrecipitationIn"], errors="coerce")
    # 3. Convert 'Events' to category (safest + efficient)
    df["Events"] = df["Events"].astype("category")
  ```

In [19]:
# import csv and create a dataframe
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [20]:
# Fix each problematic column
# 1. Convert 'EST' to datetime
df["EST"] = pd.to_datetime(df["EST"],errors="coerce")
# 2. Convert PrecipitationIn to float (If it contains numeric strings)
df["PrecipitationIn"] = pd.to_numeric(df["PrecipitationIn"],errors="coerce")
# 3. Convert 'Events' to category (safest + effitient)
df["Events"] = df["Events"].astype("category")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2016-01-01,38,23,52,30.03,10,8.0,0.00,5,NaN,281
1,2016-01-02,36,18,46,30.02,10,7.0,0.00,3,NaN,275
2,2016-01-03,40,21,47,29.86,10,8.0,0.00,1,NaN,277
3,2016-01-04,25,9,44,30.05,10,9.0,0.00,3,NaN,345
4,2016-01-05,20,-3,41,30.57,10,5.0,0.00,0,NaN,333
5,2016-01-06,33,4,35,30.50,10,4.0,0.00,0,NaN,259
6,2016-01-07,39,11,33,30.28,10,2.0,0.00,3,NaN,293
7,2016-01-08,39,29,64,30.20,10,4.0,0.00,8,NaN,79
8,2016-01-09,44,38,77,30.16,9,8.0,NaN,8,Rain,76
9,2016-01-10,50,46,71,29.59,4,NaN,1.80,7,Rain,109
10,2016-01-11,33,8,37,29.92,10,NaN,0.00,1,NaN,289
11,2016-01-12,35,15,53,29.85,10,6.0,NaN,4,NaN,235
12,2016-01-13,26,4,42,29.94,10,10.0,0.00,0,NaN,284
13,2016-01-14,30,12,47,29.95,10,5.0,NaN,7,NaN,266
14,2016-01-15,43,31,62,29.82,9,5.0,NaN,2,NaN,101
15,2016-01-16,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,2016-01-17,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,2016-01-18,25,6,53,29.83,9,12.0,NaN,2,Snow,293
18,2016-01-19,22,3,42,30.03,10,11.0,0.00,1,NaN,293
19,2016-01-20,32,15,49,30.13,10,6.0,0.00,2,NaN,302
20,2016-01-21,31,11,45,30.15,10,6.0,0.00,1,NaN,312
21,2016-01-22,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,2016-01-23,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,2016-01-24,28,11,53,29.92,8,6.0,NaN,3,Snow,327
24,2016-01-25,34,18,54,30.25,10,3.0,0.00,2,NaN,286
25,2016-01-26,43,29,56,30.03,10,7.0,0.00,2,NaN,244
26,2016-01-27,41,22,45,30.03,10,7.0,NaN,3,Rain,311
27,2016-01-28,37,20,51,29.90,10,5.0,0.00,1,NaN,234
28,2016-01-29,36,21,50,29.58,10,8.0,0.00,4,NaN,298
29,2016-01-30,34,16,46,30.01,10,7.0,0.00,0,NaN,257
30,2016-01-31,46,28,52,29.90,10,5.0,0.00,0,NaN,241

#### Explanation
- df["EST"] = pd.to_datetime(df["EST"], errors="coerce"):
  - It converts the EST column (date stings like "1/3/2025") into proper datetime64[ns] format.
  - errors = "coerce" means:
    - If a value can't be converted,  It's replaced with NaT (Not a Time) instead of raising an error.
  - It enables powerful data-based operations like sorting, filtering by month/year or resampling.
- df["PrecipitationIn"] = pd.to_numeric(df["PrecipitationIn"], errors="coerce"):
  - Converts values in PrecipitationIn from strings (like "0.5", "T", "NaN", or "--") into float numbers.
  - errors = "coerce" will turn any non-convertible string into NaN.
  - Ensures you can do numeric calcualtions (e.g, mean, sum, plot) on precipitaion data
- df["Events"] = df["Events"].astype("category"):
  - Converts the "Events" column to the "category" data type.
  - Pandas will:
    - Internally map strings like "Rain", "Snow", "Sunny" to integers.
    - Store them more efficiently than objects.
    - Reduces memory usage if the column has repeated values
    - Makes comparision, grouping and filtering faster.

In [21]:
df.to_hdf("weather.h5", key="newyork_weather_data", mode="w")

NotImplementedError: Cannot store a category dtype in a HDF5 dataset that uses format="fixed". Use format="table".

### Error I got : NotImplementedError: Cannot store a category dtype in a HDF5 dataset that uses format="fixed". Use format="table".
- You're trying to save a category column to HDF5 using format="fixed", which is the default format in df.to_hdf().
- Pandas only supports category dtype in format="table", not in the default format="fixed".

#### What is formats in pandas?
- In Pandas the to_hdf() method supports two HDF5 storage formats "fixed" and "table"
- Fixed format:
  - Default format (if you don't specify any format)
  - very fast for writing and reading
  - Stores DataFrame as a single block --> like a snapshot.
  - Does not support filtering queries
  - Does not support category dtypes
- Table format:
  - Slightly slower to write, but more flexible
  - Stores data in a structured way that supports:
    - Querying rows based on column conditions (like SQL)
    - Appending rows to the file later
    - Storing advanced dtypes like category
    - required if the requirement is to store category columns
    - allows partial loading/filtering
- Use case: When the requirment is to:
  - Filter data using query()
  - append new rows to existing HDF5 data, or store category , object or complex types.

In [24]:
df.to_hdf("weather.h5", key="newyork_weather_data", mode="w", format="table")

### Conclusion

### Why this did not work
- ``` python
    df["PrecipitationIn"] = df["PrecipitationIn"].astype("string")
    df["Events"] = df["Events"].astype("string")
  ```
- This failed when saving to HDF5 (with format="fixed") because:
  - "strings" in pandas creates a StringArray extension type, not a regular Numpy array of strings
  - HDF5 with format="fixed" only supports Numpy native types (int, float, str, etc.) not pandas extension types like StringArray, Categorical, NullableInteger etc.
  - So even though the "string" looks like a string, It is an object with internal structure and HDF5 can't serialize it in "fixed" format.
- That's why the error was "TypeError: objects of type 'StringArray' are not supported in this context"
### Why this did work:
- ```python
    df["PrecipitationIn"] = pd.to_numeric(df["PrecipitationIn"], errors="coerce")
    df["Events"] = df["Events"].astype("category")
  ```
- This worked because:
  - PrecipitationIn as float:
    - converted claenly into float64, which is a native Numpy type that HDF5 supports easily.
  - Events as category:
    - I switched to format = "table" and category is only supported in format="table" (not in the default "fixed" format).
    - Categorical data is compact and effietient and is meant for repeat string values (like weather events).

### Now that we have Saved this dataframe in HDF5 using UDFStore. We can move to the next step of creating a dataframe using HDF5 file if given

In [25]:
df = pd.read_hdf("weather.h5")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2016-01-01,38,23,52,30.03,10,8.0,0.00,5,NaN,281
1,2016-01-02,36,18,46,30.02,10,7.0,0.00,3,NaN,275
2,2016-01-03,40,21,47,29.86,10,8.0,0.00,1,NaN,277
3,2016-01-04,25,9,44,30.05,10,9.0,0.00,3,NaN,345
4,2016-01-05,20,-3,41,30.57,10,5.0,0.00,0,NaN,333
5,2016-01-06,33,4,35,30.50,10,4.0,0.00,0,NaN,259
6,2016-01-07,39,11,33,30.28,10,2.0,0.00,3,NaN,293
7,2016-01-08,39,29,64,30.20,10,4.0,0.00,8,NaN,79
8,2016-01-09,44,38,77,30.16,9,8.0,NaN,8,Rain,76
9,2016-01-10,50,46,71,29.59,4,NaN,1.80,7,Rain,109
10,2016-01-11,33,8,37,29.92,10,NaN,0.00,1,NaN,289
11,2016-01-12,35,15,53,29.85,10,6.0,NaN,4,NaN,235
12,2016-01-13,26,4,42,29.94,10,10.0,0.00,0,NaN,284
13,2016-01-14,30,12,47,29.95,10,5.0,NaN,7,NaN,266
14,2016-01-15,43,31,62,29.82,9,5.0,NaN,2,NaN,101
15,2016-01-16,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,2016-01-17,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,2016-01-18,25,6,53,29.83,9,12.0,NaN,2,Snow,293
18,2016-01-19,22,3,42,30.03,10,11.0,0.00,1,NaN,293
19,2016-01-20,32,15,49,30.13,10,6.0,0.00,2,NaN,302
20,2016-01-21,31,11,45,30.15,10,6.0,0.00,1,NaN,312
21,2016-01-22,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,2016-01-23,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,2016-01-24,28,11,53,29.92,8,6.0,NaN,3,Snow,327
24,2016-01-25,34,18,54,30.25,10,3.0,0.00,2,NaN,286
25,2016-01-26,43,29,56,30.03,10,7.0,0.00,2,NaN,244
26,2016-01-27,41,22,45,30.03,10,7.0,NaN,3,Rain,311
27,2016-01-28,37,20,51,29.90,10,5.0,0.00,1,NaN,234
28,2016-01-29,36,21,50,29.58,10,8.0,0.00,4,NaN,298
29,2016-01-30,34,16,46,30.01,10,7.0,0.00,0,NaN,257
30,2016-01-31,46,28,52,29.90,10,5.0,0.00,0,NaN,241

### How to deal with feather in dataFrame 
### What is feather?
- Feather is a lightweight, fast, binary columnar file format designed for efficient storage and transfer of large dataframes. It is based on Apache Arrow, which provides a standard in-memory columnar format.
### When is Feather Useful?
- Saving intermediate data during analysis or ML pipelines:
  - Feather is perfect for temporarily saving a DataFrame between data preprocessing and model training.
- Large datasets with performance needs:
  - When you are working with millions of rows csv becomes slow. Feather's binary reads/writes 10-100x faster.
- Multi-Language projects
  - Feather files can be shared between:
    - Python (Pandas)
    - R (data.table / arrow)
    - Julia/C++/Rust via Arrow
  - This makes Feather an excellent choice for cross-language ML or analytics pipelines.
### Some benefits of using feather
- It's much faster
- Less error-prone (no quoting or delimiter issues)
- Better for storage and transfer

In [26]:
df = pd.DataFrame({
    "name":["Alice","Bob","Charlie"],
    "age": [22,24,28],
    "city":["New York","Los Angeles", "Chicago"]
})
df

      name  age         city
0    Alice   22     New York
1      Bob   24  Los Angeles
2  Charlie   28      Chicago

### Save this dataFrame in feather

In [27]:
df.to_feather("people.feather")

### Now load the dataFrame using feather

In [29]:
df_loaded = pd.read_feather("people.feather")
df_loaded

      name  age         city
0    Alice   22     New York
1      Bob   24  Los Angeles
2  Charlie   28      Chicago

## Working with Parquet

In [31]:
df = pd.DataFrame({
    "name":["Alice","Bob","Charlie"],
    "age": [22,24,28],
    "city":["New York","Los Angeles", "Chicago"]
})
df

      name  age         city
0    Alice   22     New York
1      Bob   24  Los Angeles
2  Charlie   28      Chicago

### How to save a dataFrame in parquet

In [35]:
df.to_parquet("people.parquet", engine="pyarrow")

### Read parquet file and create a dataFrame out of it

In [36]:
df_loaded = pd.read_parquet("people.parquet",engine="pyarrow")
df_loaded

      name  age         city
0    Alice   22     New York
1      Bob   24  Los Angeles
2  Charlie   28      Chicago

### Difference between Parquet vs Feather
| Feature                     | Feather                                         | Parquet                                |
| --------------------------- | ----------------------------------------------- | -------------------------------------- |
| Compression                 | Optional, not default                           | Built-in, highly optimized             |
| Schema support              | Basic                                           | Rich schema with metadata              |
| Partitioning (for big data) | ❌ Not supported                                 | ✅ Yes (great for large data workflows) |
| Speed (small to mid data)   | ⚡ Extremely fast                                | ⚡ Very fast                            |
| Best for                    | Local pandas workflows                          | Large-scale analytics (Spark, etc.)    |
| Language support            | Python, R, Julia                                | Python, R, Spark, Hive, Dask, etc.     |
| File size                   | Smaller than CSV, bigger than Parquet (usually) | Often the smallest                     |

### Real-World use cases for parquet
- Interfacing between Pandas and Spark.
- Solving large datasets with effitient compression.
- Querying datasets using Dask, Polars or SQL engines.
- Partitioned storage on S3 or data lakesc (via Hive-style paths)

### You can also compress parquet with snappy

In [37]:
df.to_parquet("people_compressed.parquet", compression="snappy", engine="pyarrow")

### Lets try to load df using that compressed parquet file

In [38]:
df_compressed_pq = pd.read_parquet("people_compressed.parquet")
df_compressed_pq

      name  age         city
0    Alice   22     New York
1      Bob   24  Los Angeles
2  Charlie   28      Chicago

### What is Parquet best for and how to use it?
#### 1. Large datasets:
- When your CSV or Excel files becomes slow to read or write or start exceeding memory limits
- Paraquet stores data in columnar format, which means:
  - You only read the columns you need.
  - It's faster and more memory-efficient
#### 2. Repeated use of data
  - Saving intermediate data in pipelines (ETL, ML preprocessing) here ETL means Extrat transform load.
  - Store once --> reuse many times without recomputing.
#### 3. Compressed Storage
  - Parquet supports built-in compression (like snappy, gzip) which:
    - Saves disk space
    - Speeds up loading speed (less I/O)
#### 4. Working with big data tools
  - Parquet is native to:
    - Apache spark
    - Dask
    - Polars
    - Hive, Presto, Athena, Snowflake
#### 5. Column filtering and analytics
  - when you need just a few columns out of many (common in analytics dashboards or api serivces)
  - Columnar structure makes it lightning fast.
#### What is a columnar structure?
  - In a columnar structure data is stored in column by column instead of row by row.
  - +--------+-----+--------+
    | Name   | Age | City   |
    +--------+-----+--------+
    | Alice  | 24  | NYC    |
    | Bob    | 30  | Chicago|
    | Charlie| 28  | Boston |
  - Name:    [Alice, Bob, Charlie]
    Age:     [24, 30, 28]
    City:    [NYC, Chicago, Boston]
  - Lets say I have a datset of 100 million rows and I need to calculate the average salary.
    - In row-based format (CSV)
      - All the columns are read into memory even if you only want the "salary".
    - In columnar format (Parquet):
      - Only the "salary" column is read --- making it faster and more memory efficient.
### Real world use cases
#### 1. Data Science pipelines 
```python
# Save once after cleaning
df_cleaned.to_parquet("cleaned_data.parquet", compression="snappy")
# Load instantly for ML or dashboarding
df_model_input = pd.read_parquet("cleaned_data.parquet", columns=["feature1", "feature2"])
```
#### 2. Enterprise Reporting
- Your analytics team runs dashboards querying millions of rows stored in Parquet on S3.
- Tools like Apache superset, Tableau or Athena read dir
#### 3. Data Versioning 
- Keep snapshot of dataset in effitient format.
- Tag files with timestamp data_2024_07_15.parquet
#### 4. Cloud data Lakes 
- Parquet integrates seamlessly with:
  - AWS athena, google BigQuery, Azure Synapse
  - You don't need a database -- Just read structured data directly from cloud storage.
### Paraquet vs Other formats:
| Format      | Read/Write Speed  | Size      | Schema  | Compression | Best For                 |
| ----------- | ----------------- | --------- | ------- | ----------- | ------------------------ |
| CSV         | 🐢 Slow           | 🔺 Large  | ❌ No    | ❌ No        | Debugging, sharing       |
| JSON        | 🐢 Slow           | 🔺 Large  | ✅ Some  | ❌ No        | Nested/Hierarchical data |
| Feather     | ⚡ Fast            | 🔸 Medium | Limited | Optional    | In-memory transfer       |
| **Parquet** | ⚡ Fast (scalable) | 🔻 Small  | ✅ Full  | ✅ Yes       | Analytics, big data      |

## Working with ORC

In [40]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Chicago", "Boston"]
})
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30   Chicago
2  Charlie   35    Boston

### Convert a dataframe in orc file format and save it system's file system

In [42]:
df.to_orc("people_data.orc",engine="pyarrow")

### Read data from orc file format and create a dataframe out of it

In [43]:
df_orc = pd.read_orc("people_data.orc")
df_orc

      Name  Age      City
0    Alice   25  New York
1      Bob   30   Chicago
2  Charlie   35    Boston

### These are the questions that poped up in my head : 
### ORC behind the scenes
- ORC = Optimized Row Columnar format.
- Very efficient for big data processing.
- Commonly used with Apache hive, Spark and Hadoop ecosystems.
- Like Paraquet, It's columnar, compresses well and supports schema evolution.
### When to use ORC?
| Use Case                         | Why ORC?                    |
| -------------------------------- | --------------------------- |
| Hadoop or Hive-based data lakes  | Native integration          |
| Large-scale analytical queries   | Fast scan/filter/projection |
| When you need better compression | Efficient column encoding   |
### What is schema evolution?
- Schema Evolution means the ability to change the structure of data (schema) over time without breaking the existing pipelines.
- So according to what I found if there is a dataFrame with 3 columns in an ORC or paraquet file. Later my app evolves and starts writing more columns or removes or changes existing ones.
- With schema evolution, your system can still read and write data seamlessly, even if the schema has changed across versions of the dataset.

#### Example : (Schema Evolution with paraquet)
#### Version 1 of the data :

In [45]:
df_v1 = pd.DataFrame({
    "id":[1,2],
    "name":["Alice","Bob"]
})
df_v1.to_parquet("data_v1.parquet")

#### New version adds a column

In [46]:
df_v2 = pd.DataFrame({
    "id":[3],
    "name":["charlie"],
    "age":[30]
})
df_v2.to_parquet("data_v2.parquet",append=True)

TypeError: __cinit__() got an unexpected keyword argument 'append'

### Analysis as to why I got this error?
- Unlike to_csv() or to_hdf(), the to_paraquet() method does not support appending to an existing Parquet file out of the box.
- Internally to_parquet() calls Parquet engine like (pyarrow and fastparquet) and neither engine supports appending to Parquet files natively due to the structure of Parquet format --- It is columnar and optimized for immutable, efficient batch writes, not row-wise appends
### So is there a workaround to this problem?
- According to what I found:
  - Read the old file.
  - Concatenate the new data
  - Overwirte the file
### But if I have to do this will this be called schema evolution?
- No, manually reading, concatenating, and overwriting Parquet files is not true schema evolution. It’s a workaround, not a native solution.
- Schema evolution means the system automatically handles changes in the data structure over time such as:
  - Adding new columns
  - Removing or renaming columns
  - Changing data types
- And still allows:
  - Reading old and new data togeather
  - Appending new schema-compaint records
  - Querying without breaking due to version mismatches
- This is supported in systems like:
  - Apache Hive
  - Apache spark
  - Delta Lake
  - Apache Iceberge
  - BigQuery
  - SnowFlake
### Colcusion I have to handle schema evolution manually in pandas.
- Schema evolution: If I add a new column age and aligned old data with it
- Old rows have Nan or pd.Na for missing values.
- This way I will have to avoid errors and preserve backward compatibility.
### Best Practices:
- Always read + align schema before appening.
- Use a schema versioning strategy if your dataset evolve frequently
- Store metadata alongside your Parquet files it needed.
- I have to consider Delat Lake, Hudi or Iceberge if i want an automatic schema evolution support.

### Re-trying schema evolution manually in pandas

In [48]:
df_day1 = pd.DataFrame({
    "id" : [1,2],
    "name" : ["Rollex","Ballistic"]
})
df_day1

   id       name
0   1     Rollex
1   2  Ballistic

#### Saving the dataFrame in Parquet file format

In [54]:
df_day1.to_parquet("day1_data.parquet")

#### Read the data from parquet and convert it to the dataframe

In [55]:
parquet_dataFrame = pd.read_parquet("day1_data.parquet")
parquet_dataFrame

   id       name
0   1     Rollex
1   2  Ballistic

#### Add a new column in the dataFrame generated from the stored paraquet file

In [56]:
df_day2 = pd.DataFrame({
    "id":[3],
    "name":["Ignition"],
    "roll_no":6000
})
df_day2

   id      name  roll_no
0   3  Ignition     6000

In [58]:
df_old = parquet_dataFrame

# Align schemas (schema evolution logic)
# Already has it 
df_day2["age"] = df_day2.get("age",pd.NA)
# Add missing columns to the old data_frame
df_old["age"] = pd.NA

# combine and overwrite
df_combine = pd.concat([df_old,df_day2],ignore_index = True)
df_combine.to_parquet("day2_data.parquet",index=False)

#### df_day2["age"] = df_day2.get("age",pd.NA) Explaination:
- Purpose: Ensure that the "age" column exists in "df_day2".
- How it works:
  - df_day2.get("age",pd.NA) looks for the "age" column in "df_days2".
  - If it exists, it keeps its original values.
  - If it doesn't exist, It fills the column with pd.NA (Pandas' scalar missing value).
- This is the safe way to ensure the column exists without raising an error.
#### df_old["age"] = pd.NA Explaination:
- Purpose: Add the "age" column to the old DataFrame (df_old) and fill it with missing values
- Since df_old doesn't originally have "age", this line adds the column explicitly with all values as missing (pd.NA).

#### Now finally reading the latest dataFrame stored in parquet file.

In [60]:
df_latest_data = pd.read_parquet("day2_data.parquet")
df_latest_data

   id       name   age  roll_no
0   1     Rollex  None      NaN
1   2  Ballistic  None      NaN
2   3   Ignition  None   6000.0