# Ways to create dataframe

## There are different ways to create dataframe using data in different form
- Here is the link to the documentation for more info : https://pandas.pydata.org/docs/reference/io.html

## Using csv
- The first way to create a dataframe is to directly read the csv

In [1]:
import pandas as pd
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

## Using Excel

### You may get this error : ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
- In this case you will have to install openpyxl library using pip

In [3]:
df_excel = pd.read_excel("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.xlsx") 
df_excel

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

## From Python dictionary
 - Create a dataframe using a python dictionary

In [5]:
weather_data = {
    "day":["1/1/2017","1/2/2017","1/3/2017","1/4/2017","1/5/2017","1/6/2017"],
    "temperature":[32,35,28,24,32,31],
    "windspeed":[6,7,2,7,4,2],
    "event":["Rain","Sunny","Snow","Snow","Rain","Sunny"]
}
df_from_dict = pd.DataFrame(weather_data)
df_from_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## From list of tuples

In [6]:
# convert the weather_data into a list of tuples 
list_of_tuples = list(zip(
    weather_data["day"],
    weather_data["temperature"],
    weather_data["windspeed"],
    weather_data["event"]
))
list_of_tuples

[('1/1/2017', 32, 6, 'Rain'),
 ('1/2/2017', 35, 7, 'Sunny'),
 ('1/3/2017', 28, 2, 'Snow'),
 ('1/4/2017', 24, 7, 'Snow'),
 ('1/5/2017', 32, 4, 'Rain'),
 ('1/6/2017', 31, 2, 'Sunny')]

In [8]:
# Generating dataframe from the list of tuples
df_from_list_of_tuples = pd.DataFrame(list_of_tuples, columns = ["day","temperature","windspeed","event"])
df_from_list_of_tuples

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## From the list of dictionaries

In [9]:
# conver the weather data into a list of dictionaries
list_of_dicts = [
    {"day":d,"temperature":t,"windspeed":w,"event":e}
    for d,t,w,e in zip(
        weather_data["day"],
        weather_data["temperature"],
        weather_data["windspeed"],
        weather_data["event"]
    )
]
list_of_dicts

[{'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
 {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
 {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
 {'day': '1/4/2017', 'temperature': 24, 'windspeed': 7, 'event': 'Snow'},
 {'day': '1/5/2017', 'temperature': 32, 'windspeed': 4, 'event': 'Rain'},
 {'day': '1/6/2017', 'temperature': 31, 'windspeed': 2, 'event': 'Sunny'}]

In [10]:
# Generate dataframe from the list of dictioanries
df_from_list_of_dict = pd.DataFrame(list_of_dicts,columns = ["day","temperature","windspeed","event"])
df_from_list_of_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## Using python pickel
- Use python pickel to generate a dataFrame in pandas
- This is the post in stackoverflow what helped me understand : https://stackoverflow.com/questions/64832745/how-can-i-convert-csv-to-pickle

In [12]:
# convert the dataframe to python pickle
df_from_list_of_dict.to_pickle("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.pkl")

# Read pickle file from the file system of linux system.
df_from_pickle = pd.read_pickle("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.pkl")

# print the dataframe read from the pickle file 
df_from_pickle

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## Using JSON data
- Create a dataframe using JSON data from the file system.

In [13]:
df_from_json_data = pd.read_json("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.json")
df_from_json_data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

### json_normalize
- This is used when the data is in nested JSONstructures and we want to convert it into flat pandas DataFrames.
- It can be used when dealing with:
  - JSON from REST api
  - MongoDB documents
  - Complex hierarchial data

In [17]:
# read data from json file named orders.json
df_from_complex_hierarchial_data = pd.read_json("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/orders.json")
df_from_complex_hierarchial_data

,order_id,customer,items,order_date,payment
0,ORD001,"{'id': 'C001', 'name': 'Alice', 'location': {'...","[{'product_id': 'P1001', 'name': 'Laptop', 'pr...",2023-07-01,"{'method': 'Credit Card', 'status': 'Paid'}"
1,ORD002,"{'id': 'C002', 'name': 'Bob', 'location': {'ci...","[{'product_id': 'P1003', 'name': 'Keyboard', '...",2023-07-02,"{'method': 'PayPal', 'status': 'Pending'}"

### Error I encountered : 
- Whe trying to load json I naively tried this way :
- ```
    import json
    data = json.loads("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/orders.json")
  ```
- Error I got : ``` JSONDecodeError: Expecting value: line 1 column 1 (char 0) ```
- When trying to load json I tried to load the json in this way:
- ```
    import json
    with open("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/orders.json", "r") as file:
        data = json.loads(file)
  ```
  - If you do this then you will get the error saying that ``` TypeError: the JSON object must be str, bytes or bytearray, not TextIOWrapper ```

In [29]:
# load json string to a python object
import json
with open("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/orders.json", "r") as file:
    data = json.load(file)
data

[{'order_id': 'ORD001',
  'customer': {'id': 'C001',
   'name': 'Alice',
   'location': {'city': 'New York', 'state': 'NY'}},
  'items': [{'product_id': 'P1001',
    'name': 'Laptop',
    'price': 999.99,
    'quantity': 1},
   {'product_id': 'P1002', 'name': 'Mouse', 'price': 25.5, 'quantity': 2}],
  'order_date': '2023-07-01',
  'payment': {'method': 'Credit Card', 'status': 'Paid'}},
 {'order_id': 'ORD002',
  'customer': {'id': 'C002',
   'name': 'Bob',
   'location': {'city': 'Los Angeles', 'state': 'CA'}},
  'items': [{'product_id': 'P1003',
    'name': 'Keyboard',
    'price': 45.0,
    'quantity': 1}],
  'order_date': '2023-07-02',
  'payment': {'method': 'PayPal', 'status': 'Pending'}}]

In [30]:
# normalize the json data in df_from_complex_hierarchial_data
df_normalized_json_data = pd.json_normalize(data, record_path="items",meta = [
    "order_id",
    "order_date",
    ["customer","name"],
    ["customer","location","city"],
    ["customer","location","state"],
    ["payment","status"]
])
df_normalized_json_data

,product_id,name,price,quantity,order_id,order_date,customer.name,customer.location.city,customer.location.state,payment.status
0,P1001,Laptop,999.99,1,ORD001,2023-07-01,Alice,New York,NY,Paid
1,P1002,Mouse,25.50,2,ORD001,2023-07-01,Alice,New York,NY,Paid
2,P1003,Keyboard,45.00,1,ORD002,2023-07-02,Bob,Los Angeles,CA,Pending

## Using HTML

In [32]:
df = pd.read_html("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/employee.html")[0]
df

      Name   Department  Salary Joining Date
0    Alice  Engineering   85000   2018-07-01
1      Bob           HR   52000   2020-03-15
2  Charlie    Marketing   60000   2019-11-12

## Using xml

In [36]:
df = pd.read_xml("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/employee.xml")
df

      name   department  salary joining_date
0    Alice  Engineering   85000   2018-07-01
1      Bob           HR   52000   2020-03-15
2  Charlie    Marketing   60000   2019-11-12

## Working with HDFStore
- HDF5 is a binary file format designed to store large amounts of data efficiently.
- It can store data in a hierarchical structure (like a file system).
### PyTables
- PyTables is a Python library built on top of HDF5.
- It allows querying and manipulating HDF5 files.
### Use Case:
- Storing large datasets with fast read/write access.
- Splitting datasets into named sections (like "train", "test").
- Efficient storage for time series or multi-indexed data.

In [44]:
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

### Save this dataframe in HDF5 using UDFStore

### Error I faced : PerformanceWarning: your performance may suffer as PyTables will pickle object types ...
- This error means that there are some columns in your dataframe that contains data types that are not effitiently stored using the HDF5 format (which uses pytables under the hood):
  - In particular, object columns like strings datetime or mixed types (e.g, number + strings or Nan + strings) cannot be stored natively and must be pickled, which is slower , larger and not searchablein HDF5.

In [45]:
df.to_hdf("weather.h5",key="newyork_weather_data",mode="w")

/tmp/ipykernel_113227/662869660.py:1: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['EST', 'PrecipitationIn', 'Events'], dtype='object')]

  df.to_hdf("weather.h5",key="newyork_weather_data",mode="w")

### Read read HDF5 file and create a dataframe out of it

In [46]:
# Convert EST to datetime
df["EST"] = pd.to_datetime(df["EST"], errors="coerce")
# convert precipitation and events to strings or categorical data
df["PrecipitationIn"] = df["PrecipitationIn"].astype("string")
df["Events"] = df["Events"].astype("string") # or use 'category' if repated values

### Error I faced : TypeError: objects of type ``StringArray`` are not supported in this context, sorry; supported objects are: NumPy array, record or scalar; homogeneous list or tuple, integer, float, complex or bytes
- Pandas introduced a proper string dtype (StringArray) to differentiate from older object-based strings. However, PyTables (which is used by to_hdf) doesn't understand this new type yet. It only supports:
  - Primitive NumPy dtypes (int64, float64, bool, object, etc.)
  - Category
  - Arrays of basic types

In [47]:
df.to_hdf("weather.h5", key="newyork_weather_data", mode="w")

TypeError: objects of type ``StringArray`` are not supported in this context, sorry; supported objects are: NumPy array, record or scalar; homogeneous list or tuple, integer, float, complex or bytes

### Tried to resolve this issue by converting string columns to objects in the dataframe

In [48]:
# Automatically convert all string columns to object
for col in df.select_dtypes(include="string").columns:
    df[col] = df[col].astype("object")

In [49]:
df.to_hdf("weather.h5", key="newyork_weather_data", mode="w")

/tmp/ipykernel_113227/3525566113.py:1: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['Events'], dtype='object')]

  df.to_hdf("weather.h5", key="newyork_weather_data", mode="w")

### Earlier I tried to resolve the errors by doing this 
- ``` python
    # Convert EST to datetime
    df["EST"] = pd.to_datetime(df["EST"], errors="coerce")
    # convert precipitation and events to strings or categorical data
    df["PrecipitationIn"] = df["PrecipitationIn"].astype("string")
    df["Events"] = df["Events"].astype("string") # or use 'category' if repated values
    ```
- This time around I am trying this
- ``` python
  # 1. Convert 'EST' to datetime
    df["EST"] = pd.to_datetime(df["EST"], errors="coerce")
    # 2. Convert 'PrecipitationIn' to float (if it contains numeric strings)
    df["PrecipitationIn"] = pd.to_numeric(df["PrecipitationIn"], errors="coerce")
    # 3. Convert 'Events' to category (safest + efficient)
    df["Events"] = df["Events"].astype("category")
  ```

In [50]:
# import csv and create a dataframe
df = pd.read_csv("/home/aditya/github/Deep-learning-prerequisite/pandas/dataset/nyc_weather.csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [53]:
# Fix each problematic column
# 1. Convert 'EST' to datetime
df["EST"] = pd.to_datetime(df["EST"],errors="coerce")
# 2. Convert PrecipitationIn to float (If it contains numeric strings)
df["PrecipitationIn"] = pd.to_numeric(df["PrecipitationIn"],errors="coerce")
# 3. Convert 'Events' to category (safest + effitient)
df["Events"] = df["Events"].astype("category")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2016-01-01,38,23,52,30.03,10,8.0,0.00,5,NaN,281
1,2016-01-02,36,18,46,30.02,10,7.0,0.00,3,NaN,275
2,2016-01-03,40,21,47,29.86,10,8.0,0.00,1,NaN,277
3,2016-01-04,25,9,44,30.05,10,9.0,0.00,3,NaN,345
4,2016-01-05,20,-3,41,30.57,10,5.0,0.00,0,NaN,333
5,2016-01-06,33,4,35,30.50,10,4.0,0.00,0,NaN,259
6,2016-01-07,39,11,33,30.28,10,2.0,0.00,3,NaN,293
7,2016-01-08,39,29,64,30.20,10,4.0,0.00,8,NaN,79
8,2016-01-09,44,38,77,30.16,9,8.0,NaN,8,Rain,76
9,2016-01-10,50,46,71,29.59,4,NaN,1.80,7,Rain,109
10,2016-01-11,33,8,37,29.92,10,NaN,0.00,1,NaN,289
11,2016-01-12,35,15,53,29.85,10,6.0,NaN,4,NaN,235
12,2016-01-13,26,4,42,29.94,10,10.0,0.00,0,NaN,284
13,2016-01-14,30,12,47,29.95,10,5.0,NaN,7,NaN,266
14,2016-01-15,43,31,62,29.82,9,5.0,NaN,2,NaN,101
15,2016-01-16,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,2016-01-17,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,2016-01-18,25,6,53,29.83,9,12.0,NaN,2,Snow,293
18,2016-01-19,22,3,42,30.03,10,11.0,0.00,1,NaN,293
19,2016-01-20,32,15,49,30.13,10,6.0,0.00,2,NaN,302
20,2016-01-21,31,11,45,30.15,10,6.0,0.00,1,NaN,312
21,2016-01-22,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,2016-01-23,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,2016-01-24,28,11,53,29.92,8,6.0,NaN,3,Snow,327
24,2016-01-25,34,18,54,30.25,10,3.0,0.00,2,NaN,286
25,2016-01-26,43,29,56,30.03,10,7.0,0.00,2,NaN,244
26,2016-01-27,41,22,45,30.03,10,7.0,NaN,3,Rain,311
27,2016-01-28,37,20,51,29.90,10,5.0,0.00,1,NaN,234
28,2016-01-29,36,21,50,29.58,10,8.0,0.00,4,NaN,298
29,2016-01-30,34,16,46,30.01,10,7.0,0.00,0,NaN,257
30,2016-01-31,46,28,52,29.90,10,5.0,0.00,0,NaN,241

In [55]:
df.to_hdf("weather.h5", key="newyork_weather_data", mode="w")

NotImplementedError: Cannot store a category dtype in a HDF5 dataset that uses format="fixed". Use format="table".

### Error I got : NotImplementedError: Cannot store a category dtype in a HDF5 dataset that uses format="fixed". Use format="table".
- You're trying to save a category column to HDF5 using format="fixed", which is the default format in df.to_hdf().
- Pandas only supports category dtype in format="table", not in the default format="fixed".

#### What is formats in pandas?
- In Pandas the to_hdf() method supports two HDF5 storage formats "fixed" and "table"
- Fixed format:
  - Default format (if you don't specify any format)
  - very fast for writing and reading
  - Stores DataFrame as a single block --> like a snapshot.
  - Does not support filtering queries
  - Does not support category dtypes
- Table format:
  - Slightly slower to write, but more flexible
  - Stores data in a structured way that supports:
    - Querying rows based on column conditions (like SQL)
    - Appending rows to the file later
    - Storing advanced dtypes like category
    - required if the requirement is to store category columns
    - allows partial loading/filtering
- Use case: When the requirment is to:
  - Filter data using query()
  - append new rows to existing HDF5 data, or store category , object or complex types.

In [58]:
df.to_hdf("weather.h5", key="newyork_weather_data", mode="w", format="table")

### Conclusion

### Why this did not work
- ``` python
    df["PrecipitationIn"] = df["PrecipitationIn"].astype("string")
    df["Events"] = df["Events"].astype("string")
  ```
- This failed when saving to HDF5 (with format="fixed") because:
  - "strings" in pandas creates a StringArray extension type, not a regular Numpy array of strings
  - HDF5 with format="fixed" only supports Numpy native types (int, float, str, etc.) not pandas extension types like StringArray, Categorical, NullableInteger etc.
  - So even though the "string" looks like a string, It is an object with internal structure and HDF5 can't serialize it in "fixed" format.
- That's why the error was "TypeError: objects of type 'StringArray' are not supported in this context"
### Why this did work:
- ```python
    df["PrecipitationIn"] = pd.to_numeric(df["PrecipitationIn"], errors="coerce")
    df["Events"] = df["Events"].astype("category")
  ```
- This worked because:
  - PrecipitationIn as float:
    - converted claenly into float64, which is a native Numpy type that HDF5 supports easily.
  - Events as category:
    - I switched to format = "table" and category is only supported in format="table" (not in the default "fixed" format).
    - Categorical data is compact and effietient and is meant for repeat string values (like weather events).